#!/usr/bin/env python3
"""Fill common still-English stencil names across tool/stencil_maps/*.json.

Targets high-frequency leftovers (Bang, Block, Boundary, Intermediate events, …).
Run: python3 tool/fill_stencil_leftovers.py && python3 tool/finish_editor_l10n.py
"""

from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path(__file__).with_name("stencil_maps")

# English name → per-language translation. Languages omitted keep current value.
# Shared cognates / acronyms (X, UML tokens) intentionally left English.
FILLS: dict[str, dict[str, str]] = {
    "Bang": {
        "fr": "Bang", "de": "Knall", "es": "Bang", "it": "Bang", "pt": "Bang",
        "nl": "Bang", "pl": "Bang", "ru": "Взрыв", "uk": "Вибух", "cs": "Bouch",
        "sk": "Buch", "ro": "Bang", "hu": "Pukk", "el": "Κρότος", "hr": "Bang",
        "bg": "Гръм", "sv": "Smäll", "da": "Bang", "nb": "Smell", "fi": "Poks",
        "id": "Bang", "ms": "Bang", "fil": "Putok", "vi": "Nổ", "th": "แบง",
        "tr": "Pat", "hi": "धमाका", "ar": "انفجار", "he": "בום", "bn": "ব্যাং",
        "fa": "انفجار", "sw": "Bang", "ca": "Bang", "ja": "バン", "ko": "뱅",
    },
    "Block": {
        "fr": "Bloc", "de": "Block", "es": "Bloque", "it": "Blocco", "pt": "Bloco",
        "nl": "Blok", "pl": "Blok", "ru": "Блок", "uk": "Блок", "cs": "Blok",
        "sk": "Blok", "ro": "Bloc", "hu": "Blokk", "el": "Μπλοκ", "hr": "Blok",
        "bg": "Блок", "sv": "Block", "da": "Blok", "nb": "Blokk", "fi": "Lohko",
        "id": "Blok", "ms": "Blok", "fil": "Blok", "vi": "Khối", "th": "บล็อก",
        "tr": "Blok", "hi": "ब्लॉक", "ar": "كتلة", "he": "בלוק", "bn": "ব্লক",
        "fa": "بلوک", "sw": "Blok", "ca": "Bloc",
    },
    "Boundary": {
        "fr": "Frontière", "de": "Grenze", "es": "Límite", "it": "Confine", "pt": "Limite",
        "nl": "Grens", "pl": "Granica", "ru": "Граница", "uk": "Межа", "cs": "Hranice",
        "sk": "Hranica", "ro": "Limită", "hu": "Határ", "el": "Όριο", "hr": "Granica",
        "bg": "Граница", "sv": "Gräns", "da": "Grænse", "nb": "Grense", "fi": "Raja",
        "id": "Batas", "ms": "Sempadan", "fil": "Hangganan", "vi": "Ranh giới", "th": "ขอบเขต",
        "tr": "Sınır", "hi": "सीमा", "ar": "حدود", "he": "גבול", "bn": "সীমানা",
        "fa": "مرز", "sw": "Mpaka", "ca": "Límit",
    },
    "Control": {
        "fr": "Contrôle", "de": "Steuerung", "es": "Control", "it": "Controllo", "pt": "Controlo",
        "nl": "Besturing", "pl": "Sterowanie", "ru": "Управление", "uk": "Керування", "cs": "Řízení",
        "sk": "Riadenie", "ro": "Control", "hu": "Vezérlés", "el": "Έλεγχος", "hr": "Upravljanje",
        "bg": "Контрол", "sv": "Kontroll", "da": "Kontrol", "nb": "Kontroll", "fi": "Ohjaus",
        "id": "Kontrol", "ms": "Kawalan", "fil": "Kontrol", "vi": "Điều khiển", "th": "ควบคุม",
        "tr": "Kontrol", "hi": "नियंत्रण", "ar": "تحكم", "he": "בקרה", "bn": "নিয়ন্ত্রণ",
        "fa": "کنترل", "sw": "Udhibiti", "ca": "Control",
    },
    "Banner": {
        "fr": "Bannière", "de": "Banner", "es": "Banner", "it": "Banner", "pt": "Faixa",
        "nl": "Banner", "pl": "Baner", "ru": "Баннер", "uk": "Банер", "cs": "Banner",
        "sk": "Banner", "ro": "Banner", "hu": "Banner", "el": "Πανό", "hr": "Banner",
        "bg": "Банер", "sv": "Banner", "da": "Banner", "nb": "Banner", "fi": "Banneri",
        "id": "Spanduk", "ms": "Sepanduk", "fil": "Banner", "vi": "Biểu ngữ", "th": "แบนเนอร์",
        "tr": "Afiş", "hi": "बैनर", "ar": "لافتة", "he": "באנר", "bn": "ব্যানার",
        "fa": "بنر", "sw": "Bango", "ca": "Bàner",
    },
    "Chevron": {
        "fr": "Chevron", "de": "Chevron", "es": "Galón", "it": "Chevron", "pt": "Chevron",
        "nl": "Chevron", "pl": "Szewron", "ru": "Шеврон", "uk": "Шеврон", "cs": "Šipka",
        "sk": "Šípka", "ro": "Chevron", "hu": "Chevron", "el": "Σιρίτι", "hr": "Ševron",
        "bg": "Шеврон", "sv": "Chevron", "da": "Chevron", "nb": "Chevron", "fi": "Chevron",
        "id": "Chevron", "ms": "Chevron", "fil": "Chevron", "vi": "Mũi nhọn", "th": "เชฟรอน",
        "tr": "Şevron", "hi": "शेवरॉन", "ar": "شيفرون", "he": "שברון", "bn": "শেভরন",
        "fa": "شورون", "sw": "Chevron", "ca": "Galó",
    },
    "Cone": {
        "fr": "Cône", "de": "Kegel", "es": "Cono", "it": "Cono", "pt": "Cone",
        "nl": "Kegel", "pl": "Stożek", "ru": "Конус", "uk": "Конус", "cs": "Kužel",
        "sk": "Kužeľ", "ro": "Con", "hu": "Kúp", "el": "Κώνος", "hr": "Stožac",
        "bg": "Конус", "sv": "Kon", "da": "Kegle", "nb": "Kjegle", "fi": "Kartio",
        "id": "Kerucut", "ms": "Kon", "fil": "Kono", "vi": "Hình nón", "th": "กรวย",
        "tr": "Koni", "hi": "शंकु", "ar": "مخروط", "he": "חרוט", "bn": "শঙ্কু",
        "fa": "مخروط", "sw": "Koni", "ca": "Con",
    },
    "Drop": {
        "fr": "Goutte", "de": "Tropfen", "es": "Gota", "it": "Goccia", "pt": "Gota",
        "nl": "Druppel", "pl": "Kropla", "ru": "Капля", "uk": "Крапля", "cs": "Kapka",
        "sk": "Kvapka", "ro": "Picătură", "hu": "Csepp", "el": "Σταγόνα", "hr": "Kap",
        "bg": "Капка", "sv": "Droppe", "da": "Dråbe", "nb": "Dråpe", "fi": "Pisara",
        "id": "Tetes", "ms": "Titisan", "fil": "Patak", "vi": "Giọt", "th": "หยด",
        "tr": "Damla", "hi": "बूंद", "ar": "قطرة", "he": "טיפה", "bn": "ফোঁটা",
        "fa": "قطره", "sw": "Tone", "ca": "Got",
    },
    "Flash": {
        "fr": "Flash", "de": "Blitz", "es": "Destello", "it": "Flash", "pt": "Flash",
        "nl": "Flits", "pl": "Błysk", "ru": "Вспышка", "uk": "Спалах", "cs": "Záblesk",
        "sk": "Záblesk", "ro": "Flash", "hu": "Villanás", "el": "Φλας", "hr": "Bljesak",
        "bg": "Светкавица", "sv": "Blixt", "da": "Blitz", "nb": "Blitz", "fi": "Salama",
        "id": "Kilat", "ms": "Kilat", "fil": "Kidlat", "vi": "Chớp", "th": "แฟลช",
        "tr": "Flaş", "hi": "फ्लैश", "ar": "وميض", "he": "הבזק", "bn": "ফ্ল্যাশ",
        "fa": "فلاش", "sw": "Mweko", "ca": "Flaix",
    },
    "Step": {
        "fr": "Étape", "de": "Schritt", "es": "Paso", "it": "Passo", "pt": "Passo",
        "nl": "Stap", "pl": "Krok", "ru": "Шаг", "uk": "Крок", "cs": "Krok",
        "sk": "Krok", "ro": "Pas", "hu": "Lépés", "el": "Βήμα", "hr": "Korak",
        "bg": "Стъпка", "sv": "Steg", "da": "Trin", "nb": "Trinn", "fi": "Askel",
        "id": "Langkah", "ms": "Langkah", "fil": "Hakbang", "vi": "Bước", "th": "ขั้น",
        "tr": "Adım", "hi": "चरण", "ar": "خطوة", "he": "שלב", "bn": "ধাপ",
        "fa": "گام", "sw": "Hatua", "ca": "Pas",
    },
    "Sum": {
        "fr": "Somme", "de": "Summe", "es": "Suma", "it": "Somma", "pt": "Soma",
        "nl": "Som", "pl": "Suma", "ru": "Сумма", "uk": "Сума", "cs": "Součet",
        "sk": "Súčet", "ro": "Sumă", "hu": "Összeg", "el": "Άθροισμα", "hr": "Zbroj",
        "bg": "Сума", "sv": "Summa", "da": "Sum", "nb": "Sum", "fi": "Summa",
        "id": "Jumlah", "ms": "Jumlah", "fil": "Kabuuan", "vi": "Tổng", "th": "ผลรวม",
        "tr": "Toplam", "hi": "योग", "ar": "مجموع", "he": "סכום", "bn": "যোগফল",
        "fa": "جمع", "sw": "Jumla", "ca": "Suma",
    },
    "Switch": {
        "fr": "Commutateur", "de": "Schalter", "es": "Interruptor", "it": "Interruttore", "pt": "Interruptor",
        "nl": "Schakelaar", "pl": "Przełącznik", "ru": "Переключатель", "uk": "Перемикач", "cs": "Přepínač",
        "sk": "Prepínač", "ro": "Comutator", "hu": "Kapcsoló", "el": "Διακόπτης", "hr": "Prekidač",
        "bg": "Превключвател", "sv": "Växel", "da": "Kontakt", "nb": "Bryter", "fi": "Kytkin",
        "id": "Sakelar", "ms": "Suis", "fil": "Switch", "vi": "Công tắc", "th": "สวิตช์",
        "tr": "Anahtar", "hi": "स्विच", "ar": "مفتاح", "he": "מתג", "bn": "সুইচ",
        "fa": "کلید", "sw": "Swichi", "ca": "Interruptor",
    },
    "Tag": {
        "fr": "Étiquette", "de": "Tag", "es": "Etiqueta", "it": "Etichetta", "pt": "Etiqueta",
        "nl": "Label", "pl": "Tag", "ru": "Метка", "uk": "Мітка", "cs": "Štítek",
        "sk": "Štítok", "ro": "Etichetă", "hu": "Címke", "el": "Ετικέτα", "hr": "Oznaka",
        "bg": "Етикет", "sv": "Tagg", "da": "Mærke", "nb": "Merkelapp", "fi": "Tunniste",
        "id": "Tag", "ms": "Tag", "fil": "Tag", "vi": "Thẻ", "th": "แท็ก",
        "tr": "Etiket", "hi": "टैग", "ar": "وسم", "he": "תג", "bn": "ট্যাগ",
        "fa": "برچسب", "sw": "Lebo", "ca": "Etiqueta",
    },
    "Terminate": {
        "fr": "Terminer", "de": "Beenden", "es": "Terminar", "it": "Termina", "pt": "Terminar",
        "nl": "Beëindigen", "pl": "Zakończ", "ru": "Завершить", "uk": "Завершити", "cs": "Ukončit",
        "sk": "Ukončiť", "ro": "Terminare", "hu": "Lezárás", "el": "Τερματισμός", "hr": "Završi",
        "bg": "Прекратяване", "sv": "Avsluta", "da": "Afslut", "nb": "Avslutt", "fi": "Lopeta",
        "id": "Akhiri", "ms": "Tamatkan", "fil": "Tapusin", "vi": "Kết thúc", "th": "ยุติ",
        "tr": "Sonlandır", "hi": "समाप्त", "ar": "إنهاء", "he": "סיום", "bn": "সমাপ্তি",
        "fa": "پایان", "sw": "Maliza", "ca": "Finalitza",
    },
    "Tick": {
        "fr": "Coche", "de": "Häkchen", "es": "Marca", "it": "Spunta", "pt": "Marca",
        "nl": "Vinkje", "pl": "Znacznik", "ru": "Галочка", "uk": "Галочка", "cs": "Fajfka",
        "sk": "Fajka", "ro": "Bifă", "hu": "Pipa", "el": "Τικ", "hr": "Kvačica",
        "bg": "Отметка", "sv": "Bock", "da": "Flueben", "nb": "Hake", "fi": "Ruksi",
        "id": "Centang", "ms": "Tanda semak", "fil": "Tsek", "vi": "Dấu tick", "th": "ติ๊ก",
        "tr": "Onay", "hi": "टिक", "ar": "علامة", "he": "סימון", "bn": "টিক",
        "fa": "تیک", "sw": "Alama", "ca": "Marca",
    },
    "Transfer": {
        "fr": "Transfert", "de": "Transfer", "es": "Transferencia", "it": "Trasferimento", "pt": "Transferência",
        "nl": "Overdracht", "pl": "Transfer", "ru": "Передача", "uk": "Передача", "cs": "Přenos",
        "sk": "Prenos", "ro": "Transfer", "hu": "Átvitel", "el": "Μεταφορά", "hr": "Prijenos",
        "bg": "Прехвърляне", "sv": "Överföring", "da": "Overførsel", "nb": "Overføring", "fi": "Siirto",
        "id": "Transfer", "ms": "Pemindahan", "fil": "Paglipat", "vi": "Chuyển", "th": "โอน",
        "tr": "Aktarım", "hi": "स्थानांतरण", "ar": "نقل", "he": "העברה", "bn": "স্থানান্তর",
        "fa": "انتقال", "sw": "Uhamisho", "ca": "Transferència",
    },
    "Module": {
        "fr": "Module", "de": "Modul", "es": "Módulo", "it": "Modulo", "pt": "Módulo",
        "nl": "Module", "pl": "Moduł", "ru": "Модуль", "uk": "Модуль", "cs": "Modul",
        "sk": "Modul", "ro": "Modul", "hu": "Modul", "el": "Μονάδα", "hr": "Modul",
        "bg": "Модул", "sv": "Modul", "da": "Modul", "nb": "Modul", "fi": "Moduuli",
        "id": "Modul", "ms": "Modul", "fil": "Module", "vi": "Mô-đun", "th": "โมดูล",
        "tr": "Modül", "hi": "मॉड्यूल", "ar": "وحدة", "he": "מודול", "bn": "মডিউল",
        "fa": "ماژول", "sw": "Moduli", "ca": "Mòdul",
    },
    "Pyramid": {
        "fr": "Pyramide", "de": "Pyramide", "es": "Pirámide", "it": "Piramide", "pt": "Pirâmide",
        "nl": "Piramide", "pl": "Piramida", "ru": "Пирамида", "uk": "Піраміда", "cs": "Pyramida",
        "sk": "Pyramída", "ro": "Piramidă", "hu": "Piramis", "el": "Πυραμίδα", "hr": "Piramida",
        "bg": "Пирамида", "sv": "Pyramid", "da": "Pyramide", "nb": "Pyramide", "fi": "Pyramidi",
        "id": "Piramida", "ms": "Piramid", "fil": "Pyramid", "vi": "Kim tự tháp", "th": "พีระมิด",
        "tr": "Piramit", "hi": "पिरामिड", "ar": "هرم", "he": "פירמידה", "bn": "পিরামিড",
        "fa": "هرم", "sw": "Piramidi", "ca": "Piràmide",
    },
    "Arc": {
        "fr": "Arc", "de": "Bogen", "es": "Arco", "it": "Arco", "pt": "Arco",
        "nl": "Boog", "pl": "Łuk", "ru": "Дуга", "uk": "Дуга", "cs": "Oblouk",
        "sk": "Oblúk", "ro": "Arc", "hu": "Ív", "el": "Τόξο", "hr": "Luk",
        "bg": "Дъга", "sv": "Båge", "da": "Bue", "nb": "Bue", "fi": "Kaari",
        "id": "Busur", "ms": "Lengkuk", "fil": "Arko", "vi": "Cung", "th": "ส่วนโค้ง",
        "tr": "Yay", "hi": "चाप", "ar": "قوس", "he": "קשת", "bn": "চাপ",
        "fa": "کمان", "sw": "Upinde", "ca": "Arc",
    },
    "Card": {
        "fr": "Carte", "de": "Karte", "es": "Tarjeta", "it": "Scheda", "pt": "Cartão",
        "nl": "Kaart", "pl": "Karta", "ru": "Карточка", "uk": "Картка", "cs": "Karta",
        "sk": "Karta", "ro": "Card", "hu": "Kártya", "el": "Κάρτα", "hr": "Kartica",
        "bg": "Карта", "sv": "Kort", "da": "Kort", "nb": "Kort", "fi": "Kortti",
        "id": "Kartu", "ms": "Kad", "fil": "Card", "vi": "Thẻ", "th": "การ์ด",
        "tr": "Kart", "hi": "कार्ड", "ar": "بطاقة", "he": "כרטיס", "bn": "কার্ড",
        "fa": "کارت", "sw": "Kadi", "ca": "Targeta",
    },
    "Pool": {
        "fr": "Piscine", "de": "Pool", "es": "Piscina", "it": "Pool", "pt": "Piscina",
        "nl": "Pool", "pl": "Basen", "ru": "Пул", "uk": "Пул", "cs": "Bazén",
        "sk": "Bazén", "ro": "Pool", "hu": "Medence", "el": "Πισίνα", "hr": "Bazen",
        "bg": "Басейн", "sv": "Pool", "da": "Pool", "nb": "Basseng", "fi": "Allas",
        "id": "Kolam", "ms": "Kolam", "fil": "Pool", "vi": "Bể", "th": "พูล",
        "tr": "Havuz", "hi": "पूल", "ar": "مسبح", "he": "בריכה", "bn": "পুল",
        "fa": "استخر", "sw": "Bwawa", "ca": "Piscina",
    },
    "Delay": {
        "fr": "Délai", "de": "Verzögerung", "es": "Retraso", "it": "Ritardo", "pt": "Atraso",
        "nl": "Vertraging", "pl": "Opóźnienie", "ru": "Задержка", "uk": "Затримка", "cs": "Zpoždění",
        "sk": "Oneskorenie", "ro": "Întârziere", "hu": "Késleltetés", "el": "Καθυστέρηση", "hr": "Kašnjenje",
        "bg": "Забавяне", "sv": "Fördröjning", "da": "Forsinkelse", "nb": "Forsinkelse", "fi": "Viive",
        "id": "Tunda", "ms": "Lengah", "fil": "Antala", "vi": "Trễ", "th": "หน่วง",
        "tr": "Gecikme", "hi": "विलंब", "ar": "تأخير", "he": "השהיה", "bn": "বিলম্ব",
        "fa": "تأخیر", "sw": "Kuchelewa", "ca": "Retard",
    },
    "Display": {
        "fr": "Affichage", "de": "Anzeige", "es": "Pantalla", "it": "Display", "pt": "Ecrã",
        "nl": "Weergave", "pl": "Wyświetlacz", "ru": "Дисплей", "uk": "Дисплей", "cs": "Displej",
        "sk": "Displej", "ro": "Afișaj", "hu": "Kijelző", "el": "Οθόνη", "hr": "Prikaz",
        "bg": "Дисплей", "sv": "Skärm", "da": "Skærm", "nb": "Skjerm", "fi": "Näyttö",
        "id": "Tampilan", "ms": "Paparan", "fil": "Display", "vi": "Hiển thị", "th": "จอแสดงผล",
        "tr": "Ekran", "hi": "डिस्प्ले", "ar": "عرض", "he": "תצוגה", "bn": "ডিসপ্লে",
        "fa": "نمایش", "sw": "Onyesho", "ca": "Pantalla",
    },
    "Preparation": {
        "fr": "Préparation", "de": "Vorbereitung", "es": "Preparación", "it": "Preparazione", "pt": "Preparação",
        "nl": "Voorbereiding", "pl": "Przygotowanie", "ru": "Подготовка", "uk": "Підготовка", "cs": "Příprava",
        "sk": "Príprava", "ro": "Pregătire", "hu": "Előkészítés", "el": "Προετοιμασία", "hr": "Priprema",
        "bg": "Подготовка", "sv": "Förberedelse", "da": "Forberedelse", "nb": "Forberedelse", "fi": "Valmistelu",
        "id": "Persiapan", "ms": "Persediaan", "fil": "Paghahanda", "vi": "Chuẩn bị", "th": "การเตรียม",
        "tr": "Hazırlık", "hi": "तैयारी", "ar": "تحضير", "he": "הכנה", "bn": "প্রস্তুতি",
        "fa": "آماده‌سازی", "sw": "Maandalizi", "ca": "Preparació",
    },
    "Collate": {
        "fr": "Assembler", "de": "Zusammenführen", "es": "Compilar", "it": "Raccogliere", "pt": "Agrupar",
        "nl": "Verzamelen", "pl": "Zestaw", "ru": "Сопоставление", "uk": "Зіставлення", "cs": "Sestavit",
        "sk": "Zostaviť", "ro": "Colationare", "hu": "Összeállítás", "el": "Συλλογή", "hr": "Sastavi",
        "bg": "Съпоставяне", "sv": "Sammanställ", "da": "Saml", "nb": "Samle", "fi": "Koosta",
        "id": "Susun", "ms": "Kumpul", "fil": "Tipunin", "vi": "Tập hợp", "th": "เรียงรวม",
        "tr": "Birleştir", "hi": "संकलित", "ar": "تجميع", "he": "איסוף", "bn": "সংকলন",
        "fa": "گردآوری", "sw": "Kusanya", "ca": "Reuneix",
    },
    "Extract": {
        "fr": "Extraire", "de": "Extrahieren", "es": "Extraer", "it": "Estrai", "pt": "Extrair",
        "nl": "Extraheren", "pl": "Wyodrębnij", "ru": "Извлечь", "uk": "Видобути", "cs": "Extrahovat",
        "sk": "Extrahovať", "ro": "Extrage", "hu": "Kinyerés", "el": "Εξαγωγή", "hr": "Izdvoji",
        "bg": "Извличане", "sv": "Extrahera", "da": "Udtræk", "nb": "Hent ut", "fi": "Poimi",
        "id": "Ekstrak", "ms": "Ekstrak", "fil": "Kunin", "vi": "Trích xuất", "th": "แยก",
        "tr": "Çıkar", "hi": "निकालें", "ar": "استخراج", "he": "חילוץ", "bn": "এক্সট্র্যাক্ট",
        "fa": "استخراج", "sw": "Toa", "ca": "Extreu",
    },
    "Sort": {
        "fr": "Trier", "de": "Sortieren", "es": "Ordenar", "it": "Ordina", "pt": "Ordenar",
        "nl": "Sorteren", "pl": "Sortuj", "ru": "Сортировка", "uk": "Сортування", "cs": "Seřadit",
        "sk": "Zoradiť", "ro": "Sortare", "hu": "Rendezés", "el": "Ταξινόμηση", "hr": "Sortiraj",
        "bg": "Сортиране", "sv": "Sortera", "da": "Sortér", "nb": "Sorter", "fi": "Lajittele",
        "id": "Urutkan", "ms": "Isih", "fil": "Ayusin", "vi": "Sắp xếp", "th": "เรียง",
        "tr": "Sırala", "hi": "क्रमबद्ध", "ar": "فرز", "he": "מיון", "bn": "সাজান",
        "fa": "مرتب‌سازی", "sw": "Panga", "ca": "Ordena",
    },
    "Merge": {
        "fr": "Fusionner", "de": "Zusammenführen", "es": "Combinar", "it": "Unisci", "pt": "Unir",
        "nl": "Samenvoegen", "pl": "Scal", "ru": "Объединить", "uk": "Об'єднати", "cs": "Sloučit",
        "sk": "Zlúčiť", "ro": "Îmbinare", "hu": "Egyesítés", "el": "Συγχώνευση", "hr": "Spoji",
        "bg": "Обединяване", "sv": "Sammanfoga", "da": "Flet", "nb": "Slå sammen", "fi": "Yhdistä",
        "id": "Gabung", "ms": "Gabung", "fil": "Pagsamahin", "vi": "Gộp", "th": "รวม",
        "tr": "Birleştir", "hi": "मर्ज", "ar": "دمج", "he": "מיזוג", "bn": "মার্জ",
        "fa": "ادغام", "sw": "Unganisha", "ca": "Combina",
    },
    "Lightning": {
        "fr": "Éclair", "de": "Blitz", "es": "Rayo", "it": "Fulmine", "pt": "Raio",
        "nl": "Bliksem", "pl": "Błyskawica", "ru": "Молния", "uk": "Блискавка", "cs": "Blesk",
        "sk": "Blesk", "ro": "Fulger", "hu": "Villám", "el": "Αστραπή", "hr": "Munja",
        "bg": "Светкавица", "sv": "Blixt", "da": "Lyn", "nb": "Lyn", "fi": "Salama",
        "id": "Petir", "ms": "Kilat", "fil": "Kidlat", "vi": "Sét", "th": "สายฟ้า",
        "tr": "Şimşek", "hi": "बिजली", "ar": "برق", "he": "ברק", "bn": "বজ্র",
        "fa": "صاعقه", "sw": "Umeme", "ca": "Llampec",
    },
    "Donut": {
        "fr": "Anneau", "de": "Ring", "es": "Anillo", "it": "Anello", "pt": "Anel",
        "nl": "Donut", "pl": "Pierścień", "ru": "Кольцо", "uk": "Кільце", "cs": "Prstenec",
        "sk": "Prstenec", "ro": "Inel", "hu": "Gyűrű", "el": "Δακτύλιος", "hr": "Prsten",
        "bg": "Пръстен", "sv": "Ring", "da": "Ring", "nb": "Ring", "fi": "Rengas",
        "id": "Donat", "ms": "Donat", "fil": "Donut", "vi": "Vòng", "th": "โดนัท",
        "tr": "Halka", "hi": "डोनट", "ar": "حلقة", "he": "טבעת", "bn": "ডোনাট",
        "fa": "حلقه", "sw": "Pete", "ca": "Anell",
    },
    "Pie": {
        "fr": "Secteur", "de": "Kreissegment", "es": "Sector", "it": "Settore", "pt": "Setor",
        "nl": "Taartpunt", "pl": "Wycinek", "ru": "Сектор", "uk": "Сектор", "cs": "Výseč",
        "sk": "Výsek", "ro": "Sector", "hu": "Szelet", "el": "Τομέας", "hr": "Isječak",
        "bg": "Сектор", "sv": "Cirkelsektor", "da": "Cirkeludsnit", "nb": "Sektordiagram", "fi": "Piirakka",
        "id": "Pie", "ms": "pai", "fil": "Pie", "vi": "Hình quạt", "th": "พาย",
        "tr": "Dilim", "hi": "पाई", "ar": "قطاع", "he": "פרוסה", "bn": "পাই",
        "fa": "برش دایره", "sw": "Kipande", "ca": "Sector",
    },
    "Frame": {
        "fr": "Cadre", "de": "Rahmen", "es": "Marco", "it": "Cornice", "pt": "Moldura",
        "nl": "Kader", "pl": "Ramka", "ru": "Рамка", "uk": "Рамка", "cs": "Rám",
        "sk": "Rám", "ro": "Cadru", "hu": "Keret", "el": "Πλαίσιο", "hr": "Okvir",
        "bg": "Рамка", "sv": "Ram", "da": "Ramme", "nb": "Ramme", "fi": "Kehys",
        "id": "Bingkai", "ms": "Bingkai", "fil": "Frame", "vi": "Khung", "th": "กรอบ",
        "tr": "Çerçeve", "hi": "फ़्रेम", "ar": "إطار", "he": "מסגרת", "bn": "ফ্রেম",
        "fa": "قاب", "sw": "Fremu", "ca": "Marc",
    },
    "Cube": {
        "fr": "Cube", "de": "Würfel", "es": "Cubo", "it": "Cubo", "pt": "Cubo",
        "nl": "Kubus", "pl": "Sześcian", "ru": "Куб", "uk": "Куб", "cs": "Krychle",
        "sk": "Kocka", "ro": "Cub", "hu": "Kocka", "el": "Κύβος", "hr": "Kocka",
        "bg": "Куб", "sv": "Kub", "da": "Terning", "nb": "Kube", "fi": "Kuutio",
        "id": "Kubus", "ms": "Kiub", "fil": "Kubo", "vi": "Khối lập phương", "th": "ลูกบาศก์",
        "tr": "Küp", "hi": "घन", "ar": "مكعب", "he": "קובייה", "bn": "ঘনক",
        "fa": "مکعب", "sw": "Mchemraba", "ca": "Cub",
    },
    "Hexagon": {
        "fr": "Hexagone", "de": "Sechseck", "es": "Hexágono", "it": "Esagono", "pt": "Hexágono",
        "nl": "Zeshoek", "pl": "Sześciokąt", "ru": "Шестиугольник", "uk": "Шестикутник", "cs": "Šestiúhelník",
        "sk": "Šesťuholník", "ro": "Hexagon", "hu": "Hatszög", "el": "Εξάγωνο", "hr": "Šesterokut",
        "bg": "Шестоъгълник", "sv": "Hexagon", "da": "Sekskant", "nb": "Heksagon", "fi": "Kuusikulmio",
        "id": "Heksagon", "ms": "Heksagon", "fil": "Heksagono", "vi": "Lục giác", "th": "หกเหลี่ยม",
        "tr": "Altıgen", "hi": "षट्कोण", "ar": "سداسي", "he": "משושה", "bn": "ষড়ভুজ",
        "fa": "شش‌ضلعی", "sw": "Sita-pembe", "ca": "Hexàgon",
    },
    "Pentagon": {
        "fr": "Pentagone", "de": "Fünfeck", "es": "Pentágono", "it": "Pentagono", "pt": "Pentágono",
        "nl": "Vijfhoek", "pl": "Pięciokąt", "ru": "Пятиугольник", "uk": "П’ятикутник", "cs": "Pětiúhelník",
        "sk": "Päťuholník", "ro": "Pentagon", "hu": "Ötszög", "el": "Πεντάγωνο", "hr": "Peterokut",
        "bg": "Петоъгълник", "sv": "Pentagon", "da": "Femkant", "nb": "Pentagon", "fi": "Viisikulmio",
        "id": "Segilima", "ms": "Pentagon", "fil": "Pentagono", "vi": "Ngũ giác", "th": "ห้าเหลี่ยม",
        "tr": "Beşgen", "hi": "पंचभुज", "ar": "خماسي", "he": "מחומש", "bn": "পঞ্চভুজ",
        "fa": "پنج‌ضلعی", "sw": "Tano-pembe", "ca": "Pentàgon",
    },
    "Activation Bar": {
        "fr": "Barre d’activation", "de": "Aktivierungsbalken", "es": "Barra de activación",
        "it": "Barra di attivazione", "pt": "Barra de ativação", "nl": "Activeringsbalk",
        "pl": "Pasek aktywacji", "ru": "Полоса активации", "uk": "Смуга активації",
        "cs": "Aktivační pruh", "sk": "Aktivačný pruh", "ro": "Bară de activare",
        "hu": "Aktiválási sáv", "el": "Ράβδος ενεργοποίησης", "hr": "Traka aktivacije",
        "bg": "Лента за активиране", "sv": "Aktiveringsfält", "da": "Aktiveringsbjælke",
        "nb": "Aktiveringsstolpe", "fi": "Aktivointipalkki", "id": "Bilah aktivasi",
        "ms": "Bar pengaktifan", "fil": "Bar ng activation", "vi": "Thanh kích hoạt",
        "th": "แถบเปิดใช้งาน", "tr": "Etkinleştirme çubuğu", "hi": "सक्रियण पट्टी",
        "ar": "شريط التفعيل", "he": "סרגל הפעלה", "bn": "অ্যাক্টিভেশন বার",
        "fa": "نوار فعال‌سازی", "sw": "Upau wa uanzishaji", "ca": "Barra d’activació",
    },
    "Cancel Intermediate": {
        "fr": "Intermédiaire d’annulation", "de": "Abbruch (Zwischen)", "es": "Intermedio de cancelación",
        "it": "Intermedio di annullamento", "pt": "Intermédio de cancelamento", "nl": "Annuleren (tussen)",
        "pl": "Anulowanie pośrednie", "ru": "Промежуточная отмена", "uk": "Проміжне скасування",
        "cs": "Zrušení (mezi)", "sk": "Zrušenie (medzi)", "ro": "Anulare intermediară",
        "hu": "Mégsem köztes", "el": "Ακύρωση ενδιάμεση", "hr": "Odustani međusobno",
        "bg": "Междинно отказване", "sv": "Avbryt mellan", "da": "Annuller mellem",
        "nb": "Avbryt mellom", "fi": "Peruuta väli", "id": "Batal menengah",
        "ms": "Batal perantaraan", "fil": "Kanselahin (gitna)", "vi": "Hủy trung gian",
        "th": "ยกเลิกกลาง", "tr": "İptal ara", "hi": "रद्द मध्यवर्ती",
        "ar": "إلغاء وسيط", "he": "ביטול ביניים", "bn": "বাতিল মধ্যবর্তী",
        "fa": "لغو میانی", "sw": "Ghairi kati", "ca": "Cancel·la intermedi",
    },
    "Compensation Intermediate": {
        "fr": "Intermédiaire de compensation", "de": "Kompensation (Zwischen)", "es": "Intermedio de compensación",
        "it": "Intermedio di compensazione", "pt": "Intermédio de compensação", "nl": "Compensatie (tussen)",
        "pl": "Kompensacja pośrednia", "ru": "Промежуточная компенсация", "uk": "Проміжна компенсація",
        "cs": "Kompenzace (mezi)", "sk": "Kompenzácia (medzi)", "ro": "Compensare intermediară",
        "hu": "Kompenzáció köztes", "el": "Αποζημίωση ενδιάμεση", "hr": "Kompenzacija međusobna",
        "bg": "Междинна компенсация", "sv": "Kompensation mellan", "da": "Kompensation mellem",
        "nb": "Kompensasjon mellom", "fi": "Kompensaatio väli", "id": "Kompensasi menengah",
        "ms": "Pampasan perantaraan", "fil": "Compensation (gitna)", "vi": "Bù trừ trung gian",
        "th": "ชดเชยกลาง", "tr": "Telafi ara", "hi": "मुआवज़ा मध्यवर्ती",
        "ar": "تعويض وسيط", "he": "פיצוי ביניים", "bn": "ক্ষতিপূরণ মধ্যবর্তী",
        "fa": "جبران میانی", "sw": "Fidia kati", "ca": "Compensació intermèdia",
    },
    "Timer Intermediate": {
        "fr": "Intermédiaire minuteur", "de": "Timer (Zwischen)", "es": "Intermedio de temporizador",
        "it": "Intermedio timer", "pt": "Intermédio de temporizador", "nl": "Timer (tussen)",
        "pl": "Timer pośredni", "ru": "Промежуточный таймер", "uk": "Проміжний таймер",
        "cs": "Časovač (mezi)", "sk": "Časovač (medzi)", "ro": "Temporizator intermediar",
        "hu": "Időzítő köztes", "el": "Χρονόμετρο ενδιάμεσο", "hr": "Tajmer međusobni",
        "bg": "Междинен таймер", "sv": "Timer mellan", "da": "Timer mellem",
        "nb": "Timer mellom", "fi": "Ajastin väli", "id": "Timer menengah",
        "ms": "Pemasa perantaraan", "fil": "Timer (gitna)", "vi": "Hẹn giờ trung gian",
        "th": "ตัวจับเวลากลาง", "tr": "Zamanlayıcı ara", "hi": "टाइमर मध्यवर्ती",
        "ar": "مؤقت وسيط", "he": "טיימר ביניים", "bn": "টাইমার মধ্যবর্তী",
        "fa": "زمان‌سنج میانی", "sw": "Kipima muda kati", "ca": "Temporitzador intermedi",
    },
    "Link Intermediate": {
        "fr": "Intermédiaire lien", "de": "Link (Zwischen)", "es": "Intermedio de enlace",
        "it": "Intermedio collegamento", "pt": "Intermédio de ligação", "nl": "Koppeling (tussen)",
        "pl": "Łącze pośrednie", "ru": "Промежуточная ссылка", "uk": "Проміжне посилання",
        "cs": "Odkaz (mezi)", "sk": "Odkaz (medzi)", "ro": "Link intermediar",
        "hu": "Hivatkozás köztes", "el": "Σύνδεσμος ενδιάμεσος", "hr": "Veza međusobna",
        "bg": "Междинна връзка", "sv": "Länk mellan", "da": "Link mellem",
        "nb": "Kobling mellom", "fi": "Linkki väli", "id": "Tautan menengah",
        "ms": "Pautan perantaraan", "fil": "Link (gitna)", "vi": "Liên kết trung gian",
        "th": "ลิงก์กลาง", "tr": "Bağlantı ara", "hi": "लिंक मध्यवर्ती",
        "ar": "رابط وسيط", "he": "קישור ביניים", "bn": "লিংক মধ্যবর্তী",
        "fa": "پیوند میانی", "sw": "Kiungo kati", "ca": "Enllaç intermedi",
    },
    "Multiple Intermediate": {
        "fr": "Intermédiaire multiple", "de": "Mehrfach (Zwischen)", "es": "Intermedio múltiple",
        "it": "Intermedio multiplo", "pt": "Intermédio múltiplo", "nl": "Meervoudig (tussen)",
        "pl": "Wielokrotne pośrednie", "ru": "Промежуточное множественное", "uk": "Проміжне множинне",
        "cs": "Vícenásobné (mezi)", "sk": "Viacnásobné (medzi)", "ro": "Multiplu intermediar",
        "hu": "Többszörös köztes", "el": "Πολλαπλό ενδιάμεσο", "hr": "Višestruko međusobno",
        "bg": "Междинно множествено", "sv": "Multipel mellan", "da": "Multipel mellem",
        "nb": "Multippel mellom", "fi": "Moninkertainen väli", "id": "Multipel menengah",
        "ms": "Berbilang perantaraan", "fil": "Maramihan (gitna)", "vi": "Đa trung gian",
        "th": "หลายกลาง", "tr": "Çoklu ara", "hi": "बहु मध्यवर्ती",
        "ar": "متعدد وسيط", "he": "מרובה ביניים", "bn": "একাধিক মধ্যবর্তী",
        "fa": "چندگانه میانی", "sw": "Nyingi kati", "ca": "Múltiple intermedi",
    },
    "Signal In": {
        "fr": "Signal entrant", "de": "Signal ein", "es": "Señal de entrada",
        "it": "Segnale in", "pt": "Sinal de entrada", "nl": "Signaal in",
        "pl": "Sygnał wejściowy", "ru": "Входящий сигнал", "uk": "Вхідний сигнал",
        "cs": "Signál vstup", "sk": "Signál vstup", "ro": "Semnal intrare",
        "hu": "Jel be", "el": "Σήμα εισόδου", "hr": "Signal ulaz",
        "bg": "Входящ сигнал", "sv": "Signal in", "da": "Signal ind",
        "nb": "Signal inn", "fi": "Signaali sisään", "id": "Sinyal masuk",
        "ms": "Isyarat masuk", "fil": "Signal pasok", "vi": "Tín hiệu vào",
        "th": "สัญญาณเข้า", "tr": "Sinyal giriş", "hi": "सिग्नल इन",
        "ar": "إشارة داخلة", "he": "אות נכנס", "bn": "সিগন্যাল ইন",
        "fa": "سیگنال ورودی", "sw": "Ishara kuingia", "ca": "Senyal d’entrada",
    },
    "Internal Storage": {
        "fr": "Stockage interne", "de": "Interner Speicher", "es": "Almacenamiento interno",
        "it": "Archiviazione interna", "pt": "Armazenamento interno", "nl": "Interne opslag",
        "pl": "Pamięć wewnętrzna", "ru": "Внутреннее хранилище", "uk": "Внутрішнє сховище",
        "cs": "Vnitřní úložiště", "sk": "Vnútorné úložisko", "ro": "Stocare internă",
        "hu": "Belső tároló", "el": "Εσωτερική αποθήκευση", "hr": "Unutarnja pohrana",
        "bg": "Вътрешно хранилище", "sv": "Intern lagring", "da": "Intern lager",
        "nb": "Intern lagring", "fi": "Sisäinen tallennus", "id": "Penyimpanan internal",
        "ms": "Storan dalaman", "fil": "Panloob na imbakan", "vi": "Lưu trữ nội bộ",
        "th": "ที่เก็บภายใน", "tr": "Dahili depolama", "hi": "आंतरिक भंडारण",
        "ar": "تخزين داخلي", "he": "אחסון פנימי", "bn": "অভ্যন্তরীণ স্টোরেজ",
        "fa": "ذخیره داخلی", "sw": "Hifadhi ya ndani", "ca": "Emmagatzematge intern",
    },
    "Manual Input": {
        "fr": "Saisie manuelle", "de": "Manuelle Eingabe", "es": "Entrada manual",
        "it": "Input manuale", "pt": "Entrada manual", "nl": "Handmatige invoer",
        "pl": "Wprowadzanie ręczne", "ru": "Ручной ввод", "uk": "Ручне введення",
        "cs": "Ruční vstup", "sk": "Ručný vstup", "ro": "Intrare manuală",
        "hu": "Kézi bevitel", "el": "Χειροκίνητη είσοδος", "hr": "Ručni unos",
        "bg": "Ръчно въвеждане", "sv": "Manuell inmatning", "da": "Manuel indtastning",
        "nb": "Manuell inndata", "fi": "Manuaalinen syöttö", "id": "Input manual",
        "ms": "Input manual", "fil": "Manwal na input", "vi": "Nhập thủ công",
        "th": "ป้อนด้วยมือ", "tr": "Manuel girdi", "hi": "मैन्युअल इनपुट",
        "ar": "إدخال يدوي", "he": "קלט ידני", "bn": "ম্যানুয়াল ইনপুট",
        "fa": "ورودی دستی", "sw": "Ingizo la mkono", "ca": "Entrada manual",
    },
    "Manual Operation": {
        "fr": "Opération manuelle", "de": "Manuelle Operation", "es": "Operación manual",
        "it": "Operazione manuale", "pt": "Operação manual", "nl": "Handmatige bewerking",
        "pl": "Operacja ręczna", "ru": "Ручная операция", "uk": "Ручна операція",
        "cs": "Ruční operace", "sk": "Ručná operácia", "ro": "Operațiune manuală",
        "hu": "Kézi művelet", "el": "Χειροκίνητη λειτουργία", "hr": "Ručna operacija",
        "bg": "Ръчна операция", "sv": "Manuell åtgärd", "da": "Manuel handling",
        "nb": "Manuell operasjon", "fi": "Manuaalinen toiminto", "id": "Operasi manual",
        "ms": "Operasi manual", "fil": "Manwal na operasyon", "vi": "Thao tác thủ công",
        "th": "ปฏิบัติการด้วยมือ", "tr": "Manuel işlem", "hi": "मैन्युअल संचालन",
        "ar": "عملية يدوية", "he": "פעולה ידנית", "bn": "ম্যানুয়াল অপারেশন",
        "fa": "عملیات دستی", "sw": "Operesheni ya mkono", "ca": "Operació manual",
    },
    "Object": {
        "fr": "Objet", "de": "Objekt", "es": "Objeto", "it": "Oggetto", "pt": "Objeto",
        "nl": "Object", "pl": "Obiekt", "ru": "Объект", "uk": "Об’єкт", "cs": "Objekt",
        "sk": "Objekt", "ro": "Obiect", "hu": "Objektum", "el": "Αντικείμενο", "hr": "Objekt",
        "bg": "Обект", "sv": "Objekt", "da": "Objekt", "nb": "Objekt", "fi": "Objekti",
        "id": "Objek", "ms": "Objek", "fil": "Object", "vi": "Đối tượng", "th": "ออบเจ็กต์",
        "tr": "Nesne", "hi": "ऑब्जेक्ट", "ar": "كائن", "he": "אובייקט", "bn": "অবজেক্ট",
        "fa": "شیء", "sw": "Kitu", "ca": "Objecte",
    },
    "Corner": {
        "fr": "Coin", "de": "Ecke", "es": "Esquina", "it": "Angolo", "pt": "Canto",
        "nl": "Hoek", "pl": "Narożnik", "ru": "Угол", "uk": "Куток", "cs": "Roh",
        "sk": "Roh", "ro": "Colț", "hu": "Sarok", "el": "Γωνία", "hr": "Kut",
        "bg": "Ъгъл", "sv": "Hörn", "da": "Hjørne", "nb": "Hjørne", "fi": "Kulma",
        "id": "Sudut", "ms": "Sudut", "fil": "Sulok", "vi": "Góc", "th": "มุม",
        "tr": "Köşe", "hi": "कोना", "ar": "زاوية", "he": "פינה", "bn": "কোণ",
        "fa": "گوشه", "sw": "Pembe", "ca": "Cantonada",
    },
    "Plaque": {
        "fr": "Plaque", "de": "Plakette", "es": "Placa", "it": "Targa", "pt": "Placa",
        "nl": "Plaquette", "pl": "Tabliczka", "ru": "Табличка", "uk": "Табличка", "cs": "Plaketa",
        "sk": "Plaketa", "ro": "Placă", "hu": "Tábla", "el": "Πλάκα", "hr": "Ploča",
        "bg": "Плоча", "sv": "Plakett", "da": "Plakette", "nb": "Plakett", "fi": "Kilpi",
        "id": "Plakat", "ms": "Plak", "fil": "Plake", "vi": "Tấm biển", "th": "แผ่นป้าย",
        "tr": "Plaka", "hi": "पट्टिका", "ar": "لوحة", "he": "לוחית", "bn": "ফলক",
        "fa": "لوح", "sw": "Bamba", "ca": "Placa",
    },
    "Tape": {
        "fr": "Bande", "de": "Band", "es": "Cinta", "it": "Nastro", "pt": "Fita",
        "nl": "Tape", "pl": "Taśma", "ru": "Лента", "uk": "Стрічка", "cs": "Páska",
        "sk": "Páska", "ro": "Bandă", "hu": "Szalag", "el": "Ταινία", "hr": "Traka",
        "bg": "Лента", "sv": "Band", "da": "Bånd", "nb": "Tape", "fi": "Nauha",
        "id": "Pita", "ms": "Pita", "fil": "Tape", "vi": "Băng", "th": "เทป",
        "tr": "Şerit", "hi": "टेप", "ar": "شريط", "he": "סרט", "bn": "টেপ",
        "fa": "نوار", "sw": "Tepe", "ca": "Cinta",
    },
    "Conversation": {
        "fr": "Conversation", "de": "Unterhaltung", "es": "Conversación", "it": "Conversazione", "pt": "Conversação",
        "nl": "Gesprek", "pl": "Rozmowa", "ru": "Разговор", "uk": "Розмова", "cs": "Konverzace",
        "sk": "Konverzácia", "ro": "Conversație", "hu": "Beszélgetés", "el": "Συνομιλία", "hr": "Razgovor",
        "bg": "Разговор", "sv": "Konversation", "da": "Samtale", "nb": "Samtale", "fi": "Keskustelu",
        "id": "Percakapan", "ms": "Perbualan", "fil": "Usapan", "vi": "Hội thoại", "th": "การสนทนา",
        "tr": "Konuşma", "hi": "वार्तालाप", "ar": "محادثة", "he": "שיחה", "bn": "কথোপকথন",
        "fa": "گفتگو", "sw": "Mazungumzo", "ca": "Conversa",
    },
    "Destruction": {
        "fr": "Destruction", "de": "Zerstörung", "es": "Destrucción", "it": "Distruzione", "pt": "Destruição",
        "nl": "Vernietiging", "pl": "Zniszczenie", "ru": "Уничтожение", "uk": "Знищення", "cs": "Zničení",
        "sk": "Zničenie", "ro": "Distrugere", "hu": "Megsemmisítés", "el": "Καταστροφή", "hr": "Uništenje",
        "bg": "Унищожаване", "sv": "Förstörelse", "da": "Ødelæggelse", "nb": "Destruksjon", "fi": "Tuhoaminen",
        "id": "Penghancuran", "ms": "Pemusnahan", "fil": "Pagsira", "vi": "Hủy", "th": "การทำลาย",
        "tr": "Yıkım", "hi": "विनाश", "ar": "تدمير", "he": "השמדה", "bn": "ধ্বংস",
        "fa": "تخریب", "sw": "Uharibifu", "ca": "Destrucció",
    },
    "Loop Limit": {
        "fr": "Limite de boucle", "de": "Schleifengrenze", "es": "Límite de bucle",
        "it": "Limite ciclo", "pt": "Limite de ciclo", "nl": "Luslimiet",
        "pl": "Limit pętli", "ru": "Предел цикла", "uk": "Межа циклу",
        "cs": "Limit smyčky", "sk": "Limit slučky", "ro": "Limită buclă",
        "hu": "Cikluskorlát", "el": "Όριο βρόχου", "hr": "Granica petlje",
        "bg": "Лимит на цикъл", "sv": "Loopgräns", "da": "Løkkegrænse",
        "nb": "Løkkegrense", "fi": "Silmukkaraja", "id": "Batas loop",
        "ms": "Had gelung", "fil": "Limit ng loop", "vi": "Giới hạn vòng",
        "th": "ขีดจำกัดลูป", "tr": "Döngü sınırı", "hi": "लूप सीमा",
        "ar": "حد الحلقة", "he": "מגבלת לולאה", "bn": "লুপ সীমা",
        "fa": "حد حلقه", "sw": "Kikomo cha kitanzi", "ca": "Límit de bucle",
    },
    "Loop Marker": {
        "fr": "Marqueur de boucle", "de": "Schleifenmarkierung", "es": "Marcador de bucle",
        "it": "Marcatore ciclo", "pt": "Marcador de ciclo", "nl": "Lusmarkering",
        "pl": "Znacznik pętli", "ru": "Маркер цикла", "uk": "Маркер циклу",
        "cs": "Značka smyčky", "sk": "Značka slučky", "ro": "Marcator buclă",
        "hu": "Ciklusjelölő", "el": "Δείκτης βρόχου", "hr": "Oznaka petlje",
        "bg": "Маркер на цикъл", "sv": "Loopmarkör", "da": "Løkkemarkør",
        "nb": "Løkkemarkør", "fi": "Silmukkimerkki", "id": "Penanda loop",
        "ms": "Penanda gelung", "fil": "Marker ng loop", "vi": "Đánh dấu vòng",
        "th": "ตัวทำเครื่องหมายลูป", "tr": "Döngü işaretçisi", "hi": "लूप मार्कर",
        "ar": "علامة الحلقة", "he": "סמן לולאה", "bn": "লুপ মার্কার",
        "fa": "نشانگر حلقه", "sw": "Alama ya kitanzi", "ca": "Marcador de bucle",
    },
    "Pointed Oval": {
        "fr": "Ovale pointu", "de": "Spitzes Oval", "es": "Óvalo puntiagudo",
        "it": "Ovale appuntito", "pt": "Oval pontiagudo", "nl": "Puntig ovaal",
        "pl": "Spiczasty owal", "ru": "Заострённый овал", "uk": "Загострений овал",
        "cs": "Špičatý ovál", "sk": "Špicatý ovál", "ro": "Oval ascuțit",
        "hu": "Csúcsos ovális", "el": "Μυτερή έλλειψη", "hr": "Šiljasti oval",
        "bg": "Заострен овал", "sv": "Spetsig oval", "da": "Spids oval",
        "nb": "Spiss oval", "fi": "Suippo soikio", "id": "Oval runcing",
        "ms": "Bujur meruncing", "fil": "Tulis na oval", "vi": "Oval nhọn",
        "th": "วงรีแหลม", "tr": "Sivri oval", "hi": "नुकीला अंडाकार",
        "ar": "بيضاوي مدبب", "he": "אליפסה מחודדת", "bn": "সুচালো ডিম্বাকার",
        "fa": "بیضی نوک‌تیز", "sw": "Duaraike yenye ncha", "ca": "Oval punxegut",
    },
    "Tee": {
        "fr": "Té", "de": "T-Stück", "es": "Te", "it": "T", "pt": "Tê",
        "nl": "T-stuk", "pl": "Trójnik", "ru": "Тройник", "uk": "Трійник", "cs": "T-kus",
        "sk": "T-kus", "ro": "Teu", "hu": "T-idom", "el": "Ταυ", "hr": "T-komad",
        "bg": "Тройник", "sv": "T-stycke", "da": "T-stykke", "nb": "T-stykke", "fi": "T-kappale",
        "id": "Tee", "ms": "Tee", "fil": "Tee", "vi": "Chữ T", "th": "ที",
        "tr": "T parçası", "hi": "टी", "ar": "تي", "he": "טי", "bn": "টি",
        "fa": "سهراهی", "sw": "Tee", "ca": "Te",
    },
    "Compensation": {
        "fr": "Compensation", "de": "Kompensation", "es": "Compensación", "it": "Compensazione", "pt": "Compensação",
        "nl": "Compensatie", "pl": "Kompensacja", "ru": "Компенсация", "uk": "Компенсація", "cs": "Kompenzace",
        "sk": "Kompenzácia", "ro": "Compensare", "hu": "Kompenzáció", "el": "Αποζημίωση", "hr": "Kompenzacija",
        "bg": "Компенсация", "sv": "Kompensation", "da": "Kompensation", "nb": "Kompensasjon", "fi": "Kompensaatio",
        "id": "Kompensasi", "ms": "Pampasan", "fil": "Compensation", "vi": "Bù trừ", "th": "การชดเชย",
        "tr": "Telafi", "hi": "मुआवज़ा", "ar": "تعويض", "he": "פיצוי", "bn": "ক্ষতিপূরণ",
        "fa": "جبران", "sw": "Fidia", "ca": "Compensació",
    },
    "Multiple Instances": {
        "fr": "Instances multiples", "de": "Mehrere Instanzen", "es": "Varias instancias",
        "it": "Istanze multiple", "pt": "Várias instâncias", "nl": "Meerdere instanties",
        "pl": "Wiele wystąpień", "ru": "Несколько экземпляров", "uk": "Кілька екземплярів",
        "cs": "Více instancí", "sk": "Viac inštancií", "ro": "Instanțe multiple",
        "hu": "Több példány", "el": "Πολλαπλά στιγμιότυπα", "hr": "Više primjeraka",
        "bg": "Множество екземпляри", "sv": "Flera instanser", "da": "Flere instanser",
        "nb": "Flere instanser", "fi": "Useita esiintymiä", "id": "Beberapa instans",
        "ms": "Berbilang tika", "fil": "Maraming instance", "vi": "Nhiều phiên bản",
        "th": "หลายอินสแตนซ์", "tr": "Birden fazla örnek", "hi": "एकाधिक इंस्टेंस",
        "ar": "مثيلات متعددة", "he": "מופעים מרובים", "bn": "একাধিক ইনস্ট্যান্স",
        "fa": "نمونه‌های چندگانه", "sw": "Matukio mengi", "ca": "Diverses instàncies",
    },
    "No Symbol": {
        "fr": "Pas de symbole", "de": "Kein Symbol", "es": "Sin símbolo",
        "it": "Nessun simbolo", "pt": "Sem símbolo", "nl": "Geen symbool",
        "pl": "Brak symbolu", "ru": "Без символа", "uk": "Без символу",
        "cs": "Bez symbolu", "sk": "Bez symbolu", "ro": "Fără simbol",
        "hu": "Nincs szimbólum", "el": "Χωρίς σύμβολο", "hr": "Bez simbola",
        "bg": "Без символ", "sv": "Ingen symbol", "da": "Intet symbol",
        "nb": "Ingen symbol", "fi": "Ei symbolia", "id": "Tanpa simbol",
        "ms": "Tiada simbol", "fil": "Walang simbolo", "vi": "Không ký hiệu",
        "th": "ไม่มีสัญลักษณ์", "tr": "Sembol yok", "hi": "कोई प्रतीक नहीं",
        "ar": "بدون رمز", "he": "ללא סמל", "bn": "কোনো প্রতীক নেই",
        "fa": "بدون نماد", "sw": "Hakuna ishara", "ca": "Sense símbol",
    },
    "Smiley": {
        "fr": "Smiley", "de": "Smiley", "es": "Smiley", "it": "Smiley", "pt": "Smiley",
        "nl": "Smiley", "pl": "Uśmiech", "ru": "Смайлик", "uk": "Смайлик", "cs": "Smajlík",
        "sk": "Smajlík", "ro": "Smiley", "hu": "Mosolygós", "el": "Φατσούλα", "hr": "Smajlić",
        "bg": "Усмивка", "sv": "Smiley", "da": "Smiley", "nb": "Smiley", "fi": "Hymiö",
        "id": "Smiley", "ms": "Senyuman", "fil": "Smiley", "vi": "Mặt cười", "th": "หน้ายิ้ม",
        "tr": "Gülen yüz", "hi": "स्माइली", "ar": "ابتسامة", "he": "סמיילי", "bn": "স্মাইলি",
        "fa": "صورتک", "sw": "Tabasamu", "ca": "Smiley",
    },
    "Neutral Smiley": {
        "fr": "Smiley neutre", "de": "Neutrales Smiley", "es": "Smiley neutro",
        "it": "Smiley neutro", "pt": "Smiley neutro", "nl": "Neutrale smiley",
        "pl": "Neutralny uśmiech", "ru": "Нейтральный смайлик", "uk": "Нейтральний смайлик",
        "cs": "Neutrální smajlík", "sk": "Neutrálny smajlík", "ro": "Smiley neutru",
        "hu": "Semleges mosoly", "el": "Ουδέτερη φατσούλα", "hr": "Neutralni smajlić",
        "bg": "Неутрална усмивка", "sv": "Neutral smiley", "da": "Neutral smiley",
        "nb": "Nøytral smiley", "fi": "Neutraali hymiö", "id": "Smiley netral",
        "ms": "Senyuman neutral", "fil": "Neutral na smiley", "vi": "Mặt trung tính",
        "th": "หน้าเรียบ", "tr": "Nötr gülen yüz", "hi": "तटस्थ स्माइली",
        "ar": "ابتسامة محايدة", "he": "סמיילי ניטרלי", "bn": "নিরপেক্ষ স্মাইলি",
        "fa": "صورتک خنثی", "sw": "Tabasamu la kati", "ca": "Smiley neutre",
    },
    "Sad Smiley": {
        "fr": "Smiley triste", "de": "Trauriges Smiley", "es": "Smiley triste",
        "it": "Smiley triste", "pt": "Smiley triste", "nl": "Verdrietige smiley",
        "pl": "Smutny uśmiech", "ru": "Грустный смайлик", "uk": "Сумний смайлик",
        "cs": "Smutný smajlík", "sk": "Smutný smajlík", "ro": "Smiley trist",
        "hu": "Szomorú mosoly", "el": "Λυπημένη φατσούλα", "hr": "Tužni smajlić",
        "bg": "Тъжна усмивка", "sv": "Ledsen smiley", "da": "Ked af det-smiley",
        "nb": "Trist smiley", "fi": "Surullinen hymiö", "id": "Smiley sedih",
        "ms": "Senyuman sedih", "fil": "Malungkot na smiley", "vi": "Mặt buồn",
        "th": "หน้าเศร้า", "tr": "Üzgün gülen yüz", "hi": "उदास स्माइली",
        "ar": "ابتسامة حزينة", "he": "סמיילי עצוב", "bn": "দুঃখিত স্মাইলি",
        "fa": "صورتک غمگین", "sw": "Tabasamu la huzuni", "ca": "Smiley trist",
    },
    "List Item": {
        "fr": "Élément de liste", "de": "Listenelement", "es": "Elemento de lista",
        "it": "Elemento elenco", "pt": "Item de lista", "nl": "Lijstitem",
        "pl": "Element listy", "ru": "Элемент списка", "uk": "Елемент списку",
        "cs": "Položka seznamu", "sk": "Položka zoznamu", "ro": "Element listă",
        "hu": "Listaelem", "el": "Στοιχείο λίστας", "hr": "Stavka popisa",
        "bg": "Елемент от списък", "sv": "Listobjekt", "da": "Listeelement",
        "nb": "Listeelement", "fi": "Luettelokohta", "id": "Item daftar",
        "ms": "Item senarai", "fil": "Item sa listahan", "vi": "Mục danh sách",
        "th": "รายการ", "tr": "Liste öğesi", "hi": "सूची आइटम",
        "ar": "عنصر قائمة", "he": "פריט רשימה", "bn": "তালিকা আইটেম",
        "fa": "مورد فهرست", "sw": "Kipengele cha orodha", "ca": "Element de llista",
    },
    "Unordered List": {
        "fr": "Liste non ordonnée", "de": "Ungeordnete Liste", "es": "Lista sin orden",
        "it": "Elenco non ordinato", "pt": "Lista não ordenada", "nl": "Ongeordende lijst",
        "pl": "Lista nieuporządkowana", "ru": "Маркированный список", "uk": "Маркований список",
        "cs": "Neuspořádaný seznam", "sk": "Neusporiadaný zoznam", "ro": "Listă neordonată",
        "hu": "Rendezetlen lista", "el": "Μη διατεταγμένη λίστα", "hr": "Neuređeni popis",
        "bg": "Неподреден списък", "sv": "Oordnad lista", "da": "Uordnet liste",
        "nb": "Uordnet liste", "fi": "Järjestämätön luettelo", "id": "Daftar tak berurut",
        "ms": "Senarai tidak tertib", "fil": "Walang ayos na listahan", "vi": "Danh sách không thứ tự",
        "th": "รายการไม่มีลำดับ", "tr": "Sırasız liste", "hi": "अक्रमित सूची",
        "ar": "قائمة غير مرتبة", "he": "רשימה לא מסודרת", "bn": "অবিন্যস্ত তালিকা",
        "fa": "فهرست بدون ترتیب", "sw": "Orodha isiyo na mpangilio", "ca": "Llista sense ordre",
    },
    "Zigzag": {
        "fr": "Zigzag", "de": "Zickzack", "es": "Zigzag", "it": "Zigzag", "pt": "Ziguezague",
        "nl": "Zigzag", "pl": "Zygzak", "ru": "Зигзаг", "uk": "Зигзаг", "cs": "Cikcak",
        "sk": "Cikcak", "ro": "Zigzag", "hu": "Cikkcakk", "el": "Ζιγκζαγκ", "hr": "Cikcak",
        "bg": "Зигзаг", "sv": "Sicksack", "da": "Zigzag", "nb": "Sikksakk", "fi": "Siksak",
        "id": "Zigzag", "ms": "Zigzag", "fil": "Zigzag", "vi": "Zigzag", "th": "ซิกแซก",
        "tr": "Zigzag", "hi": "जिगज़ैग", "ar": "متعرج", "he": "זיגזג", "bn": "জিগজ্যাগ",
        "fa": "زیگزاگ", "sw": "Zigzag", "ca": "Ziga-zaga",
    },
    "Ad Hoc": {
        # Keep English in many UIs; provide where natural
        "de": "Ad hoc", "fr": "Ad hoc", "es": "Ad hoc", "nl": "Ad hoc",
        "ru": "Специальный", "uk": "Спеціальний", "cs": "Ad hoc", "pl": "Ad hoc",
        "ja": "アドホック", "ko": "애드혹", "zh": "临时",
        "hi": "तदर्थ", "ar": "مخصص", "he": "אד הוק", "bn": "অ্যাড হক",
        "fa": "موردی", "vi": "Ad hoc", "th": "เฉพาะกิจ", "tr": "Ad hoc",
        "id": "Ad hoc", "sw": "Ad hoc", "fil": "Ad hoc",
    },
    "Label 1": {
        "fr": "Étiquette 1", "de": "Beschriftung 1", "es": "Etiqueta 1", "it": "Etichetta 1",
        "pt": "Etiqueta 1", "nl": "Label 1", "pl": "Etykieta 1", "ru": "Метка 1",
        "uk": "Мітка 1", "cs": "Popisek 1", "sk": "Popisok 1", "ro": "Etichetă 1",
        "hu": "Címke 1", "el": "Ετικέτα 1", "hr": "Oznaka 1", "bg": "Етикет 1",
        "sv": "Etikett 1", "da": "Etiket 1", "nb": "Etikett 1", "fi": "Nimike 1",
        "id": "Label 1", "ms": "Label 1", "fil": "Label 1", "vi": "Nhãn 1",
        "th": "ป้าย 1", "tr": "Etiket 1", "hi": "लेबल 1", "ar": "تسمية 1",
        "he": "תווית 1", "bn": "লেবেল ১", "fa": "برچسب ۱", "sw": "Lebo 1", "ca": "Etiqueta 1",
    },
    "Label 2": {
        "fr": "Étiquette 2", "de": "Beschriftung 2", "es": "Etiqueta 2", "it": "Etichetta 2",
        "pt": "Etiqueta 2", "nl": "Label 2", "pl": "Etykieta 2", "ru": "Метка 2",
        "uk": "Мітка 2", "cs": "Popisek 2", "sk": "Popisok 2", "ro": "Etichetă 2",
        "hu": "Címke 2", "el": "Ετικέτα 2", "hr": "Oznaka 2", "bg": "Етикет 2",
        "sv": "Etikett 2", "da": "Etiket 2", "nb": "Etikett 2", "fi": "Nimike 2",
        "id": "Label 2", "ms": "Label 2", "fil": "Label 2", "vi": "Nhãn 2",
        "th": "ป้าย 2", "tr": "Etiket 2", "hi": "लेबल 2", "ar": "تسمية 2",
        "he": "תווית 2", "bn": "লেবেল ২", "fa": "برچسب ۲", "sw": "Lebo 2", "ca": "Etiqueta 2",
    },
    "Diagonal Stripe": {
        "fr": "Bande diagonale", "de": "Diagonale Streifen", "es": "Franja diagonal",
        "it": "Striscia diagonale", "pt": "Faixa diagonal", "nl": "Diagonale streep",
        "pl": "Pasek ukośny", "ru": "Диагональная полоса", "uk": "Діагональна смуга",
        "cs": "Diagonální pruh", "sk": "Diagonálny pruh", "ro": "Bandă diagonală",
        "hu": "Átlós csík", "el": "Διαγώνια λωρίδα", "hr": "Dijagonalna pruga",
        "bg": "Диагонална ивица", "sv": "Diagonal rand", "da": "Diagonal stribe",
        "nb": "Diagonal stripe", "fi": "Viisto raita", "id": "Garis diagonal",
        "ms": "Jalur pepenjuru", "fil": "Diagonal na guhit", "vi": "Sọc chéo",
        "th": "แถบทแยง", "tr": "Çapraz şerit", "hi": "विकर्ण धारी",
        "ar": "شريط قطري", "he": "פס אלכסוני", "bn": "তির্যক ডোরা",
        "fa": "نوار مورب", "sw": "Mstari wa pembetatu", "ca": "Franja diagonal",
    },
    "Relationship": {
        "fr": "Relation", "de": "Beziehung", "es": "Relación", "it": "Relazione", "pt": "Relação",
        "nl": "Relatie", "pl": "Relacja", "ru": "Связь", "uk": "Зв’язок", "cs": "Vztah",
        "sk": "Vzťah", "ro": "Relație", "hu": "Kapcsolat", "el": "Σχέση", "hr": "Veza",
        "bg": "Връзка", "sv": "Relation", "da": "Relation", "nb": "Relasjon", "fi": "Suhde",
        "id": "Relasi", "ms": "Hubungan", "fil": "Relasyon", "vi": "Quan hệ", "th": "ความสัมพันธ์",
        "tr": "İlişki", "hi": "संबंध", "ar": "علاقة", "he": "קשר", "bn": "সম্পর্ক",
        "fa": "رابطه", "sw": "Uhusiano", "ca": "Relació",
    },
    "Identifying Relationship": {
        "fr": "Relation identifiante", "de": "Identifizierende Beziehung", "es": "Relación identificadora",
        "it": "Relazione identificativa", "pt": "Relação identificadora", "nl": "Identificerende relatie",
        "pl": "Relacja identyfikująca", "ru": "Идентифицирующая связь", "uk": "Ідентифікувальний зв’язок",
        "cs": "Identifikující vztah", "sk": "Identifikujúci vzťah", "ro": "Relație identificatoare",
        "hu": "Azonosító kapcsolat", "el": "Αναγνωριστική σχέση", "hr": "Identificirajuća veza",
        "bg": "Идентифицираща връзка", "sv": "Identifierande relation", "da": "Identificerende relation",
        "nb": "Identifiserende relasjon", "fi": "Tunnistava suhde", "id": "Relasi pengidentifikasi",
        "ms": "Hubungan pengenal", "fil": "Identifying na relasyon", "vi": "Quan hệ định danh",
        "th": "ความสัมพันธ์ระบุตัวตน", "tr": "Tanımlayıcı ilişki", "hi": "पहचान संबंध",
        "ar": "علاقة معرّفة", "he": "קשר מזהה", "bn": "শনাক্তকরণ সম্পর্ক",
        "fa": "رابطه شناسایی‌کننده", "sw": "Uhusiano wa kutambua", "ca": "Relació identificadora",
    },
}


def main() -> None:
    if not OUT_DIR.is_dir():
        raise SystemExit(f"missing {OUT_DIR}")
    totals: dict[str, int] = {}
    for path in sorted(OUT_DIR.glob("*.json")):
        lang = path.stem
        data = json.loads(path.read_text())
        n = 0
        for eng, by_lang in FILLS.items():
            if eng not in data:
                continue
            if data[eng] != eng:
                continue  # already localized
            loc = by_lang.get(lang)
            if not loc or loc == eng:
                continue
            data[eng] = loc
            n += 1
        if n:
            path.write_text(json.dumps(data, ensure_ascii=False, indent=0) + "\n")
            totals[lang] = n
            print(f"{lang}: filled {n}")
    print(f"done — updated {len(totals)} maps")


if __name__ == "__main__":
    main()
