#!/usr/bin/env python3
"""Fix German-polluted Nordic/Dutch banks and Spanish-polluted Catalan.

Rewrites UI strings for: da, nb, sv, fi, nl, ca.
Preserves stencil (st_*) entries. Updates editor_l10n_maps.dart and /tmp/all_banks.json.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPS = ROOT / "lib/l10n/editor_l10n_maps.dart"
BANKS_JSON = Path("/tmp/all_banks.json")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_editor_l10n import dart_map  # noqa: E402


def parse_const_map(text: str, name: str) -> dict[str, str]:
    m = re.search(
        rf"const Map<String, String> _{name} = <String, String>\{{(.*?)\n\}};",
        text,
        re.S,
    )
    if not m:
        raise SystemExit(f"cannot find _{name}")
    return {
        a.replace("\\'", "'"): b.replace("\\'", "'")
        for a, b in (
            match.groups()
            for match in re.finditer(
                r"'((?:\\'|[^'])*)':\s*'((?:\\'|[^'])*)'", m.group(1)
            )
        )
    }


def replace_const_map(text: str, name: str, data: dict[str, str]) -> str:
    new_block = dart_map(f"_{name}", data)
    pat = rf"const Map<String, String> _{name} = <String, String>\{{.*?\n\}};"
    out, n = re.subn(pat, new_block, text, count=1, flags=re.S)
    if n != 1:
        raise SystemExit(f"failed to replace _{name}")
    return out


def shortcuts(b: dict[str, str]) -> dict[str, str]:
    """Fill derived shortcut keys. Uses optional helper keys then strips them."""
    o = dict(b)
    rotate_right = o.pop("rotateRight90", None) or "Rotate 90° right"
    show_replace = o.pop("showReplace", None) or o.get("hideReplace", "Show replace").replace(
        "Hide", "Show"
    ).replace("Skjul", "Vis").replace("Dölj", "Visa").replace("Piilota", "Näytä").replace(
        "verbergen", "tonen"
    ).replace("Amaga", "Mostra").replace("Itago", "Ipakita")

    o["fitToWindowShortcut"] = f"{o['fitToWindow']} (⇧⌘H)"
    o["selectAllShortcut"] = f"{o['selectAll']} (Cmd+A)"
    o["findShortcut"] = f"{o['find']} (Cmd+F)"
    o["findReplaceShortcut"] = f"{o['findReplace']} (Cmd+H)"
    o["editDataShortcut"] = f"{o['editData']} (Cmd+M)"
    o["editLinkShortcut"] = f"{o['editLink']} (Cmd+K)"
    o["lockShortcut"] = f"{o['lock']} (Cmd+L)"
    o["unlockShortcut"] = f"{o['unlock']} (Cmd+L)"
    o["copyStyleShortcut"] = f"{o['copyStyle']} (Cmd+Alt+C)"
    o["pasteStyleShortcut"] = f"{o['pasteStyle']} (Cmd+Alt+V)"
    o["closeTabShortcut"] = f"{o['closeTab']} (Cmd+W)"
    o["bringForwardShortcut"] = f"{o['bringForward']} (Cmd+])"
    o["sendBackwardShortcut"] = f"{o['sendBackward']} (Cmd+[)"
    o["groupShortcut"] = f"{o['group']} (Cmd+G)"
    o["ungroupShortcut"] = f"{o['ungroup']} (Cmd+Shift+U)"
    o["rotateRight90Shortcut"] = f"{rotate_right} (Cmd+R)"
    o["previousShortcut"] = f"{o['previous']} (Shift+Enter)"
    o["nextShortcut"] = f"{o['next']} (Enter)"
    o["showReplaceShortcut"] = f"{show_replace} (Cmd+H)"
    o["closeEsc"] = f"{o['close']} (Esc)"
    return o


# --- Full UI banks (base keys; shortcuts filled by shortcuts()) ---

DA = {
    "cancel": "Annuller",
    "ok": "OK",
    "apply": "Anvend",
    "close": "Luk",
    "delete": "Slet",
    "rename": "Omdøb",
    "discard": "Kassér",
    "none": "Ingen",
    "enabled": "Aktiveret",
    "untitled": "Uden titel",
    "undo": "Fortryd",
    "redo": "Annuller fortryd",
    "outline": "Disposition",
    "rulers": "Linealer",
    "toggleGrid": "Vis/skjul gitter",
    "fitToWindow": "Tilpas til vindue",
    "layers": "Lag",
    "insertImage": "Indsæt billede…",
    "hideOutline": "Skjul disposition",
    "selectAll": "Markér alt",
    "find": "Find…",
    "findReplace": "Find og erstat…",
    "editData": "Rediger data…",
    "editLink": "Rediger link…",
    "editConnectionPoints": "Rediger forbindelsespunkter…",
    "doneEditingConnectionPoints": "Afslut redigering af forbindelsespunkter",
    "lock": "Lås",
    "unlock": "Lås op",
    "zoomToSelection": "Zoom til markering",
    "copyStyle": "Kopiér format",
    "pasteStyle": "Indsæt format",
    "saveAs": "Gem som…",
    "exportSvg": "Eksportér som SVG…",
    "exportPng": "Eksportér som PNG…",
    "exportPdf": "Eksportér som PDF…",
    "snapToGrid": "Fastgør til gitter",
    "lineJumps": "Linjespring",
    "closeTab": "Luk fane",
    "cut": "Klip",
    "copy": "Kopiér",
    "paste": "Indsæt",
    "pasteHere": "Indsæt her",
    "duplicate": "Dupliker",
    "clearWaypoints": "Ryd vejpunkter",
    "bringToFront": "Bring forrest",
    "sendToBack": "Send bagerst",
    "bringForward": "Bring frem",
    "sendBackward": "Send tilbage",
    "group": "Gruppér",
    "ungroup": "Ophæv gruppering",
    "editText": "Rediger tekst…",
    "replaceImage": "Erstat billede…",
    "addLane": "Tilføj bane",
    "removeLane": "Fjern bane",
    "addRow": "Tilføj række",
    "addColumn": "Tilføj kolonne",
    "deleteRow": "Slet række",
    "deleteColumn": "Slet kolonne",
    "mergeCells": "Flet celler",
    "unmergeCells": "Opdel celler",
    "clearGuides": "Ryd hjælpelinjer",
    "toolSelect": "Markér / flyt",
    "toolRectangle": "Rektangel",
    "toolEllipse": "Ellipse",
    "toolLine": "Linje",
    "toolConnector": "Forbindelse (lim)",
    "toolFreehand": "Frihånd",
    "toolText": "Tekst",
    "moreShapes": "Flere figurer",
    "searchShapes": "Søg figurer",
    "categoriesCount": "{n} kategorier",
    "expandAll": "Udvid alle",
    "collapseAll": "Skjul alle",
    "addPage": "Tilføj side",
    "duplicatePage": "Dupliker side",
    "deletePage": "Slet side",
    "renamePage": "Omdøb side",
    "pageNameHint": "Sidenavn",
    "pageReorderHint": "Træk for at omarrangere · Dobbeltklik for at omdøbe",
    "backgroundPageReorderHint": "Baggrundsside · Træk for at omarrangere · Dobbeltklik for at omdøbe",
    "pageOf": "Side {current} af {total}",
    "unsaved": "Ikke gemt",
    "noSelection": "Ingen markering",
    "selectedCount": "{n} markeret",
    "emptySubtitle": "Opret en ny tegning, eller træk & slip / åbn .vsdx-filer (hver åbnes i sin egen fane).",
    "newDrawing": "Ny tegning",
    "openVisioDrawing": "Åbn Visio-tegning",
    "orTrySample": "Eller prøv et eksempel:",
    "dropHint": "Slip Visio-fil eller billede",
    "discardUnsavedTitle": "Kassér ikke-gemte ændringer?",
    "discardUnsavedBody": "“{name}” har ikke-gemte ændringer.",
    "savedTo": "Gemt til {path}",
    "saveFailed": "Kunne ikke gemme: {error}",
    "exportedSvg": "SVG eksporteret til {path}",
    "exportedPng": "PNG eksporteret til {path}",
    "exportedPdf": "PDF eksporteret til {path}",
    "svgExportFailed": "SVG-eksport mislykkedes: {error}",
    "pngExportFailed": "PNG-eksport mislykkedes",
    "pngExportFailedError": "PNG-eksport mislykkedes: {error}",
    "pdfExportFailed": "PDF-eksport mislykkedes: {error}",
    "panelArrange": "Arranger",
    "panelAlign": "Juster",
    "panelAlignToPage": "Juster til side",
    "panelFill": "Fyld",
    "panelLine": "Linje",
    "panelConnector": "Forbindelse",
    "panelShadow": "Skygge",
    "panelGlow": "Glød",
    "panelReflection": "Spejling",
    "panelSoftEdges": "Bløde kanter",
    "panelText": "Tekst",
    "panelImage": "Billede",
    "panelData": "Data",
    "panelLink": "Link",
    "panelDiagram": "Diagram",
    "panelView": "Visning",
    "opacity": "Uigennemsigtighed",
    "size": "Størrelse",
    "color": "Farve",
    "rounded": "Afrundet",
    "gradient": "Farveforløb",
    "linear": "Lineær",
    "radial": "Radial",
    "start": "Start",
    "end": "Slut",
    "blur": "Sløring",
    "offsetX": "Forskydning X",
    "offsetY": "Forskydning Y",
    "dist": "Afstand",
    "solid": "Udfyldt",
    "dashed": "Stiplet",
    "dotted": "Prikket",
    "straight": "Lige",
    "orthogonal": "Ortogonal",
    "curved": "Buet",
    "bold": "Fed",
    "italic": "Kursiv",
    "underline": "Understreget",
    "lineSpacing": "Linjeafstand",
    "noShapeData": "Ingen figurdata",
    "noLink": "Intet link",
    "alignLeft": "Venstrejuster",
    "alignRight": "Højrejuster",
    "alignTop": "Juster øverst",
    "alignBottom": "Juster nederst",
    "alignCenterH": "Centrer vandret",
    "alignCenterV": "Centrer lodret",
    "alignLeftPage": "Venstrejuster til side",
    "alignRightPage": "Højrejuster til side",
    "alignTopPage": "Juster øverst til side",
    "alignBottomPage": "Juster nederst til side",
    "distributeH": "Fordel vandret",
    "distributeV": "Fordel lodret",
    "sameSize": "Samme størrelse",
    "sameWidth": "Samme bredde",
    "sameHeight": "Samme højde",
    "grid": "Gitter",
    "background": "Baggrund",
    "backgroundPage": "Baggrundsside",
    "theme": "Tema",
    "paperSize": "Papirstørrelse",
    "portrait": "Stående",
    "landscape": "Liggende",
    "noneDefault": "Ingen (standard)",
    "custom": "Brugerdefineret",
    "zoomIn": "Zoom ind",
    "zoomOut": "Zoom ud",
    "findShapesHint": "Find figurer…",
    "replaceWithHint": "Erstat med…",
    "replace": "Erstat",
    "replaceAll": "Alle",
    "previous": "Forrige",
    "next": "Næste",
    "renameLayer": "Omdøb lag",
    "name": "Navn",
    "value": "Værdi",
    "addProperty": "Tilføj egenskab",
    "remove": "Fjern",
    "noLayersYet": "Ingen lag endnu. Tilføj et for at organisere figurer (synlig / låst / udskriv).",
    "visible": "Synlig",
    "locked": "Låst",
    "print": "Udskriv",
    "assignSelection": "Tildel mark.",
    "deleteLayer": "Slet lag",
    "addLayer": "Tilføj lag",
    "addLayerWithSelection": "Tilføj lag (med markering)",
    "labelOptional": "Etiket (valgfri)",
    "removeLink": "Fjern link",
    "link": "Link",
    "noShapeDataHint": "Ingen figurdata. Tilføj en egenskab for at komme i gang.",
    "linkHint": "https://example.com  eller  #Page-2",
    "sg_General": "Generelt",
    "sg_Flowchart": "Flowdiagram",
    "sg_Arrows": "Pile",
    "sg_Basic": "Grundlæggende",
    "sg_Containers": "Beholdere",
    "sg_UML": "UML",
    "sg_ER": "ER",
    "sg_BPMN": "BPMN",
    "sg_Misc": "Diverse",
    "sg_Advanced": "Avanceret",
    "flipHorizontal": "Vend vandret",
    "flipVertical": "Vend lodret",
    "rotateLeft90": "Roter 90° til venstre",
    "rotateRight90": "Roter 90° til højre",
    "centerHorizontally": "Centrer vandret",
    "centerHorizontallyPage": "Centrer vandret på siden",
    "centerVertically": "Centrer lodret",
    "centerVerticallyPage": "Centrer lodret på siden",
    "justify": "Lige margener",
    "spaceBefore": "Afstand før",
    "spaceAfter": "Afstand efter",
    "dropToOpen": "Slip for at åbne",
    "openFileFailed": "Kunne ikke åbne filen: {error}",
    "openPathFailed": "Kunne ikke åbne {path}",
    "openExampleFailed": "Kunne ikke åbne eksemplet {name}",
    "insertImageFailed": "Kunne ikke indsætte billede",
    "replacedWith": "Erstattet med {name}",
    "insertedNamed": "Indsat {name}",
    "strikethrough": "Gennemstreget",
    "dashDot": "Streg-prik",
    "compoundSingle": "Enkel",
    "compoundDouble": "Dobbelt",
    "compoundThickThin": "Tyk-tynd",
    "compoundThinThick": "Tynd-tyk",
    "arrowFilled": "Udfyldt",
    "arrowOpen": "Åben",
    "arrowThin": "Tynd",
    "arrowStealth": "Stealth",
    "arrowCircle": "Cirkel",
    "arrowOpenDiamond": "Åben diamant",
    "arrowCircleOpen": "Cirkel (åben)",
    "arrowNumbered": "Pil #{id}",
    "defaultFont": "Standard",
    "noResults": "Ingen resultater",
    "matchCaseOn": "Forskel på store/små: til",
    "matchCaseOff": "Forskel på store/små: fra",
    "wholeWordOn": "Hele ord: til",
    "wholeWordOff": "Hele ord: fra",
    "hideReplace": "Skjul erstat",
    "showReplace": "Vis erstat",
    "backgroundPageHint": "Brug som underlag for andre sider",
    "useBackground": "Brug baggrund",
    "willMarkBackground": "{name} (markeres som bg)",
    "corners": "Hjørner",
    "jumpRadius": "Springradius",
    "patternBrick": "Mursten",
    "patternShingle": "Tagsten",
}

NB = {
    "cancel": "Avbryt",
    "ok": "OK",
    "apply": "Bruk",
    "close": "Lukk",
    "delete": "Slett",
    "rename": "Gi nytt navn",
    "discard": "Forkast",
    "none": "Ingen",
    "enabled": "Aktivert",
    "untitled": "Uten tittel",
    "undo": "Angre",
    "redo": "Gjør om",
    "outline": "Disposisjon",
    "rulers": "Linjaler",
    "toggleGrid": "Vis/skjul rutenett",
    "fitToWindow": "Tilpass til vindu",
    "layers": "Lag",
    "insertImage": "Sett inn bilde…",
    "hideOutline": "Skjul disposisjon",
    "selectAll": "Merk alt",
    "find": "Finn…",
    "findReplace": "Finn og erstatt…",
    "editData": "Rediger data…",
    "editLink": "Rediger kobling…",
    "editConnectionPoints": "Rediger tilkoblingspunkter…",
    "doneEditingConnectionPoints": "Fullfør redigering av tilkoblingspunkter",
    "lock": "Lås",
    "unlock": "Lås opp",
    "zoomToSelection": "Zoom til utvalg",
    "copyStyle": "Kopier format",
    "pasteStyle": "Lim inn format",
    "saveAs": "Lagre som…",
    "exportSvg": "Eksporter som SVG…",
    "exportPng": "Eksporter som PNG…",
    "exportPdf": "Eksporter som PDF…",
    "snapToGrid": "Fest til rutenett",
    "lineJumps": "Linjehopp",
    "closeTab": "Lukk fane",
    "cut": "Klipp ut",
    "copy": "Kopier",
    "paste": "Lim inn",
    "pasteHere": "Lim inn her",
    "duplicate": "Dupliser",
    "clearWaypoints": "Fjern veipunkter",
    "bringToFront": "Plasser forrest",
    "sendToBack": "Plasser bakerst",
    "bringForward": "Flytt fremover",
    "sendBackward": "Flytt bakover",
    "group": "Grupper",
    "ungroup": "Opphev gruppering",
    "editText": "Rediger tekst…",
    "replaceImage": "Erstatt bilde…",
    "addLane": "Legg til bane",
    "removeLane": "Fjern bane",
    "addRow": "Legg til rad",
    "addColumn": "Legg til kolonne",
    "deleteRow": "Slett rad",
    "deleteColumn": "Slett kolonne",
    "mergeCells": "Slå sammen celler",
    "unmergeCells": "Del celler",
    "clearGuides": "Fjern hjelpelinjer",
    "toolSelect": "Merk / flytt",
    "toolRectangle": "Rektangel",
    "toolEllipse": "Ellipse",
    "toolLine": "Linje",
    "toolConnector": "Kobling (lim)",
    "toolFreehand": "Frihånd",
    "toolText": "Tekst",
    "moreShapes": "Flere figurer",
    "searchShapes": "Søk i figurer",
    "categoriesCount": "{n} kategorier",
    "expandAll": "Utvid alle",
    "collapseAll": "Skjul alle",
    "addPage": "Legg til side",
    "duplicatePage": "Dupliser side",
    "deletePage": "Slett side",
    "renamePage": "Gi siden nytt navn",
    "pageNameHint": "Sidenavn",
    "pageReorderHint": "Dra for å omordne · Dobbeltklikk for å gi nytt navn",
    "backgroundPageReorderHint": "Bakgrunnsside · Dra for å omordne · Dobbeltklikk for å gi nytt navn",
    "pageOf": "Side {current} av {total}",
    "unsaved": "Ikke lagret",
    "noSelection": "Ingen markering",
    "selectedCount": "{n} merket",
    "emptySubtitle": "Opprett en ny tegning, eller dra og slipp / åpne .vsdx-filer (hver åpnes i egen fane).",
    "newDrawing": "Ny tegning",
    "openVisioDrawing": "Åpne Visio-tegning",
    "orTrySample": "Eller prøv et eksempel:",
    "dropHint": "Slipp Visio-fil eller bilde",
    "discardUnsavedTitle": "Forkaste ulagrede endringer?",
    "discardUnsavedBody": "“{name}” har ulagrede endringer.",
    "savedTo": "Lagret til {path}",
    "saveFailed": "Kunne ikke lagre: {error}",
    "exportedSvg": "SVG eksportert til {path}",
    "exportedPng": "PNG eksportert til {path}",
    "exportedPdf": "PDF eksportert til {path}",
    "svgExportFailed": "SVG-eksport mislyktes: {error}",
    "pngExportFailed": "PNG-eksport mislyktes",
    "pngExportFailedError": "PNG-eksport mislyktes: {error}",
    "pdfExportFailed": "PDF-eksport mislyktes: {error}",
    "panelArrange": "Ordne",
    "panelAlign": "Juster",
    "panelAlignToPage": "Juster til side",
    "panelFill": "Fyll",
    "panelLine": "Linje",
    "panelConnector": "Kobling",
    "panelShadow": "Skygge",
    "panelGlow": "Glød",
    "panelReflection": "Refleksjon",
    "panelSoftEdges": "Myke kanter",
    "panelText": "Tekst",
    "panelImage": "Bilde",
    "panelData": "Data",
    "panelLink": "Kobling",
    "panelDiagram": "Diagram",
    "panelView": "Visning",
    "opacity": "Ugjennomsiktighet",
    "size": "Størrelse",
    "color": "Farge",
    "rounded": "Avrundet",
    "gradient": "Gradient",
    "linear": "Lineær",
    "radial": "Radiell",
    "start": "Start",
    "end": "Slutt",
    "blur": "Uskarphet",
    "offsetX": "Forskyvning X",
    "offsetY": "Forskyvning Y",
    "dist": "Avstand",
    "solid": "Heltrukket",
    "dashed": "Stiplet",
    "dotted": "Prikket",
    "straight": "Rett",
    "orthogonal": "Ortogonal",
    "curved": "Buet",
    "bold": "Fet",
    "italic": "Kursiv",
    "underline": "Understreking",
    "lineSpacing": "Linjeavstand",
    "noShapeData": "Ingen figurdata",
    "noLink": "Ingen kobling",
    "alignLeft": "Venstrejuster",
    "alignRight": "Høyrejuster",
    "alignTop": "Juster øverst",
    "alignBottom": "Juster nederst",
    "alignCenterH": "Sentrer vannrett",
    "alignCenterV": "Sentrer loddrett",
    "alignLeftPage": "Venstrejuster til side",
    "alignRightPage": "Høyrejuster til side",
    "alignTopPage": "Juster øverst til side",
    "alignBottomPage": "Juster nederst til side",
    "distributeH": "Fordel vannrett",
    "distributeV": "Fordel loddrett",
    "sameSize": "Samme størrelse",
    "sameWidth": "Samme bredde",
    "sameHeight": "Samme høyde",
    "grid": "Rutenett",
    "background": "Bakgrunn",
    "backgroundPage": "Bakgrunnsside",
    "theme": "Tema",
    "paperSize": "Papirstørrelse",
    "portrait": "Stående",
    "landscape": "Liggende",
    "noneDefault": "Ingen (standard)",
    "custom": "Egendefinert",
    "zoomIn": "Zoom inn",
    "zoomOut": "Zoom ut",
    "findShapesHint": "Finn figurer…",
    "replaceWithHint": "Erstatt med…",
    "replace": "Erstatt",
    "replaceAll": "Alle",
    "previous": "Forrige",
    "next": "Neste",
    "renameLayer": "Gi laget nytt navn",
    "name": "Navn",
    "value": "Verdi",
    "addProperty": "Legg til egenskap",
    "remove": "Fjern",
    "noLayersYet": "Ingen lag ennå. Legg til ett for å organisere figurer (synlig / låst / skriv ut).",
    "visible": "Synlig",
    "locked": "Låst",
    "print": "Skriv ut",
    "assignSelection": "Tilordne utv.",
    "deleteLayer": "Slett lag",
    "addLayer": "Legg til lag",
    "addLayerWithSelection": "Legg til lag (med utvalg)",
    "labelOptional": "Etikett (valgfritt)",
    "removeLink": "Fjern kobling",
    "link": "Kobling",
    "noShapeDataHint": "Ingen figurdata. Legg til en egenskap for å komme i gang.",
    "linkHint": "https://example.com  eller  #Page-2",
    "sg_General": "Generelt",
    "sg_Flowchart": "Flytskjema",
    "sg_Arrows": "Piler",
    "sg_Basic": "Grunnleggende",
    "sg_Containers": "Beholdere",
    "sg_UML": "UML",
    "sg_ER": "ER",
    "sg_BPMN": "BPMN",
    "sg_Misc": "Diverse",
    "sg_Advanced": "Avansert",
    "flipHorizontal": "Vend vannrett",
    "flipVertical": "Vend loddrett",
    "rotateLeft90": "Roter 90° til venstre",
    "rotateRight90": "Roter 90° til høyre",
    "centerHorizontally": "Sentrer vannrett",
    "centerHorizontallyPage": "Sentrer vannrett på siden",
    "centerVertically": "Sentrer loddrett",
    "centerVerticallyPage": "Sentrer loddrett på siden",
    "justify": "Blokkjuster",
    "spaceBefore": "Avstand før",
    "spaceAfter": "Avstand etter",
    "dropToOpen": "Slipp for å åpne",
    "openFileFailed": "Kunne ikke åpne filen: {error}",
    "openPathFailed": "Kunne ikke åpne {path}",
    "openExampleFailed": "Kunne ikke åpne eksempelet {name}",
    "insertImageFailed": "Kunne ikke sette inn bilde",
    "replacedWith": "Erstattet med {name}",
    "insertedNamed": "Satt inn {name}",
    "strikethrough": "Gjennomstreking",
    "dashDot": "Strek-prikk",
    "compoundSingle": "Enkel",
    "compoundDouble": "Dobbel",
    "compoundThickThin": "Tykk-tynn",
    "compoundThinThick": "Tynn-tykk",
    "arrowFilled": "Fylt",
    "arrowOpen": "Åpen",
    "arrowThin": "Tynn",
    "arrowStealth": "Stealth",
    "arrowCircle": "Sirkel",
    "arrowOpenDiamond": "Åpen diamant",
    "arrowCircleOpen": "Sirkel (åpen)",
    "arrowNumbered": "Pil #{id}",
    "defaultFont": "Standard",
    "noResults": "Ingen resultater",
    "matchCaseOn": "Skill mellom store/små: på",
    "matchCaseOff": "Skill mellom store/små: av",
    "wholeWordOn": "Hele ord: på",
    "wholeWordOff": "Hele ord: av",
    "hideReplace": "Skjul erstatt",
    "showReplace": "Vis erstatt",
    "backgroundPageHint": "Bruk som underlag for andre sider",
    "useBackground": "Bruk bakgrunn",
    "willMarkBackground": "{name} (merkes som bg)",
    "corners": "Hjørner",
    "jumpRadius": "Hoppradius",
    "patternBrick": "Murstein",
    "patternShingle": "Taktegl",
}

SV = {
    "cancel": "Avbryt",
    "ok": "OK",
    "apply": "Använd",
    "close": "Stäng",
    "delete": "Ta bort",
    "rename": "Byt namn",
    "discard": "Kassera",
    "none": "Ingen",
    "enabled": "Aktiverad",
    "untitled": "Namnlös",
    "undo": "Ångra",
    "redo": "Gör om",
    "outline": "Disposition",
    "rulers": "Linjaler",
    "toggleGrid": "Visa/dölj rutnät",
    "fitToWindow": "Anpassa till fönster",
    "layers": "Lager",
    "insertImage": "Infoga bild…",
    "hideOutline": "Dölj disposition",
    "selectAll": "Markera allt",
    "find": "Sök…",
    "findReplace": "Sök och ersätt…",
    "editData": "Redigera data…",
    "editLink": "Redigera länk…",
    "editConnectionPoints": "Redigera anslutningspunkter…",
    "doneEditingConnectionPoints": "Slutför redigering av anslutningspunkter",
    "lock": "Lås",
    "unlock": "Lås upp",
    "zoomToSelection": "Zooma till markering",
    "copyStyle": "Kopiera format",
    "pasteStyle": "Klistra in format",
    "saveAs": "Spara som…",
    "exportSvg": "Exportera som SVG…",
    "exportPng": "Exportera som PNG…",
    "exportPdf": "Exportera som PDF…",
    "snapToGrid": "Fäst mot rutnät",
    "lineJumps": "Linjehopp",
    "closeTab": "Stäng flik",
    "cut": "Klipp ut",
    "copy": "Kopiera",
    "paste": "Klistra in",
    "pasteHere": "Klistra in här",
    "duplicate": "Duplicera",
    "clearWaypoints": "Rensa vägpunkter",
    "bringToFront": "Placera längst fram",
    "sendToBack": "Placera längst bak",
    "bringForward": "Flytta framåt",
    "sendBackward": "Flytta bakåt",
    "group": "Gruppera",
    "ungroup": "Dela upp grupp",
    "editText": "Redigera text…",
    "replaceImage": "Ersätt bild…",
    "addLane": "Lägg till bana",
    "removeLane": "Ta bort bana",
    "addRow": "Lägg till rad",
    "addColumn": "Lägg till kolumn",
    "deleteRow": "Ta bort rad",
    "deleteColumn": "Ta bort kolumn",
    "mergeCells": "Sammanfoga celler",
    "unmergeCells": "Dela celler",
    "clearGuides": "Rensa hjälplinjer",
    "toolSelect": "Markera / flytta",
    "toolRectangle": "Rektangel",
    "toolEllipse": "Ellips",
    "toolLine": "Linje",
    "toolConnector": "Koppling (lim)",
    "toolFreehand": "Frihand",
    "toolText": "Text",
    "moreShapes": "Fler former",
    "searchShapes": "Sök former",
    "categoriesCount": "{n} kategorier",
    "expandAll": "Expandera alla",
    "collapseAll": "Komprimera alla",
    "addPage": "Lägg till sida",
    "duplicatePage": "Duplicera sida",
    "deletePage": "Ta bort sida",
    "renamePage": "Byt namn på sida",
    "pageNameHint": "Sidnamn",
    "pageReorderHint": "Dra för att ändra ordning · Dubbelklicka för att byta namn",
    "backgroundPageReorderHint": "Bakgrundssida · Dra för att ändra ordning · Dubbelklicka för att byta namn",
    "pageOf": "Sida {current} av {total}",
    "unsaved": "Osparat",
    "noSelection": "Ingen markering",
    "selectedCount": "{n} markerade",
    "emptySubtitle": "Skapa en ny ritning, eller dra och släpp / öppna .vsdx-filer (varje öppnas i egen flik).",
    "newDrawing": "Ny ritning",
    "openVisioDrawing": "Öppna Visio-ritning",
    "orTrySample": "Eller prova ett exempel:",
    "dropHint": "Släpp Visio-fil eller bild",
    "discardUnsavedTitle": "Kassera osparade ändringar?",
    "discardUnsavedBody": "“{name}” har osparade ändringar.",
    "savedTo": "Sparad till {path}",
    "saveFailed": "Kunde inte spara: {error}",
    "exportedSvg": "SVG exporterad till {path}",
    "exportedPng": "PNG exporterad till {path}",
    "exportedPdf": "PDF exporterad till {path}",
    "svgExportFailed": "SVG-export misslyckades: {error}",
    "pngExportFailed": "PNG-export misslyckades",
    "pngExportFailedError": "PNG-export misslyckades: {error}",
    "pdfExportFailed": "PDF-export misslyckades: {error}",
    "panelArrange": "Ordna",
    "panelAlign": "Justera",
    "panelAlignToPage": "Justera mot sida",
    "panelFill": "Fyllning",
    "panelLine": "Linje",
    "panelConnector": "Koppling",
    "panelShadow": "Skugga",
    "panelGlow": "Glöd",
    "panelReflection": "Spegling",
    "panelSoftEdges": "Mjuka kanter",
    "panelText": "Text",
    "panelImage": "Bild",
    "panelData": "Data",
    "panelLink": "Länk",
    "panelDiagram": "Diagram",
    "panelView": "Vy",
    "opacity": "Opacitet",
    "size": "Storlek",
    "color": "Färg",
    "rounded": "Rundad",
    "gradient": "Övertoning",
    "linear": "Linjär",
    "radial": "Radiell",
    "start": "Start",
    "end": "Slut",
    "blur": "Oskärpa",
    "offsetX": "Förskjutning X",
    "offsetY": "Förskjutning Y",
    "dist": "Avstånd",
    "solid": "Heldragen",
    "dashed": "Streckad",
    "dotted": "Prickad",
    "straight": "Rak",
    "orthogonal": "Ortogonal",
    "curved": "Böjd",
    "bold": "Fet",
    "italic": "Kursiv",
    "underline": "Understruken",
    "lineSpacing": "Radavstånd",
    "noShapeData": "Inga formdata",
    "noLink": "Ingen länk",
    "alignLeft": "Vänsterjustera",
    "alignRight": "Högerjustera",
    "alignTop": "Justera upptill",
    "alignBottom": "Justera nedtill",
    "alignCenterH": "Centrera vågrätt",
    "alignCenterV": "Centrera lodrätt",
    "alignLeftPage": "Vänsterjustera mot sida",
    "alignRightPage": "Högerjustera mot sida",
    "alignTopPage": "Justera upptill mot sida",
    "alignBottomPage": "Justera nedtill mot sida",
    "distributeH": "Fördela vågrätt",
    "distributeV": "Fördela lodrätt",
    "sameSize": "Samma storlek",
    "sameWidth": "Samma bredd",
    "sameHeight": "Samma höjd",
    "grid": "Rutnät",
    "background": "Bakgrund",
    "backgroundPage": "Bakgrundssida",
    "theme": "Tema",
    "paperSize": "Pappersstorlek",
    "portrait": "Stående",
    "landscape": "Liggande",
    "noneDefault": "Ingen (standard)",
    "custom": "Anpassad",
    "zoomIn": "Zooma in",
    "zoomOut": "Zooma ut",
    "findShapesHint": "Sök former…",
    "replaceWithHint": "Ersätt med…",
    "replace": "Ersätt",
    "replaceAll": "Alla",
    "previous": "Föregående",
    "next": "Nästa",
    "renameLayer": "Byt namn på lager",
    "name": "Namn",
    "value": "Värde",
    "addProperty": "Lägg till egenskap",
    "remove": "Ta bort",
    "noLayersYet": "Inga lager ännu. Lägg till ett för att organisera former (synlig / låst / skriv ut).",
    "visible": "Synlig",
    "locked": "Låst",
    "print": "Skriv ut",
    "assignSelection": "Tilldela mark.",
    "deleteLayer": "Ta bort lager",
    "addLayer": "Lägg till lager",
    "addLayerWithSelection": "Lägg till lager (med markering)",
    "labelOptional": "Etikett (valfritt)",
    "removeLink": "Ta bort länk",
    "link": "Länk",
    "noShapeDataHint": "Inga formdata. Lägg till en egenskap för att komma igång.",
    "linkHint": "https://example.com  eller  #Page-2",
    "sg_General": "Allmänt",
    "sg_Flowchart": "Flödesschema",
    "sg_Arrows": "Pilar",
    "sg_Basic": "Grundläggande",
    "sg_Containers": "Behållare",
    "sg_UML": "UML",
    "sg_ER": "ER",
    "sg_BPMN": "BPMN",
    "sg_Misc": "Diverse",
    "sg_Advanced": "Avancerat",
    "flipHorizontal": "Vänd vågrätt",
    "flipVertical": "Vänd lodrätt",
    "rotateLeft90": "Rotera 90° åt vänster",
    "rotateRight90": "Rotera 90° åt höger",
    "centerHorizontally": "Centrera vågrätt",
    "centerHorizontallyPage": "Centrera vågrätt på sidan",
    "centerVertically": "Centrera lodrätt",
    "centerVerticallyPage": "Centrera lodrätt på sidan",
    "justify": "Justera båda sidor",
    "spaceBefore": "Avstånd före",
    "spaceAfter": "Avstånd efter",
    "dropToOpen": "Släpp för att öppna",
    "openFileFailed": "Kunde inte öppna filen: {error}",
    "openPathFailed": "Kunde inte öppna {path}",
    "openExampleFailed": "Kunde inte öppna exemplet {name}",
    "insertImageFailed": "Kunde inte infoga bild",
    "replacedWith": "Ersattes med {name}",
    "insertedNamed": "Infogade {name}",
    "strikethrough": "Genomstruken",
    "dashDot": "Streck-punkt",
    "compoundSingle": "Enkel",
    "compoundDouble": "Dubbel",
    "compoundThickThin": "Tjock-tunn",
    "compoundThinThick": "Tunn-tjock",
    "arrowFilled": "Fylld",
    "arrowOpen": "Öppen",
    "arrowThin": "Tunn",
    "arrowStealth": "Stealth",
    "arrowCircle": "Cirkel",
    "arrowOpenDiamond": "Öppen diamant",
    "arrowCircleOpen": "Cirkel (öppen)",
    "arrowNumbered": "Pil #{id}",
    "defaultFont": "Standard",
    "noResults": "Inga resultat",
    "matchCaseOn": "Matcha versaler: på",
    "matchCaseOff": "Matcha versaler: av",
    "wholeWordOn": "Hela ord: på",
    "wholeWordOff": "Hela ord: av",
    "hideReplace": "Dölj ersätt",
    "showReplace": "Visa ersätt",
    "backgroundPageHint": "Använd som underlag för andra sidor",
    "useBackground": "Använd bakgrund",
    "willMarkBackground": "{name} (markeras som bg)",
    "corners": "Hörn",
    "jumpRadius": "Hoppradie",
    "patternBrick": "Tegel",
    "patternShingle": "Takspån",
}

FI = {
    "cancel": "Peruuta",
    "ok": "OK",
    "apply": "Käytä",
    "close": "Sulje",
    "delete": "Poista",
    "rename": "Nimeä uudelleen",
    "discard": "Hylkää",
    "none": "Ei mitään",
    "enabled": "Käytössä",
    "untitled": "Nimetön",
    "undo": "Kumoa",
    "redo": "Tee uudelleen",
    "outline": "Jäsennys",
    "rulers": "Viivaimet",
    "toggleGrid": "Näytä/piilota ruudukko",
    "fitToWindow": "Sovita ikkunaan",
    "layers": "Tasot",
    "insertImage": "Lisää kuva…",
    "hideOutline": "Piilota jäsennys",
    "selectAll": "Valitse kaikki",
    "find": "Etsi…",
    "findReplace": "Etsi ja korvaa…",
    "editData": "Muokkaa tietoja…",
    "editLink": "Muokkaa linkkiä…",
    "editConnectionPoints": "Muokkaa liitoskohtia…",
    "doneEditingConnectionPoints": "Lopeta liitoskohtien muokkaus",
    "lock": "Lukitse",
    "unlock": "Poista lukitus",
    "zoomToSelection": "Zoomaa valintaan",
    "copyStyle": "Kopioi tyyli",
    "pasteStyle": "Liitä tyyli",
    "saveAs": "Tallenna nimellä…",
    "exportSvg": "Vie SVG-muodossa…",
    "exportPng": "Vie PNG-muodossa…",
    "exportPdf": "Vie PDF-muodossa…",
    "snapToGrid": "Kohdista ruudukkoon",
    "lineJumps": "Viivahypyt",
    "closeTab": "Sulje välilehti",
    "cut": "Leikkaa",
    "copy": "Kopioi",
    "paste": "Liitä",
    "pasteHere": "Liitä tähän",
    "duplicate": "Monista",
    "clearWaypoints": "Tyhjennä reittipisteet",
    "bringToFront": "Tuo eteen",
    "sendToBack": "Vie taakse",
    "bringForward": "Tuo eteenpäin",
    "sendBackward": "Vie taaksepäin",
    "group": "Ryhmitä",
    "ungroup": "Pura ryhmitys",
    "editText": "Muokkaa tekstiä…",
    "replaceImage": "Korvaa kuva…",
    "addLane": "Lisää kaista",
    "removeLane": "Poista kaista",
    "addRow": "Lisää rivi",
    "addColumn": "Lisää sarake",
    "deleteRow": "Poista rivi",
    "deleteColumn": "Poista sarake",
    "mergeCells": "Yhdistä solut",
    "unmergeCells": "Pura solujen yhdistäminen",
    "clearGuides": "Tyhjennä apuviivat",
    "toolSelect": "Valitse / siirrä",
    "toolRectangle": "Suorakulmio",
    "toolEllipse": "Ellipsi",
    "toolLine": "Viiva",
    "toolConnector": "Yhdistäjä (liima)",
    "toolFreehand": "Vapaa käsi",
    "toolText": "Teksti",
    "moreShapes": "Lisää muotoja",
    "searchShapes": "Hae muotoja",
    "categoriesCount": "{n} luokkaa",
    "expandAll": "Laajenna kaikki",
    "collapseAll": "Tiivistä kaikki",
    "addPage": "Lisää sivu",
    "duplicatePage": "Monista sivu",
    "deletePage": "Poista sivu",
    "renamePage": "Nimeä sivu uudelleen",
    "pageNameHint": "Sivun nimi",
    "pageReorderHint": "Vedä järjestääksesi · Kaksoisnapsauta nimetäksesi",
    "backgroundPageReorderHint": "Taustasivu · Vedä järjestääksesi · Kaksoisnapsauta nimetäksesi",
    "pageOf": "Sivu {current} / {total}",
    "unsaved": "Tallentamaton",
    "noSelection": "Ei valintaa",
    "selectedCount": "{n} valittu",
    "emptySubtitle": "Luo uusi piirustus tai vedä & pudota / avaa .vsdx-tiedostoja (kukin omaan välilehteensä).",
    "newDrawing": "Uusi piirustus",
    "openVisioDrawing": "Avaa Visio-piirustus",
    "orTrySample": "Tai kokeile esimerkkiä:",
    "dropHint": "Pudota Visio-tiedosto tai kuva",
    "discardUnsavedTitle": "Hylätäänkö tallentamattomat muutokset?",
    "discardUnsavedBody": "“{name}” sisältää tallentamattomia muutoksia.",
    "savedTo": "Tallennettu polkuun {path}",
    "saveFailed": "Tallennus epäonnistui: {error}",
    "exportedSvg": "SVG viety polkuun {path}",
    "exportedPng": "PNG viety polkuun {path}",
    "exportedPdf": "PDF viety polkuun {path}",
    "svgExportFailed": "SVG-vienti epäonnistui: {error}",
    "pngExportFailed": "PNG-vienti epäonnistui",
    "pngExportFailedError": "PNG-vienti epäonnistui: {error}",
    "pdfExportFailed": "PDF-vienti epäonnistui: {error}",
    "panelArrange": "Järjestä",
    "panelAlign": "Tasaa",
    "panelAlignToPage": "Tasaa sivulle",
    "panelFill": "Täyttö",
    "panelLine": "Viiva",
    "panelConnector": "Yhdistäjä",
    "panelShadow": "Varjo",
    "panelGlow": "Hehku",
    "panelReflection": "Heijastus",
    "panelSoftEdges": "Pehmeät reunat",
    "panelText": "Teksti",
    "panelImage": "Kuva",
    "panelData": "Tiedot",
    "panelLink": "Linkki",
    "panelDiagram": "Kaavio",
    "panelView": "Näkymä",
    "opacity": "Peittävyys",
    "size": "Koko",
    "color": "Väri",
    "rounded": "Pyöristetty",
    "gradient": "Liukuväri",
    "linear": "Lineaarinen",
    "radial": "Säteittäinen",
    "start": "Alku",
    "end": "Loppu",
    "blur": "Sumennus",
    "offsetX": "Siirtymä X",
    "offsetY": "Siirtymä Y",
    "dist": "Etäisyys",
    "solid": "Yhtenäinen",
    "dashed": "Katkoviiva",
    "dotted": "Pisteviiva",
    "straight": "Suora",
    "orthogonal": "Ortogonaalinen",
    "curved": "Kaareva",
    "bold": "Lihavoitu",
    "italic": "Kursivoitu",
    "underline": "Alleviivaus",
    "lineSpacing": "Riviväli",
    "noShapeData": "Ei muototietoja",
    "noLink": "Ei linkkiä",
    "alignLeft": "Tasaa vasemmalle",
    "alignRight": "Tasaa oikealle",
    "alignTop": "Tasaa ylös",
    "alignBottom": "Tasaa alas",
    "alignCenterH": "Keskitä vaakasuunnassa",
    "alignCenterV": "Keskitä pystysuunnassa",
    "alignLeftPage": "Tasaa vasemmalle sivulle",
    "alignRightPage": "Tasaa oikealle sivulle",
    "alignTopPage": "Tasaa ylös sivulle",
    "alignBottomPage": "Tasaa alas sivulle",
    "distributeH": "Jaa vaakasuunnassa",
    "distributeV": "Jaa pystysuunnassa",
    "sameSize": "Sama koko",
    "sameWidth": "Sama leveys",
    "sameHeight": "Sama korkeus",
    "grid": "Ruudukko",
    "background": "Tausta",
    "backgroundPage": "Taustasivu",
    "theme": "Teema",
    "paperSize": "Paperikoko",
    "portrait": "Pysty",
    "landscape": "Vaaka",
    "noneDefault": "Ei mitään (oletus)",
    "custom": "Mukautettu",
    "zoomIn": "Lähennä",
    "zoomOut": "Loitonna",
    "findShapesHint": "Etsi muotoja…",
    "replaceWithHint": "Korvaa tekstillä…",
    "replace": "Korvaa",
    "replaceAll": "Kaikki",
    "previous": "Edellinen",
    "next": "Seuraava",
    "renameLayer": "Nimeä taso uudelleen",
    "name": "Nimi",
    "value": "Arvo",
    "addProperty": "Lisää ominaisuus",
    "remove": "Poista",
    "noLayersYet": "Ei tasoja vielä. Lisää taso järjestääksesi muotoja (näkyvyys / lukitus / tulostus).",
    "visible": "Näkyvä",
    "locked": "Lukittu",
    "print": "Tulosta",
    "assignSelection": "Määritä val.",
    "deleteLayer": "Poista taso",
    "addLayer": "Lisää taso",
    "addLayerWithSelection": "Lisää taso (valinnalla)",
    "labelOptional": "Nimike (valinnainen)",
    "removeLink": "Poista linkki",
    "link": "Linkki",
    "noShapeDataHint": "Ei muototietoja. Lisää ominaisuus aloittaaksesi.",
    "linkHint": "https://example.com  tai  #Page-2",
    "sg_General": "Yleiset",
    "sg_Flowchart": "Vuokaavio",
    "sg_Arrows": "Nuolet",
    "sg_Basic": "Perus",
    "sg_Containers": "Säilöt",
    "sg_UML": "UML",
    "sg_ER": "ER",
    "sg_BPMN": "BPMN",
    "sg_Misc": "Muut",
    "sg_Advanced": "Edistyneet",
    "flipHorizontal": "Peilaa vaakasuunnassa",
    "flipVertical": "Peilaa pystysuunnassa",
    "rotateLeft90": "Kierrä 90° vasemmalle",
    "rotateRight90": "Kierrä 90° oikealle",
    "centerHorizontally": "Keskitä vaakasuunnassa",
    "centerHorizontallyPage": "Keskitä vaakasuunnassa sivulle",
    "centerVertically": "Keskitä pystysuunnassa",
    "centerVerticallyPage": "Keskitä pystysuunnassa sivulle",
    "justify": "Tasaa molemmat",
    "spaceBefore": "Väli ennen",
    "spaceAfter": "Väli jälkeen",
    "dropToOpen": "Pudota avataksesi",
    "openFileFailed": "Tiedostoa ei voitu avata: {error}",
    "openPathFailed": "Kohdetta {path} ei voitu avata",
    "openExampleFailed": "Esimerkkiä {name} ei voitu avata",
    "insertImageFailed": "Kuvaa ei voitu lisätä",
    "replacedWith": "Korvattu: {name}",
    "insertedNamed": "Lisätty {name}",
    "strikethrough": "Yliviivaus",
    "dashDot": "Viiva-piste",
    "compoundSingle": "Yksi",
    "compoundDouble": "Kaksois",
    "compoundThickThin": "Paksu-ohut",
    "compoundThinThick": "Ohut-paksu",
    "arrowFilled": "Täytetty",
    "arrowOpen": "Avoin",
    "arrowThin": "Ohut",
    "arrowStealth": "Stealth",
    "arrowCircle": "Ympyrä",
    "arrowOpenDiamond": "Avoin timantti",
    "arrowCircleOpen": "Ympyrä (avoin)",
    "arrowNumbered": "Nuoli #{id}",
    "defaultFont": "Oletus",
    "noResults": "Ei tuloksia",
    "matchCaseOn": "Sama kirjainkoko: päällä",
    "matchCaseOff": "Sama kirjainkoko: pois",
    "wholeWordOn": "Koko sana: päällä",
    "wholeWordOff": "Koko sana: pois",
    "hideReplace": "Piilota korvaa",
    "showReplace": "Näytä korvaa",
    "backgroundPageHint": "Käytä muiden sivujen alustana",
    "useBackground": "Käytä taustaa",
    "willMarkBackground": "{name} (merkitään taustaksi)",
    "corners": "Kulmat",
    "jumpRadius": "Hyppy-säde",
    "patternBrick": "Tiili",
    "patternShingle": "Paanu",
}

NL = {
    "cancel": "Annuleren",
    "ok": "OK",
    "apply": "Toepassen",
    "close": "Sluiten",
    "delete": "Verwijderen",
    "rename": "Naam wijzigen",
    "discard": "Negeren",
    "none": "Geen",
    "enabled": "Ingeschakeld",
    "untitled": "Naamloos",
    "undo": "Ongedaan maken",
    "redo": "Opnieuw",
    "outline": "Overzicht",
    "rulers": "Linialen",
    "toggleGrid": "Raster tonen/verbergen",
    "fitToWindow": "Passend in venster",
    "layers": "Lagen",
    "insertImage": "Afbeelding invoegen…",
    "hideOutline": "Overzicht verbergen",
    "selectAll": "Alles selecteren",
    "find": "Zoeken…",
    "findReplace": "Zoeken en vervangen…",
    "editData": "Gegevens bewerken…",
    "editLink": "Koppeling bewerken…",
    "editConnectionPoints": "Verbindingspunten bewerken…",
    "doneEditingConnectionPoints": "Bewerken van verbindingspunten voltooien",
    "lock": "Vergrendelen",
    "unlock": "Ontgrendelen",
    "zoomToSelection": "Zoomen op selectie",
    "copyStyle": "Opmaak kopiëren",
    "pasteStyle": "Opmaak plakken",
    "saveAs": "Opslaan als…",
    "exportSvg": "Exporteren als SVG…",
    "exportPng": "Exporteren als PNG…",
    "exportPdf": "Exporteren als PDF…",
    "snapToGrid": "Uitlijnen op raster",
    "lineJumps": "Lijnsprongen",
    "closeTab": "Tabblad sluiten",
    "cut": "Knippen",
    "copy": "Kopiëren",
    "paste": "Plakken",
    "pasteHere": "Hier plakken",
    "duplicate": "Dupliceren",
    "clearWaypoints": "Padpunten wissen",
    "bringToFront": "Naar voorgrond",
    "sendToBack": "Naar achtergrond",
    "bringForward": "Een laag naar voren",
    "sendBackward": "Een laag naar achteren",
    "group": "Groeperen",
    "ungroup": "Groep opheffen",
    "editText": "Tekst bewerken…",
    "replaceImage": "Afbeelding vervangen…",
    "addLane": "Baan toevoegen",
    "removeLane": "Baan verwijderen",
    "addRow": "Rij toevoegen",
    "addColumn": "Kolom toevoegen",
    "deleteRow": "Rij verwijderen",
    "deleteColumn": "Kolom verwijderen",
    "mergeCells": "Cellen samenvoegen",
    "unmergeCells": "Cellen splitsen",
    "clearGuides": "Hulplijnen wissen",
    "toolSelect": "Selecteren / verplaatsen",
    "toolRectangle": "Rechthoek",
    "toolEllipse": "Ellips",
    "toolLine": "Lijn",
    "toolConnector": "Connector (lijm)",
    "toolFreehand": "Vrije hand",
    "toolText": "Tekst",
    "moreShapes": "Meer vormen",
    "searchShapes": "Vormen zoeken",
    "categoriesCount": "{n} categorieën",
    "expandAll": "Alles uitvouwen",
    "collapseAll": "Alles samenvouwen",
    "addPage": "Pagina toevoegen",
    "duplicatePage": "Pagina dupliceren",
    "deletePage": "Pagina verwijderen",
    "renamePage": "Pagina hernoemen",
    "pageNameHint": "Paginanaam",
    "pageReorderHint": "Slepen om te herordenen · Dubbelklikken om te hernoemen",
    "backgroundPageReorderHint": "Achtergrondpagina · Slepen om te herordenen · Dubbelklikken om te hernoemen",
    "pageOf": "Pagina {current} van {total}",
    "unsaved": "Niet opgeslagen",
    "noSelection": "Geen selectie",
    "selectedCount": "{n} geselecteerd",
    "emptySubtitle": "Maak een nieuwe tekening, of sleep / open .vsdx-bestanden (elk in een eigen tabblad).",
    "newDrawing": "Nieuwe tekening",
    "openVisioDrawing": "Visio-tekening openen",
    "orTrySample": "Of probeer een voorbeeld:",
    "dropHint": "Sleep Visio-bestand of afbeelding hierheen",
    "discardUnsavedTitle": "Niet-opgeslagen wijzigingen negeren?",
    "discardUnsavedBody": "“{name}” heeft niet-opgeslagen wijzigingen.",
    "savedTo": "Opgeslagen naar {path}",
    "saveFailed": "Opslaan mislukt: {error}",
    "exportedSvg": "SVG geëxporteerd naar {path}",
    "exportedPng": "PNG geëxporteerd naar {path}",
    "exportedPdf": "PDF geëxporteerd naar {path}",
    "svgExportFailed": "SVG-export mislukt: {error}",
    "pngExportFailed": "PNG-export mislukt",
    "pngExportFailedError": "PNG-export mislukt: {error}",
    "pdfExportFailed": "PDF-export mislukt: {error}",
    "panelArrange": "Ordenen",
    "panelAlign": "Uitlijnen",
    "panelAlignToPage": "Uitlijnen op pagina",
    "panelFill": "Opvulling",
    "panelLine": "Lijn",
    "panelConnector": "Connector",
    "panelShadow": "Schaduw",
    "panelGlow": "Gloed",
    "panelReflection": "Reflectie",
    "panelSoftEdges": "Zachte randen",
    "panelText": "Tekst",
    "panelImage": "Afbeelding",
    "panelData": "Gegevens",
    "panelLink": "Koppeling",
    "panelDiagram": "Diagram",
    "panelView": "Weergave",
    "opacity": "Dekking",
    "size": "Grootte",
    "color": "Kleur",
    "rounded": "Afgerond",
    "gradient": "Verloop",
    "linear": "Lineair",
    "radial": "Radiaal",
    "start": "Begin",
    "end": "Einde",
    "blur": "Vervagen",
    "offsetX": "Verschuiving X",
    "offsetY": "Verschuiving Y",
    "dist": "Afstand",
    "solid": "Ononderbroken",
    "dashed": "Onderbroken",
    "dotted": "Gestippeld",
    "straight": "Recht",
    "orthogonal": "Orthogonaal",
    "curved": "Gebogen",
    "bold": "Vet",
    "italic": "Cursief",
    "underline": "Onderstrepen",
    "lineSpacing": "Regelafstand",
    "noShapeData": "Geen vormgegevens",
    "noLink": "Geen koppeling",
    "alignLeft": "Links uitlijnen",
    "alignRight": "Rechts uitlijnen",
    "alignTop": "Boven uitlijnen",
    "alignBottom": "Onder uitlijnen",
    "alignCenterH": "Horizontaal centreren",
    "alignCenterV": "Verticaal centreren",
    "alignLeftPage": "Links uitlijnen op pagina",
    "alignRightPage": "Rechts uitlijnen op pagina",
    "alignTopPage": "Boven uitlijnen op pagina",
    "alignBottomPage": "Onder uitlijnen op pagina",
    "distributeH": "Horizontaal verdelen",
    "distributeV": "Verticaal verdelen",
    "sameSize": "Zelfde grootte",
    "sameWidth": "Zelfde breedte",
    "sameHeight": "Zelfde hoogte",
    "grid": "Raster",
    "background": "Achtergrond",
    "backgroundPage": "Achtergrondpagina",
    "theme": "Thema",
    "paperSize": "Papierformaat",
    "portrait": "Staand",
    "landscape": "Liggend",
    "noneDefault": "Geen (standaard)",
    "custom": "Aangepast",
    "zoomIn": "Inzoomen",
    "zoomOut": "Uitzoomen",
    "findShapesHint": "Vormen zoeken…",
    "replaceWithHint": "Vervangen door…",
    "replace": "Vervangen",
    "replaceAll": "Alles",
    "previous": "Vorige",
    "next": "Volgende",
    "renameLayer": "Laag hernoemen",
    "name": "Naam",
    "value": "Waarde",
    "addProperty": "Eigenschap toevoegen",
    "remove": "Verwijderen",
    "noLayersYet": "Nog geen lagen. Voeg er een toe om vormen te organiseren (zichtbaar / vergrendeld / afdrukken).",
    "visible": "Zichtbaar",
    "locked": "Vergrendeld",
    "print": "Afdrukken",
    "assignSelection": "Selectie toew.",
    "deleteLayer": "Laag verwijderen",
    "addLayer": "Laag toevoegen",
    "addLayerWithSelection": "Laag toevoegen (met selectie)",
    "labelOptional": "Label (optioneel)",
    "removeLink": "Koppeling verwijderen",
    "link": "Koppeling",
    "noShapeDataHint": "Geen vormgegevens. Voeg een eigenschap toe om te beginnen.",
    "linkHint": "https://example.com  of  #Page-2",
    "sg_General": "Algemeen",
    "sg_Flowchart": "Stroomdiagram",
    "sg_Arrows": "Pijlen",
    "sg_Basic": "Basis",
    "sg_Containers": "Containers",
    "sg_UML": "UML",
    "sg_ER": "ER",
    "sg_BPMN": "BPMN",
    "sg_Misc": "Diversen",
    "sg_Advanced": "Geavanceerd",
    "flipHorizontal": "Horizontaal spiegelen",
    "flipVertical": "Verticaal spiegelen",
    "rotateLeft90": "90° links draaien",
    "rotateRight90": "90° rechts draaien",
    "centerHorizontally": "Horizontaal centreren",
    "centerHorizontallyPage": "Horizontaal centreren op pagina",
    "centerVertically": "Verticaal centreren",
    "centerVerticallyPage": "Verticaal centreren op pagina",
    "justify": "Uitvullen",
    "spaceBefore": "Ruimte ervoor",
    "spaceAfter": "Ruimte erna",
    "dropToOpen": "Neerzetten om te openen",
    "openFileFailed": "Kan bestand niet openen: {error}",
    "openPathFailed": "Kan {path} niet openen",
    "openExampleFailed": "Kan voorbeeld {name} niet openen",
    "insertImageFailed": "Kan afbeelding niet invoegen",
    "replacedWith": "Vervangen door {name}",
    "insertedNamed": "{name} ingevoegd",
    "strikethrough": "Doorhalen",
    "dashDot": "Streep-punt",
    "compoundSingle": "Enkel",
    "compoundDouble": "Dubbel",
    "compoundThickThin": "Dik-dun",
    "compoundThinThick": "Dun-dik",
    "arrowFilled": "Gevuld",
    "arrowOpen": "Open",
    "arrowThin": "Dun",
    "arrowStealth": "Stealth",
    "arrowCircle": "Cirkel",
    "arrowOpenDiamond": "Open ruit",
    "arrowCircleOpen": "Cirkel (open)",
    "arrowNumbered": "Pijl #{id}",
    "defaultFont": "Standaard",
    "noResults": "Geen resultaten",
    "matchCaseOn": "Hoofdlettergevoelig: aan",
    "matchCaseOff": "Hoofdlettergevoelig: uit",
    "wholeWordOn": "Heel woord: aan",
    "wholeWordOff": "Heel woord: uit",
    "hideReplace": "Vervangen verbergen",
    "showReplace": "Vervangen tonen",
    "backgroundPageHint": "Gebruiken als onderlaag voor andere pagina's",
    "useBackground": "Achtergrond gebruiken",
    "willMarkBackground": "{name} (wordt als bg gemarkeerd)",
    "corners": "Hoeken",
    "jumpRadius": "Sprongstraal",
    "patternBrick": "Baksteen",
    "patternShingle": "Dakpan",
}

CA = {
    "cancel": "Cancel·la",
    "ok": "Acceptar",
    "apply": "Aplica",
    "close": "Tanca",
    "delete": "Suprimeix",
    "rename": "Canvia el nom",
    "discard": "Descarta",
    "none": "Cap",
    "enabled": "Activat",
    "untitled": "Sense títol",
    "undo": "Desfés",
    "redo": "Refés",
    "outline": "Esquema",
    "rulers": "Regles",
    "toggleGrid": "Mostra/amaga la quadrícula",
    "fitToWindow": "Ajusta a la finestra",
    "layers": "Capes",
    "insertImage": "Insereix una imatge…",
    "hideOutline": "Amaga l'esquema",
    "selectAll": "Selecciona-ho tot",
    "find": "Cerca…",
    "findReplace": "Cerca i reemplaça…",
    "editData": "Edita les dades…",
    "editLink": "Edita l'enllaç…",
    "editConnectionPoints": "Edita els punts de connexió…",
    "doneEditingConnectionPoints": "Finalitza l'edició dels punts de connexió",
    "lock": "Bloqueja",
    "unlock": "Desbloqueja",
    "zoomToSelection": "Zoom a la selecció",
    "copyStyle": "Copia l'estil",
    "pasteStyle": "Enganxa l'estil",
    "saveAs": "Anomena i desa…",
    "exportSvg": "Exporta com a SVG…",
    "exportPng": "Exporta com a PNG…",
    "exportPdf": "Exporta com a PDF…",
    "snapToGrid": "Ajusta a la quadrícula",
    "lineJumps": "Salts de línia",
    "closeTab": "Tanca la pestanya",
    "cut": "Retalla",
    "copy": "Copia",
    "paste": "Enganxa",
    "pasteHere": "Enganxa aquí",
    "duplicate": "Duplica",
    "clearWaypoints": "Esborra els punts de ruta",
    "bringToFront": "Porta al davant",
    "sendToBack": "Envia al fons",
    "bringForward": "Porta endavant",
    "sendBackward": "Envia enrere",
    "group": "Agrupa",
    "ungroup": "Desagrupa",
    "editText": "Edita el text…",
    "replaceImage": "Reemplaça la imatge…",
    "addLane": "Afegeix un carril",
    "removeLane": "Suprimeix el carril",
    "addRow": "Afegeix una fila",
    "addColumn": "Afegeix una columna",
    "deleteRow": "Suprimeix la fila",
    "deleteColumn": "Suprimeix la columna",
    "mergeCells": "Combina les cel·les",
    "unmergeCells": "Separa les cel·les",
    "clearGuides": "Esborra les guies",
    "toolSelect": "Selecciona / mou",
    "toolRectangle": "Rectangle",
    "toolEllipse": "El·lipse",
    "toolLine": "Línia",
    "toolConnector": "Connector (enganxa)",
    "toolFreehand": "A mà alçada",
    "toolText": "Text",
    "moreShapes": "Més formes",
    "searchShapes": "Cerca formes",
    "categoriesCount": "{n} categories",
    "expandAll": "Expandeix-ho tot",
    "collapseAll": "Redueix-ho tot",
    "addPage": "Afegeix una pàgina",
    "duplicatePage": "Duplica la pàgina",
    "deletePage": "Suprimeix la pàgina",
    "renamePage": "Canvia el nom de la pàgina",
    "pageNameHint": "Nom de la pàgina",
    "pageReorderHint": "Arrossega per reordenar · Feu doble clic per canviar el nom",
    "backgroundPageReorderHint": "Pàgina de fons · Arrossega per reordenar · Feu doble clic per canviar el nom",
    "pageOf": "Pàgina {current} de {total}",
    "unsaved": "Sense desar",
    "noSelection": "Cap selecció",
    "selectedCount": "{n} seleccionats",
    "emptySubtitle": "Creeu un dibuix nou, o arrossegueu i deixeu anar / obriu fitxers .vsdx (cadascun s'obre a la seva pestanya).",
    "newDrawing": "Dibuix nou",
    "openVisioDrawing": "Obre un dibuix de Visio",
    "orTrySample": "O proveu un exemple:",
    "dropHint": "Deixeu anar un fitxer Visio o una imatge",
    "discardUnsavedTitle": "Voleu descartar els canvis sense desar?",
    "discardUnsavedBody": "“{name}” té canvis sense desar.",
    "savedTo": "Desat a {path}",
    "saveFailed": "No s'ha pogut desar: {error}",
    "exportedSvg": "SVG exportat a {path}",
    "exportedPng": "PNG exportat a {path}",
    "exportedPdf": "PDF exportat a {path}",
    "svgExportFailed": "Ha fallat l'exportació SVG: {error}",
    "pngExportFailed": "Ha fallat l'exportació PNG",
    "pngExportFailedError": "Ha fallat l'exportació PNG: {error}",
    "pdfExportFailed": "Ha fallat l'exportació PDF: {error}",
    "panelArrange": "Organitza",
    "panelAlign": "Alinea",
    "panelAlignToPage": "Alinea a la pàgina",
    "panelFill": "Emplenament",
    "panelLine": "Línia",
    "panelConnector": "Connector",
    "panelShadow": "Ombra",
    "panelGlow": "Brillantor",
    "panelReflection": "Reflex",
    "panelSoftEdges": "Vores suaus",
    "panelText": "Text",
    "panelImage": "Imatge",
    "panelData": "Dades",
    "panelLink": "Enllaç",
    "panelDiagram": "Diagrama",
    "panelView": "Visualització",
    "opacity": "Opacitat",
    "size": "Mida",
    "color": "Color",
    "rounded": "Arrodonit",
    "gradient": "Degradat",
    "linear": "Lineal",
    "radial": "Radial",
    "start": "Inici",
    "end": "Final",
    "blur": "Difuminat",
    "offsetX": "Desplaçament X",
    "offsetY": "Desplaçament Y",
    "dist": "Distància",
    "solid": "Sòlid",
    "dashed": "Discontinu",
    "dotted": "Puntejat",
    "straight": "Recte",
    "orthogonal": "Ortogonal",
    "curved": "Corbat",
    "bold": "Negreta",
    "italic": "Cursiva",
    "underline": "Subratllat",
    "lineSpacing": "Interlineat",
    "noShapeData": "Sense dades de forma",
    "noLink": "Sense enllaç",
    "alignLeft": "Alinea a l'esquerra",
    "alignRight": "Alinea a la dreta",
    "alignTop": "Alinea a dalt",
    "alignBottom": "Alinea a baix",
    "alignCenterH": "Centra horitzontalment",
    "alignCenterV": "Centra verticalment",
    "alignLeftPage": "Alinea a l'esquerra de la pàgina",
    "alignRightPage": "Alinea a la dreta de la pàgina",
    "alignTopPage": "Alinea a dalt de la pàgina",
    "alignBottomPage": "Alinea a baix de la pàgina",
    "distributeH": "Distribueix horitzontalment",
    "distributeV": "Distribueix verticalment",
    "sameSize": "Mateixa mida",
    "sameWidth": "Mateixa amplada",
    "sameHeight": "Mateixa alçada",
    "grid": "Quadrícula",
    "background": "Fons",
    "backgroundPage": "Pàgina de fons",
    "theme": "Tema",
    "paperSize": "Mida del paper",
    "portrait": "Vertical",
    "landscape": "Horitzontal",
    "noneDefault": "Cap (per defecte)",
    "custom": "Personalitzat",
    "zoomIn": "Apropa",
    "zoomOut": "Allunya",
    "findShapesHint": "Cerca formes…",
    "replaceWithHint": "Reemplaça amb…",
    "replace": "Reemplaça",
    "replaceAll": "Tot",
    "previous": "Anterior",
    "next": "Següent",
    "renameLayer": "Canvia el nom de la capa",
    "name": "Nom",
    "value": "Valor",
    "addProperty": "Afegeix una propietat",
    "remove": "Suprimeix",
    "noLayersYet": "Encara no hi ha capes. Afegiu-ne una per organitzar formes (visible / bloquejat / imprimeix).",
    "visible": "Visible",
    "locked": "Bloquejat",
    "print": "Imprimeix",
    "assignSelection": "Assigna sel.",
    "deleteLayer": "Suprimeix la capa",
    "addLayer": "Afegeix una capa",
    "addLayerWithSelection": "Afegeix una capa (amb selecció)",
    "labelOptional": "Etiqueta (opcional)",
    "removeLink": "Suprimeix l'enllaç",
    "link": "Enllaç",
    "noShapeDataHint": "Sense dades de forma. Afegiu una propietat per començar.",
    "linkHint": "https://example.com  o  #Page-2",
    "sg_General": "General",
    "sg_Flowchart": "Diagrama de flux",
    "sg_Arrows": "Fletxes",
    "sg_Basic": "Bàsic",
    "sg_Containers": "Contenidors",
    "sg_UML": "UML",
    "sg_ER": "ER",
    "sg_BPMN": "BPMN",
    "sg_Misc": "Miscel·lània",
    "sg_Advanced": "Avançat",
    "flipHorizontal": "Capgira horitzontalment",
    "flipVertical": "Capgira verticalment",
    "rotateLeft90": "Gira 90° a l'esquerra",
    "rotateRight90": "Gira 90° a la dreta",
    "centerHorizontally": "Centra horitzontalment",
    "centerHorizontallyPage": "Centra horitzontalment a la pàgina",
    "centerVertically": "Centra verticalment",
    "centerVerticallyPage": "Centra verticalment a la pàgina",
    "justify": "Justifica",
    "spaceBefore": "Espai abans",
    "spaceAfter": "Espai després",
    "dropToOpen": "Deixeu anar per obrir",
    "openFileFailed": "No s'ha pogut obrir el fitxer: {error}",
    "openPathFailed": "No s'ha pogut obrir {path}",
    "openExampleFailed": "No s'ha pogut obrir l'exemple {name}",
    "insertImageFailed": "No s'ha pogut inserir la imatge",
    "replacedWith": "Reemplaçat amb {name}",
    "insertedNamed": "S'ha inserit {name}",
    "strikethrough": "Barrat",
    "dashDot": "Guió-punt",
    "compoundSingle": "Simple",
    "compoundDouble": "Doble",
    "compoundThickThin": "Gruixut-fi",
    "compoundThinThick": "Fi-gruixut",
    "arrowFilled": "Ple",
    "arrowOpen": "Obert",
    "arrowThin": "Fi",
    "arrowStealth": "Furtiva",
    "arrowCircle": "Cercle",
    "arrowOpenDiamond": "Diamant obert",
    "arrowCircleOpen": "Cercle (obert)",
    "arrowNumbered": "Fletxa #{id}",
    "defaultFont": "Per defecte",
    "noResults": "Sense resultats",
    "matchCaseOn": "Distingeix majúscules: activat",
    "matchCaseOff": "Distingeix majúscules: desactivat",
    "wholeWordOn": "Paraula sencera: activat",
    "wholeWordOff": "Paraula sencera: desactivat",
    "hideReplace": "Amaga el reemplaçament",
    "showReplace": "Mostra el reemplaçament",
    "backgroundPageHint": "Fes servir com a capa inferior d'altres pàgines",
    "useBackground": "Fes servir el fons",
    "willMarkBackground": "{name} (es marcarà com a fons)",
    "corners": "Cantons",
    "jumpRadius": "Radi del salt",
    "patternBrick": "Maó",
    "patternShingle": "Teula",
}

# Filipino patches for leftover English technical UI terms
FIL_PATCH = {
    "rulers": "Mga ruler",
    "lineJumps": "Mga talon ng linya",
    "toolFreehand": "Malayang kamay",
    "panelFill": "Puno",
    "panelConnector": "Konektor",
    "panelGlow": "Kintab",
    "panelSoftEdges": "Malambot na gilid",
    "panelData": "Datos",
    "panelLink": "Link",
    "panelView": "Tingnan",
    "opacity": "Opasidad",
    "rounded": "Bilog ang sulok",
    "gradient": "Gradient",
    "linear": "Linear",
    "radial": "Radial",
    "blur": "Blur",
    "offsetX": "Offset X",
    "offsetY": "Offset Y",
    "solid": "Solid",
    "dashed": "Dashed",
    "dotted": "May tuldok",
    "orthogonal": "Orthogonal",
    "bold": "Bold",
    "italic": "Italic",
    "underline": "Underline",
    "justify": "Pantayin ang magkabilang gilid",
    "jumpRadius": "Radius ng talon",
    "defaultFont": "Default",
    "matchCaseOn": "Tugmang laki ng titik: naka-on",
    "matchCaseOff": "Tugmang laki ng titik: naka-off",
    "wholeWordOn": "Buong salita: naka-on",
    "wholeWordOff": "Buong salita: naka-off",
    "hideReplace": "Itago ang palitan",
    "showReplace": "Ipakita ang palitan",
    "patternBrick": "Ladrilyo",
    "patternShingle": "Shingle",
    "arrowOpen": "Bukas",
    "arrowThin": "Manipis",
    "arrowStealth": "Stealth",
    "arrowFilled": "Puno",
    "compoundSingle": "Isa",
    "compoundDouble": "Doble",
    "strikethrough": "May guhit sa gitna",
}


BANKS = {
    "da": DA,
    "nb": NB,
    "sv": SV,
    "fi": FI,
    "nl": NL,
    "ca": CA,
}


def build_ui(base: dict[str, str]) -> dict[str, str]:
    return shortcuts(base)


def main() -> None:
    text = MAPS.read_text()
    en = parse_const_map(text, "en")
    ui_keys = [k for k in en if not k.startswith("st_")]

    banks_cache: dict[str, dict[str, str]] = {}
    if BANKS_JSON.exists():
        banks_cache = json.loads(BANKS_JSON.read_text())

    for lang, base in BANKS.items():
        ui = build_ui(base)
        missing = [k for k in ui_keys if k not in ui]
        if missing:
            raise SystemExit(f"{lang} missing keys: {missing[:20]} ({len(missing)} total)")
        extra = [k for k in ui if k not in ui_keys]
        if extra:
            raise SystemExit(f"{lang} extra keys: {extra}")

        old = parse_const_map(text, lang)
        st = {k: v for k, v in old.items() if k.startswith("st_")}
        merged = {**{k: ui[k] for k in ui_keys}, **st}
        text = replace_const_map(text, lang, merged)
        banks_cache[lang] = {k: ui[k] for k in ui_keys}
        print(f"{lang}: rewrote {len(ui_keys)} UI keys (kept {len(st)} stencils)")

    # Filipino patches
    fil_old = parse_const_map(text, "fil")
    fil_ui = {k: fil_old[k] for k in ui_keys}
    fil_ui.update(FIL_PATCH)
    fil_ui = shortcuts({**fil_ui, "showReplace": fil_ui.get("showReplace", FIL_PATCH["showReplace"]),
                        "rotateRight90": fil_ui.get("rotateRight90", "I-rotate nang 90° pakanan"),
                        "ungroup": fil_ui.get("ungroup", "I-ungroup"),
                        "close": fil_ui.get("close", "Isara"),
                        "previous": fil_ui.get("previous", "Nakaraan"),
                        "next": fil_ui.get("next", "Susunod"),
                        "group": fil_ui.get("group", "I-group"),
                        "bringForward": fil_ui.get("bringForward", "Ilipat pasulong"),
                        "sendBackward": fil_ui.get("sendBackward", "Ilipat paatras"),
                        "lock": fil_ui.get("lock", "I-lock"),
                        "unlock": fil_ui.get("unlock", "I-unlock"),
                        "copyStyle": fil_ui.get("copyStyle", "Kopyahin ang estilo"),
                        "pasteStyle": fil_ui.get("pasteStyle", "I-paste ang estilo"),
                        "closeTab": fil_ui.get("closeTab", "Isara ang tab"),
                        "selectAll": fil_ui.get("selectAll", "Piliin lahat"),
                        "find": fil_ui.get("find", "Hanapin…"),
                        "findReplace": fil_ui.get("findReplace", "Hanapin at palitan…"),
                        "editData": fil_ui.get("editData", "I-edit ang datos…"),
                        "editLink": fil_ui.get("editLink", "I-edit ang link…"),
                        "fitToWindow": fil_ui.get("fitToWindow", "Iangkop sa window"),
                        })
    # Re-apply patches after shortcuts may overwrite nothing important
    fil_ui.update(FIL_PATCH)
    fil_merged = {**{k: fil_ui[k] for k in ui_keys}, **{k: v for k, v in fil_old.items() if k.startswith("st_")}}
    text = replace_const_map(text, "fil", fil_merged)
    banks_cache["fil"] = {k: fil_ui[k] for k in ui_keys}
    print(f"fil: patched {len(FIL_PATCH)} UI keys")

    MAPS.write_text(text)
    BANKS_JSON.write_text(json.dumps(banks_cache, ensure_ascii=False))
    print("wrote", MAPS)
    print("wrote", BANKS_JSON)


if __name__ == "__main__":
    main()
