/// Built-in image clipart for the materials palette.
///
/// Assets live under `assets/materials/` (64×64 PNGs). Insertion loads the
/// bytes and embeds them via [EditorController.insertImage] — these are not
/// geometric stencils.
class ImageMaterial {
  const ImageMaterial({
    required this.id,
    required this.name,
    required this.assetPath,
  });

  /// Stable id / filename stem (also used for l10n: `im_<id>`).
  final String id;

  /// English display name.
  final String name;

  /// Flutter asset path, e.g. `assets/materials/person.png`.
  final String assetPath;

  String get fileExtension => 'png';
}

class ImageMaterialGroup {
  const ImageMaterialGroup(this.name, this.items);

  final String name;
  final List<ImageMaterial> items;
}

/// Default max edge length (inches) when inserting a material image so large
/// source files cannot dominate the page. 64×64 @ 96 dpi is ~0.67".
const double kImageMaterialMaxInches = 1.0;

ImageMaterial _m(String id, String name) => ImageMaterial(
      id: id,
      name: name,
      assetPath: 'assets/materials/$id.png',
    );

/// Diagram-friendly clipart grouped for the materials sidebar.
final List<ImageMaterialGroup> kImageMaterialGroups = <ImageMaterialGroup>[
  ImageMaterialGroup('People', <ImageMaterial>[
    _m('person', 'Person'),
    _m('users', 'Users'),
    _m('manager', 'Manager'),
    _m('handshake', 'Handshake'),
    _m('support', 'Support'),
    _m('id_badge', 'ID Badge'),
    _m('team', 'Team'),
    _m('developer', 'Developer'),
    _m('customer', 'Customer'),
    _m('admin', 'Admin'),
    _m('nurse', 'Nurse'),
    _m('courier', 'Courier'),
    _m('teacher', 'Teacher'),
    _m('athlete', 'Athlete'),
    _m('doctor', 'Doctor'),
    _m('chef', 'Chef'),
    _m('farmer', 'Farmer'),
    _m('soldier', 'Soldier'),
  ]),
  ImageMaterialGroup('IT', <ImageMaterial>[
    _m('server', 'Server'),
    _m('database', 'Database'),
    _m('cloud', 'Cloud'),
    _m('laptop', 'Laptop'),
    _m('phone', 'Phone'),
    _m('globe', 'Globe'),
    _m('monitor', 'Monitor'),
    _m('hard_drive', 'Hard Drive'),
    _m('code', 'Code'),
    _m('tablet', 'Tablet'),
    _m('cpu', 'CPU'),
    _m('battery', 'Battery'),
    _m('usb', 'USB'),
    _m('robot', 'Robot'),
    _m('cloud_upload', 'Cloud Upload'),
    _m('cloud_download', 'Cloud Download'),
    _m('terminal', 'Terminal'),
    _m('keyboard', 'Keyboard'),
    _m('network_switch', 'Switch'),
    _m('container', 'Container'),
    _m('mouse', 'Mouse'),
    _m('webcam', 'Webcam'),
    _m('sd_card', 'SD Card'),
    _m('stack', 'Stack'),
    _m('branch', 'Branch'),
    _m('layers', 'Layers'),
    _m('browser', 'Browser'),
    _m('cache', 'Cache'),
    _m('queue', 'Queue'),
    _m('floppy', 'Floppy'),
    _m('cd', 'CD'),
    _m('ai', 'AI'),
    _m('disk', 'Disk'),
  ]),
  ImageMaterialGroup('Office', <ImageMaterial>[
    _m('document', 'Document'),
    _m('folder', 'Folder'),
    _m('email', 'Email'),
    _m('building', 'Building'),
    _m('calendar', 'Calendar'),
    _m('printer', 'Printer'),
    _m('clipboard', 'Clipboard'),
    _m('briefcase', 'Briefcase'),
    _m('sticky_note', 'Sticky Note'),
    _m('presentation', 'Presentation'),
    _m('book', 'Book'),
    _m('inbox', 'Inbox'),
    _m('megaphone', 'Megaphone'),
    _m('attachment', 'Attachment'),
    _m('tag', 'Tag'),
    _m('filter', 'Filter'),
    _m('calculator', 'Calculator'),
    _m('archive', 'Archive'),
    _m('pen', 'Pen'),
    _m('scissors', 'Scissors'),
    _m('stamp', 'Stamp'),
    _m('notepad', 'Notepad'),
    _m('binder', 'Binder'),
    _m('folder_open', 'Folder Open'),
    _m('desk', 'Desk'),
    _m('whiteboard', 'Whiteboard'),
    _m('fax', 'Fax'),
    _m('stapler', 'Stapler'),
    _m('highlighter', 'Highlighter'),
  ]),
  ImageMaterialGroup('Status', <ImageMaterial>[
    _m('lock', 'Lock'),
    _m('warning', 'Warning'),
    _m('check', 'Check'),
    _m('cross', 'Cross'),
    _m('info', 'Info'),
    _m('settings', 'Settings'),
    _m('chart', 'Chart'),
    _m('camera', 'Camera'),
    _m('star', 'Star'),
    _m('bell', 'Bell'),
    _m('heart', 'Heart'),
    _m('key', 'Key'),
    _m('refresh', 'Refresh'),
    _m('pause', 'Pause'),
    _m('play', 'Play'),
    _m('stop', 'Stop'),
    _m('download', 'Download'),
    _m('upload', 'Upload'),
    _m('question', 'Question'),
    _m('power', 'Power'),
    _m('thumbs_up', 'Thumbs Up'),
    _m('signal', 'Signal'),
    _m('bookmark', 'Bookmark'),
    _m('share', 'Share'),
    _m('mute', 'Mute'),
    _m('hourglass', 'Hourglass'),
    _m('pin', 'Pin'),
    _m('infinity', 'Infinity'),
    _m('trash', 'Trash'),
    _m('edit', 'Edit'),
    _m('copy', 'Copy'),
    _m('link_off', 'Link Off'),
    _m('visibility', 'Visibility'),
    _m('clipboard_check', 'Clipboard Check'),
    _m('sparkles', 'Sparkles'),
  ]),
  ImageMaterialGroup('Network', <ImageMaterial>[
    _m('wifi', 'Wifi'),
    _m('router', 'Router'),
    _m('firewall', 'Firewall'),
    _m('api', 'API'),
    _m('link', 'Link'),
    _m('bluetooth', 'Bluetooth'),
    _m('satellite', 'Satellite'),
    _m('ethernet', 'Ethernet'),
    _m('vpn', 'VPN'),
    _m('dns', 'DNS'),
    _m('gateway', 'Gateway'),
    _m('hotspot', 'Hotspot'),
    _m('load_balancer', 'Load Balancer'),
    _m('proxy', 'Proxy'),
    _m('mesh', 'Mesh'),
    _m('cdn', 'CDN'),
    _m('webhook', 'Webhook'),
    _m('lan', 'LAN'),
    _m('bridge', 'Bridge'),
    _m('tunnel', 'Tunnel'),
  ]),
  ImageMaterialGroup('Business', <ImageMaterial>[
    _m('lightbulb', 'Lightbulb'),
    _m('target', 'Target'),
    _m('flag', 'Flag'),
    _m('rocket', 'Rocket'),
    _m('clock', 'Clock'),
    _m('package', 'Package'),
    _m('map_pin', 'Map Pin'),
    _m('wallet', 'Wallet'),
    _m('credit_card', 'Credit Card'),
    _m('shopping_cart', 'Shopping Cart'),
    _m('trophy', 'Trophy'),
    _m('chart_pie', 'Pie Chart'),
    _m('barcode', 'Barcode'),
    _m('qr_code', 'QR Code'),
    _m('funnel', 'Funnel'),
    _m('coin', 'Coin'),
    _m('contract', 'Contract'),
    _m('chart_line', 'Line Chart'),
    _m('invoice', 'Invoice'),
    _m('timeline', 'Timeline'),
    _m('kanban', 'Kanban'),
    _m('percent', 'Percent'),
    _m('gift', 'Gift'),
    _m('balance', 'Balance'),
    _m('storefront', 'Storefront'),
    _m('auction', 'Auction'),
    _m('shopping_bag', 'Shopping Bag'),
    _m('receipt', 'Receipt'),
    _m('deal', 'Deal'),
    _m('insurance', 'Insurance'),
  ]),
  ImageMaterialGroup('Security', <ImageMaterial>[
    _m('shield', 'Shield'),
    _m('fingerprint', 'Fingerprint'),
    _m('eye', 'Eye'),
    _m('unlock', 'Unlock'),
    _m('vault', 'Vault'),
    _m('password', 'Password'),
    _m('bug', 'Bug'),
    _m('certificate', 'Certificate'),
    _m('cctv', 'CCTV'),
    _m('anonymize', 'Anonymize'),
    _m('alarm', 'Alarm'),
    _m('scan', 'Scan'),
    _m('fire_extinguisher', 'Fire Extinguisher'),
    _m('police', 'Police'),
    _m('helmet', 'Helmet'),
    _m('siren', 'Siren'),
  ]),
  ImageMaterialGroup('Transport', <ImageMaterial>[
    _m('truck', 'Truck'),
    _m('car', 'Car'),
    _m('plane', 'Plane'),
    _m('ship', 'Ship'),
    _m('train', 'Train'),
    _m('bike', 'Bike'),
    _m('bus', 'Bus'),
    _m('parking', 'Parking'),
    _m('ambulance', 'Ambulance'),
    _m('scooter', 'Scooter'),
    _m('metro', 'Metro'),
    _m('helicopter', 'Helicopter'),
    _m('taxi', 'Taxi'),
    _m('ferry', 'Ferry'),
    _m('submarine', 'Submarine'),
    _m('forklift', 'Forklift'),
  ]),
  ImageMaterialGroup('Media', <ImageMaterial>[
    _m('music', 'Music'),
    _m('headphones', 'Headphones'),
    _m('mic', 'Mic'),
    _m('film', 'Film'),
    _m('speaker', 'Speaker'),
    _m('photo', 'Photo'),
    _m('video', 'Video'),
    _m('tv', 'TV'),
    _m('radio', 'Radio'),
    _m('podcast', 'Podcast'),
    _m('clapper', 'Clapper'),
    _m('gamepad', 'Gamepad'),
    _m('ebook', 'Ebook'),
    _m('vinyl', 'Vinyl'),
    _m('projector', 'Projector'),
    _m('ticket', 'Ticket'),
    _m('newspaper', 'Newspaper'),
  ]),
  ImageMaterialGroup('Tools', <ImageMaterial>[
    _m('wrench', 'Wrench'),
    _m('hammer', 'Hammer'),
    _m('magnifier', 'Magnifier'),
    _m('compass', 'Compass'),
    _m('screwdriver', 'Screwdriver'),
    _m('ruler', 'Ruler'),
    _m('bolt', 'Bolt'),
    _m('paintbrush', 'Paintbrush'),
    _m('flashlight', 'Flashlight'),
    _m('ladder', 'Ladder'),
    _m('saw', 'Saw'),
    _m('pliers', 'Pliers'),
    _m('tape', 'Tape'),
    _m('drill', 'Drill'),
    _m('level', 'Level'),
    _m('axe', 'Axe'),
    _m('shovel', 'Shovel'),
  ]),
  ImageMaterialGroup('Places', <ImageMaterial>[
    _m('home', 'Home'),
    _m('factory', 'Factory'),
    _m('hospital', 'Hospital'),
    _m('school', 'School'),
    _m('warehouse', 'Warehouse'),
    _m('store', 'Store'),
    _m('lab', 'Lab'),
    _m('airport', 'Airport'),
    _m('park', 'Park'),
    _m('bank', 'Bank'),
    _m('gym', 'Gym'),
    _m('hotel', 'Hotel'),
    _m('museum', 'Museum'),
    _m('church', 'Church'),
    _m('stadium', 'Stadium'),
    _m('beach', 'Beach'),
    _m('castle', 'Castle'),
  ]),
  ImageMaterialGroup('Communication', <ImageMaterial>[
    _m('chat', 'Chat'),
    _m('call', 'Call'),
    _m('video_call', 'Video Call'),
    _m('comment', 'Comment'),
    _m('broadcast', 'Broadcast'),
    _m('mail_open', 'Mail Open'),
    _m('sms', 'SMS'),
    _m('at_sign', 'At Sign'),
    _m('newsletter', 'Newsletter'),
    _m('voicemail', 'Voicemail'),
    _m('pager', 'Pager'),
    _m('walkie', 'Walkie'),
  ]),
  ImageMaterialGroup('Energy', <ImageMaterial>[
    _m('plug', 'Plug'),
    _m('lightning', 'Lightning'),
    _m('sun', 'Sun'),
    _m('leaf', 'Leaf'),
    _m('recycle', 'Recycle'),
    _m('water', 'Water'),
    _m('thermometer', 'Thermometer'),
    _m('gauge', 'Gauge'),
    _m('wind', 'Wind'),
    _m('flame', 'Flame'),
    _m('battery_charging', 'Battery Charging'),
    _m('hydro', 'Hydro'),
    _m('atom', 'Atom'),
    _m('solar_panel', 'Solar Panel'),
    _m('oil', 'Oil'),
    _m('nuclear', 'Nuclear'),
  ]),
  ImageMaterialGroup('Devices', <ImageMaterial>[
    _m('sensor', 'Sensor'),
    _m('antenna', 'Antenna'),
    _m('smartwatch', 'Smartwatch'),
    _m('drone', 'Drone'),
    _m('nfc', 'NFC'),
    _m('pcb', 'PCB'),
    _m('thermostat', 'Thermostat'),
    _m('doorbell', 'Doorbell'),
    _m('camera_ip', 'IP Camera'),
    _m('smart_lock', 'Smart Lock'),
    _m('speaker_smart', 'Smart Speaker'),
    _m('fridge', 'Fridge'),
  ]),
  ImageMaterialGroup('Data', <ImageMaterial>[
    _m('table', 'Table'),
    _m('spreadsheet', 'Spreadsheet'),
    _m('cube', 'Cube'),
    _m('pipeline', 'Pipeline'),
    _m('json', 'JSON'),
    _m('binary', 'Binary'),
    _m('dataset', 'Dataset'),
    _m('schema', 'Schema'),
    _m('log', 'Log'),
    _m('metric', 'Metric'),
    _m('report', 'Report'),
    _m('etl', 'ETL'),
    _m('index', 'Index'),
    _m('snapshot', 'Snapshot'),
    _m('mirror', 'Mirror'),
  ]),
  ImageMaterialGroup('Health', <ImageMaterial>[
    _m('pill', 'Pill'),
    _m('syringe', 'Syringe'),
    _m('dna', 'DNA'),
    _m('stethoscope', 'Stethoscope'),
    _m('bandage', 'Bandage'),
    _m('wheelchair', 'Wheelchair'),
    _m('vaccine', 'Vaccine'),
    _m('microscope', 'Microscope'),
  ]),
  ImageMaterialGroup('Nature', <ImageMaterial>[
    _m('tree', 'Tree'),
    _m('mountain', 'Mountain'),
    _m('flower', 'Flower'),
    _m('fish', 'Fish'),
    _m('bird', 'Bird'),
    _m('rain', 'Rain'),
  ]),
];

final List<ImageMaterial> kImageMaterials = <ImageMaterial>[
  for (final g in kImageMaterialGroups) ...g.items,
];
