import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_lucide/flutter_lucide.dart';
import 'package:phosphoricons_flutter/phosphoricons_flutter.dart';
import 'package:vsdx/vsdx.dart';

/// An open-source icon from a third-party pack, insertable as a picture node.
class ThirdPartyIcon {
  const ThirdPartyIcon({
    required this.id,
    required this.name,
    required this.icon,
    this.keywords = const <String>[],
  });

  /// Stable id within its provider (e.g. `cloud`).
  final String id;

  /// English display name.
  final String name;

  final IconData icon;

  /// Extra search terms (lowercase).
  final List<String> keywords;
}

/// One icon provider (license is free for commercial use).
class ThirdPartyIconProvider {
  const ThirdPartyIconProvider({
    required this.id,
    required this.name,
    required this.license,
    required this.icons,
  });

  final String id;
  final String name;

  /// Short license label shown in the palette footer.
  final String license;

  final List<ThirdPartyIcon> icons;
}

/// Default edge length (inches) when inserting a rasterised icon.
const double kThirdPartyIconMaxInches = 0.75;

/// Pixel size used when painting an [IconData] to PNG.
const int kThirdPartyIconRasterPx = 128;

/// Default ink colour for newly inserted icons.
const Color kThirdPartyIconDefaultColor = Color(0xFF243040);

ThirdPartyIcon _i(String id, String name, IconData icon,
        [List<String> keywords = const <String>[]]) =>
    ThirdPartyIcon(id: id, name: name, icon: icon, keywords: keywords);

/// Curated diagram-friendly icons from free/commercial-friendly packs.
/// Grouped by provider for the palette; searchable by name / keywords.
final List<ThirdPartyIconProvider> kThirdPartyIconProviders =
    <ThirdPartyIconProvider>[
  ThirdPartyIconProvider(
    id: 'material',
    name: 'Material Icons',
    license: 'Apache-2.0',
    icons: <ThirdPartyIcon>[
      _i('person', 'Person', Icons.person_outline, const ['user', 'people']),
      _i('group', 'Group', Icons.group_outlined, const ['users', 'team']),
      _i('badge', 'Badge', Icons.badge_outlined, const ['id', 'employee']),
      _i('dns', 'Server', Icons.dns_outlined, const ['server', 'host']),
      _i('storage', 'Database', Icons.storage_outlined, const ['db', 'data']),
      _i('cloud', 'Cloud', Icons.cloud_outlined),
      _i('cloud_queue', 'Cloud Queue', Icons.cloud_queue_outlined,
          const ['queue']),
      _i('laptop', 'Laptop', Icons.laptop_outlined, const ['computer']),
      _i('desktop', 'Desktop', Icons.desktop_windows_outlined, const ['pc']),
      _i('phone', 'Phone', Icons.phone_android_outlined, const ['mobile']),
      _i('tablet', 'Tablet', Icons.tablet_mac_outlined),
      _i('public', 'Globe', Icons.public_outlined, const ['world', 'web']),
      _i('description', 'Document', Icons.description_outlined,
          const ['file', 'doc']),
      _i('article', 'Article', Icons.article_outlined, const ['text']),
      _i('folder', 'Folder', Icons.folder_outlined),
      _i('email', 'Email', Icons.email_outlined, const ['mail']),
      _i('inbox', 'Inbox', Icons.inbox_outlined),
      _i('business', 'Building', Icons.business_outlined, const ['office']),
      _i('factory', 'Factory', Icons.factory_outlined, const ['plant']),
      _i('store', 'Store', Icons.storefront_outlined, const ['shop']),
      _i('calendar', 'Calendar', Icons.calendar_today_outlined),
      _i('schedule', 'Schedule', Icons.schedule_outlined, const ['time']),
      _i('print', 'Printer', Icons.print_outlined),
      _i('lock', 'Lock', Icons.lock_outline, const ['security']),
      _i('vpn_key', 'VPN Key', Icons.vpn_key_outlined, const ['key']),
      _i('warning', 'Warning', Icons.warning_amber_outlined, const ['alert']),
      _i('error', 'Error', Icons.error_outline, const ['fail']),
      _i('check', 'Check', Icons.check_circle_outline, const ['ok', 'done']),
      _i('cancel', 'Cancel', Icons.cancel_outlined, const ['close']),
      _i('settings', 'Settings', Icons.settings_outlined, const ['gear']),
      _i('tune', 'Tune', Icons.tune_outlined, const ['adjust']),
      _i('bar_chart', 'Chart', Icons.bar_chart_outlined, const ['analytics']),
      _i('pie_chart', 'Pie Chart', Icons.pie_chart_outline, const ['analytics']),
      _i('timeline', 'Timeline', Icons.timeline_outlined),
      _i('camera', 'Camera', Icons.photo_camera_outlined),
      _i('wifi', 'Wi‑Fi', Icons.wifi_outlined, const ['network']),
      _i('bluetooth', 'Bluetooth', Icons.bluetooth_outlined),
      _i('router', 'Router', Icons.router_outlined, const ['network']),
      _i('shield', 'Shield', Icons.shield_outlined, const ['security']),
      _i('home', 'Home', Icons.home_outlined),
      _i('apartment', 'Apartment', Icons.apartment_outlined),
      _i('link', 'Link', Icons.link, const ['url']),
      _i('search', 'Search', Icons.search),
      _i('download', 'Download', Icons.download_outlined),
      _i('upload', 'Upload', Icons.upload_outlined),
      _i('sync', 'Sync', Icons.sync_outlined, const ['refresh']),
      _i('code', 'Code', Icons.code, const ['developer']),
      _i('terminal', 'Terminal', Icons.terminal_outlined, const ['console']),
      _i('bug', 'Bug', Icons.bug_report_outlined),
      _i('rocket', 'Rocket', Icons.rocket_launch_outlined, const ['launch']),
      _i('bolt', 'Bolt', Icons.bolt_outlined, const ['zap', 'power']),
      _i('battery', 'Battery', Icons.battery_charging_full_outlined),
      _i('key', 'Key', Icons.key_outlined),
      _i('map', 'Map', Icons.map_outlined),
      _i('place', 'Place', Icons.place_outlined, const ['location', 'pin']),
      _i('chat', 'Chat', Icons.chat_bubble_outline, const ['message']),
      _i('forum', 'Forum', Icons.forum_outlined, const ['discussion']),
      _i('image', 'Image', Icons.image_outlined),
      _i('videocam', 'Video', Icons.videocam_outlined),
      _i('mic', 'Mic', Icons.mic_none_outlined, const ['audio']),
      _i('headphones', 'Headphones', Icons.headphones_outlined),
      _i('shopping', 'Cart', Icons.shopping_cart_outlined, const ['shop']),
      _i('payments', 'Payments', Icons.payments_outlined, const ['money']),
      _i('inventory', 'Inventory', Icons.inventory_2_outlined, const ['box']),
      _i('local_shipping', 'Shipping', Icons.local_shipping_outlined,
          const ['truck', 'delivery']),
      _i('hub', 'Hub', Icons.hub_outlined, const ['network', 'node']),
      _i('memory', 'Memory', Icons.memory_outlined, const ['chip', 'cpu']),
      _i('smart_toy', 'Robot', Icons.smart_toy_outlined, const ['bot', 'ai']),
      _i('psychology', 'AI', Icons.psychology_outlined, const ['brain', 'ai']),
      _i('extension', 'Extension', Icons.extension_outlined, const ['plugin']),
      _i('api', 'API', Icons.api_outlined, const ['integration']),
      _i('webhook', 'Webhook', Icons.webhook_outlined),
      _i('dataset', 'Dataset', Icons.dataset_outlined, const ['table']),
      _i('analytics', 'Analytics', Icons.analytics_outlined),
      _i('support', 'Support', Icons.support_agent_outlined, const ['help']),
      _i('verified', 'Verified', Icons.verified_outlined, const ['badge']),
      _i('fingerprint', 'Fingerprint', Icons.fingerprint, const ['biometric']),
      _i('visibility', 'Visibility', Icons.visibility_outlined, const ['eye']),
      _i('favorite', 'Favorite', Icons.favorite_outline, const ['heart']),
      _i('star', 'Star', Icons.star_outline),
      _i('flag', 'Flag', Icons.flag_outlined),
      _i('bookmark', 'Bookmark', Icons.bookmark_outline),
      _i('edit', 'Edit', Icons.edit_outlined, const ['pencil']),
      _i('delete', 'Delete', Icons.delete_outline, const ['trash']),
      _i('add', 'Add', Icons.add_circle_outline, const ['plus']),
      _i('remove', 'Remove', Icons.remove_circle_outline, const ['minus']),
      _i('layers', 'Layers', Icons.layers_outlined),
      _i('dashboard', 'Dashboard', Icons.dashboard_outlined),
      _i('widgets', 'Widgets', Icons.widgets_outlined),
      _i('account_tree', 'Tree', Icons.account_tree_outlined,
          const ['hierarchy', 'org']),
      _i('schema', 'Schema', Icons.schema_outlined, const ['diagram']),
      _i('device_hub', 'Device Hub', Icons.device_hub_outlined),
      _i('lan', 'LAN', Icons.lan_outlined, const ['ethernet']),
      _i('security', 'Security', Icons.security_outlined),
      _i('password', 'Password', Icons.password_outlined),
      _i('notifications', 'Notifications', Icons.notifications_outlined,
          const ['bell']),
      _i('lightbulb', 'Idea', Icons.lightbulb_outline, const ['idea']),
      _i('science', 'Science', Icons.science_outlined, const ['lab']),
      _i('biotech', 'Biotech', Icons.biotech_outlined),
      _i('health', 'Health', Icons.health_and_safety_outlined, const ['medical']),
      _i('school', 'School', Icons.school_outlined, const ['education']),
      _i('work', 'Work', Icons.work_outline, const ['briefcase']),
      _i('flight', 'Flight', Icons.flight_outlined, const ['plane']),
      _i('directions_car', 'Car', Icons.directions_car_outlined),
      _i('train', 'Train', Icons.train_outlined),
      _i('anchor', 'Anchor', Icons.anchor_outlined, const ['ship']),
      _i('park', 'Park', Icons.park_outlined, const ['nature']),
      _i('water', 'Water', Icons.water_drop_outlined),
      _i('energy', 'Energy', Icons.energy_savings_leaf_outlined,
          const ['green']),
      _i('person_add', 'Add Person', Icons.person_add_alt_1_outlined, const ['invite']),
      _i('person_remove', 'Remove Person', Icons.person_remove_outlined),
      _i('engineering', 'Engineer', Icons.engineering_outlined, const ['dev']),
      _i('developer_mode', 'Dev Mode', Icons.developer_mode_outlined),
      _i('cloud_upload', 'Cloud Upload', Icons.cloud_upload_outlined),
      _i('cloud_download', 'Cloud Download', Icons.cloud_download_outlined),
      _i('cloud_off', 'Cloud Off', Icons.cloud_off_outlined),
      _i('folder_open', 'Folder Open', Icons.folder_open_outlined),
      _i('folder_shared', 'Shared Folder', Icons.folder_shared_outlined),
      _i('file_copy', 'Copy File', Icons.file_copy_outlined),
      _i('note', 'Note', Icons.note_outlined),
      _i('sticky_note', 'Sticky Note', Icons.sticky_note_2_outlined),
      _i('newspaper', 'News', Icons.newspaper_outlined),
      _i('campaign', 'Campaign', Icons.campaign_outlined, const ['megaphone']),
      _i('podcasts', 'Podcast', Icons.podcasts_outlined),
      _i('cell_tower', 'Cell Tower', Icons.cell_tower_outlined),
      _i('power', 'Power', Icons.power_settings_new_outlined),
      _i('thermostat', 'Thermostat', Icons.thermostat_outlined),
      _i('local_fire', 'Fire', Icons.local_fire_department_outlined),
      _i('ac_unit', 'Snowflake', Icons.ac_unit_outlined),
      _i('umbrella', 'Umbrella', Icons.beach_access_outlined),
      _i('terrain', 'Mountain', Icons.terrain_outlined),
      _i('forest', 'Forest', Icons.forest_outlined),
      _i('pets', 'Pets', Icons.pets_outlined),
      _i('cruelty_free', 'Cruelty Free', Icons.cruelty_free_outlined),
      _i('restaurant', 'Restaurant', Icons.restaurant_outlined, const ['food']),
      _i('local_cafe', 'Cafe', Icons.local_cafe_outlined, const ['coffee']),
      _i('local_bar', 'Bar', Icons.local_bar_outlined),
      _i('cake', 'Cake', Icons.cake_outlined),
      _i('card_giftcard', 'Gift', Icons.card_giftcard_outlined),
      _i('celebration', 'Party', Icons.celebration_outlined),
      _i('emoji_events', 'Trophy', Icons.emoji_events_outlined, const ['award']),
      _i('military_tech', 'Medal', Icons.military_tech_outlined),
      _i('gps_fixed', 'Target', Icons.gps_fixed, const ['crosshair']),
      _i('explore', 'Compass', Icons.explore_outlined),
      _i('alt_route', 'Route', Icons.alt_route_outlined),
      _i('directions_bus', 'Bus', Icons.directions_bus_outlined),
      _i('directions_bike', 'Bike', Icons.directions_bike_outlined),
      _i('local_hospital', 'Hospital', Icons.local_hospital_outlined),
      _i('medical_services', 'Medical', Icons.medical_services_outlined),
      _i('medication', 'Pill', Icons.medication_outlined),
      _i('vaccines', 'Vaccine', Icons.vaccines_outlined),
      _i('monitor_heart', 'Heart Monitor', Icons.monitor_heart_outlined),
      _i('fitness_center', 'Fitness', Icons.fitness_center_outlined),
      _i('accessible', 'Accessibility', Icons.accessible_outlined, const ['a11y']),
      _i('child_care', 'Child', Icons.child_care_outlined),
      _i('thumb_up', 'Thumbs Up', Icons.thumb_up_outlined),
      _i('thumb_down', 'Thumbs Down', Icons.thumb_down_outlined),
      _i('waving_hand', 'Hand', Icons.waving_hand_outlined),
      _i('handshake', 'Handshake', Icons.handshake_outlined),
      _i('qr_code', 'QR Code', Icons.qr_code_outlined),
      _i('content_copy', 'Copy', Icons.content_copy_outlined),
      _i('content_cut', 'Cut', Icons.content_cut_outlined),
      _i('attach_file', 'Attach', Icons.attach_file_outlined),
      _i('push_pin', 'Pin', Icons.push_pin_outlined),
      _i('hotel', 'Hotel', Icons.hotel_outlined),
      _i('church', 'Church', Icons.church_outlined),
      _i('castle', 'Castle', Icons.castle_outlined),
      _i('museum', 'Museum', Icons.museum_outlined),
      _i('local_library', 'Library', Icons.local_library_outlined),
      _i('confirmation_number', 'Ticket', Icons.confirmation_number_outlined),
      _i('movie', 'Movie', Icons.movie_outlined),
      _i('live_tv', 'TV', Icons.live_tv_outlined),
      _i('library_music', 'Music', Icons.library_music_outlined),
      _i('volume_up', 'Volume', Icons.volume_up_outlined),
      _i('volume_off', 'Mute', Icons.volume_off_outlined),
      _i('play_arrow', 'Play', Icons.play_arrow_outlined),
      _i('pause', 'Pause', Icons.pause_outlined),
      _i('skip_next', 'Skip Next', Icons.skip_next_outlined),
      _i('skip_previous', 'Skip Previous', Icons.skip_previous_outlined),
      _i('repeat', 'Repeat', Icons.repeat_outlined),
      _i('shuffle', 'Shuffle', Icons.shuffle_outlined),
      _i('cast', 'Cast', Icons.cast_outlined),
      _i('airplay', 'AirPlay', Icons.airplay_outlined),
      _i('present_to_all', 'Present', Icons.present_to_all_outlined),
      _i('brush', 'Brush', Icons.brush_outlined),
      _i('palette', 'Palette', Icons.palette_outlined),
      _i('format_paint', 'Paint', Icons.format_paint_outlined),
      _i('auto_fix', 'Eraser', Icons.cleaning_services_outlined),
      _i('straighten', 'Ruler', Icons.straighten_outlined),
      _i('category', 'Shapes', Icons.category_outlined),
      _i('open_with', 'Move', Icons.open_with_outlined),
      _i('zoom_in', 'Zoom In', Icons.zoom_in_outlined),
      _i('zoom_out', 'Zoom Out', Icons.zoom_out_outlined),
      _i('center_focus', 'Focus', Icons.center_focus_strong_outlined),
      _i('contrast', 'Contrast', Icons.contrast_outlined),
      _i('rotate_right', 'Rotate CW', Icons.rotate_right_outlined),
      _i('rotate_left', 'Rotate CCW', Icons.rotate_left_outlined),
      _i('history', 'History', Icons.history_outlined),
      _i('timer', 'Timer', Icons.timer_outlined),
      _i('hourglass', 'Hourglass', Icons.hourglass_empty_outlined),
      _i('alarm', 'Alarm', Icons.alarm_outlined),
      _i('watch', 'Watch', Icons.watch_outlined),
      _i('event_available', 'Event Check', Icons.event_available_outlined),
      _i('event_busy', 'Event Busy', Icons.event_busy_outlined),
      _i('send', 'Send', Icons.send_outlined),
      _i('reply', 'Reply', Icons.reply_outlined),
      _i('forward', 'Forward', Icons.forward_outlined),
      _i('share', 'Share', Icons.share_outlined),
      _i('open_in_new', 'External', Icons.open_in_new_outlined),
      _i('login', 'Log In', Icons.login_outlined),
      _i('logout', 'Log Out', Icons.logout_outlined),
      _i('door_front', 'Door', Icons.door_front_door_outlined),
      _i('gpp_maybe', 'Shield Alert', Icons.gpp_maybe_outlined),
      _i('gpp_bad', 'Shield Off', Icons.gpp_bad_outlined),
      _i('add_moderator', 'Shield Plus', Icons.add_moderator_outlined),
      _i('face', 'Face', Icons.face_outlined),
      _i('alternate_email', 'At', Icons.alternate_email_outlined),
      _i('tag', 'Hash', Icons.tag_outlined),
      _i('percent', 'Percent', Icons.percent_outlined),
      _i('all_inclusive', 'Infinity', Icons.all_inclusive_outlined),
      _i('block', 'Ban', Icons.block_outlined),
      _i('construction', 'Construction', Icons.construction_outlined),
      _i('handyman', 'Handyman', Icons.handyman_outlined),
      _i('build', 'Build', Icons.build_outlined, const ['wrench']),
      _i('format_list_bulleted', 'List', Icons.format_list_bulleted_outlined),
      _i('format_list_numbered', 'Ordered List', Icons.format_list_numbered_outlined),
      _i('checklist', 'Checklist', Icons.checklist_outlined),
      _i('title', 'Heading', Icons.title_outlined),
      _i('format_quote', 'Quote', Icons.format_quote_outlined),
      _i('format_bold', 'Bold', Icons.format_bold_outlined),
      _i('format_italic', 'Italic', Icons.format_italic_outlined),
      _i('translate', 'Translate', Icons.translate_outlined),
      _i('sailing', 'Sailboat', Icons.sailing_outlined),
      _i('flight_takeoff', 'Takeoff', Icons.flight_takeoff_outlined),
      _i('flight_land', 'Landing', Icons.flight_land_outlined),
      _i('account_balance_wallet', 'Wallet', Icons.account_balance_wallet_outlined),
      _i('monetization', 'Coins', Icons.monetization_on_outlined),
      _i('receipt_long', 'Receipt', Icons.receipt_long_outlined),
      _i('shopping_bag', 'Shopping Bag', Icons.shopping_bag_outlined),
      _i('shopping_basket', 'Basket', Icons.shopping_basket_outlined),
      _i('sell', 'Tags', Icons.sell_outlined),
      _i('volunteer', 'Charity', Icons.volunteer_activism_outlined),
      _i('auto_awesome', 'Magic', Icons.auto_awesome_outlined, const ['ai']),
      _i('call', 'Phone Call', Icons.call_outlined),
      _i('call_received', 'Incoming', Icons.call_received_outlined),
      _i('call_made', 'Outgoing', Icons.call_made_outlined),
      _i('drafts', 'Mail Open', Icons.drafts_outlined),
      _i('archive', 'Archive', Icons.archive_outlined),
      _i('recycling', 'Recycle', Icons.recycling_outlined),
      _i('warehouse', 'Warehouse', Icons.warehouse_outlined),
      _i('forklift', 'Forklift', Icons.local_shipping_outlined, const ['forklift']),
      _i('local_taxi', 'Taxi', Icons.local_taxi_outlined),
      _i('tram', 'Tram', Icons.tram_outlined),
      _i('spa', 'Spa', Icons.spa_outlined),
      _i('yard', 'Yard', Icons.yard_outlined),
      _i('eco', 'Eco', Icons.eco_outlined),
      _i('nutrition', 'Nutrition', Icons.restaurant_menu_outlined, const ['food']),
      _i('bakery', 'Bakery', Icons.bakery_dining_outlined),
      _i('kitchen', 'Kitchen', Icons.kitchen_outlined),
      _i('bathtub', 'Bath', Icons.bathtub_outlined),
      _i('weekend', 'Sofa', Icons.weekend_outlined),
      _i('bed', 'Bed', Icons.bed_outlined),
      _i('light', 'Lamp', Icons.light_outlined),
      _i('chair', 'Chair', Icons.chair_outlined),
      _i('git_hub', 'GitHub', Icons.code_outlined),
      _i('commit', 'Commit', Icons.commit_outlined, const ['git']),
      _i('difference', 'Diff', Icons.difference_outlined),
      _i('view_kanban', 'Kanban', Icons.view_kanban_outlined),
      _i('sos', 'SOS', Icons.sos_outlined),
      _i('emergency', 'Emergency', Icons.emergency_outlined),
      _i('flood', 'Flood', Icons.flood_outlined),
      _i('tsunami', 'Tsunami', Icons.tsunami_outlined),
      _i('volcano', 'Volcano', Icons.volcano_outlined),
      _i('cyclone', 'Cyclone', Icons.cyclone_outlined),

    ],
  ),
  ThirdPartyIconProvider(
    id: 'lucide',
    name: 'Lucide',
    license: 'ISC',
    icons: <ThirdPartyIcon>[
      _i('user', 'User', LucideIcons.user, const ['person']),
      _i('users', 'Users', LucideIcons.users, const ['group', 'team']),
      _i('user_cog', 'User Settings', LucideIcons.user_cog),
      _i('server', 'Server', LucideIcons.server),
      _i('database', 'Database', LucideIcons.database, const ['db']),
      _i('cloud', 'Cloud', LucideIcons.cloud),
      _i('cloud_cog', 'Cloud Settings', LucideIcons.cloud_cog),
      _i('laptop', 'Laptop', LucideIcons.laptop, const ['computer']),
      _i('smartphone', 'Phone', LucideIcons.smartphone, const ['mobile']),
      _i('tablet', 'Tablet', LucideIcons.tablet),
      _i('globe', 'Globe', LucideIcons.globe, const ['world', 'web']),
      _i('file', 'File', LucideIcons.file, const ['document']),
      _i('file_text', 'Document', LucideIcons.file_text, const ['doc']),
      _i('files', 'Files', LucideIcons.files),
      _i('folder', 'Folder', LucideIcons.folder),
      _i('folder_open', 'Folder Open', LucideIcons.folder_open),
      _i('mail', 'Mail', LucideIcons.mail, const ['email']),
      _i('inbox', 'Inbox', LucideIcons.inbox),
      _i('building', 'Building', LucideIcons.building, const ['office']),
      _i('building_2', 'Buildings', LucideIcons.building_2),
      _i('factory', 'Factory', LucideIcons.factory),
      _i('store', 'Store', LucideIcons.store),
      _i('calendar', 'Calendar', LucideIcons.calendar),
      _i('clock', 'Clock', LucideIcons.clock, const ['time']),
      _i('printer', 'Printer', LucideIcons.printer),
      _i('lock', 'Lock', LucideIcons.lock, const ['security']),
      _i('unlock', 'Unlock', LucideIcons.lock_open),
      _i('triangle_alert', 'Warning', LucideIcons.triangle_alert,
          const ['alert']),
      _i('circle_alert', 'Alert', LucideIcons.circle_alert),
      _i('circle_check', 'Check', LucideIcons.circle_check, const ['ok']),
      _i('circle_x', 'Cancel', LucideIcons.circle_x),
      _i('settings', 'Settings', LucideIcons.settings, const ['gear']),
      _i('sliders_horizontal', 'Sliders', LucideIcons.sliders_horizontal),
      _i('chart_bar', 'Chart', LucideIcons.chart_bar, const ['analytics']),
      _i('chart_pie', 'Pie Chart', LucideIcons.chart_pie),
      _i('chart_line', 'Line Chart', LucideIcons.chart_line),
      _i('camera', 'Camera', LucideIcons.camera),
      _i('wifi', 'Wi‑Fi', LucideIcons.wifi, const ['network']),
      _i('bluetooth', 'Bluetooth', LucideIcons.bluetooth),
      _i('router', 'Router', LucideIcons.router),
      _i('shield', 'Shield', LucideIcons.shield, const ['security']),
      _i('shield_check', 'Shield Check', LucideIcons.shield_check),
      _i('house', 'Home', LucideIcons.house),
      _i('link', 'Link', LucideIcons.link, const ['url']),
      _i('search', 'Search', LucideIcons.search),
      _i('download', 'Download', LucideIcons.download),
      _i('upload', 'Upload', LucideIcons.upload),
      _i('refresh_cw', 'Refresh', LucideIcons.refresh_cw, const ['sync']),
      _i('code', 'Code', LucideIcons.code),
      _i('bug', 'Bug', LucideIcons.bug),
      _i('rocket', 'Rocket', LucideIcons.rocket, const ['launch']),
      _i('zap', 'Zap', LucideIcons.zap, const ['bolt', 'power']),
      _i('battery_charging', 'Battery', LucideIcons.battery_charging),
      _i('key', 'Key', LucideIcons.key),
      _i('map', 'Map', LucideIcons.map),
      _i('map_pin', 'Map Pin', LucideIcons.map_pin, const ['location']),
      _i('message_square', 'Message', LucideIcons.message_square,
          const ['chat']),
      _i('messages_square', 'Messages', LucideIcons.messages_square),
      _i('image', 'Image', LucideIcons.image),
      _i('video', 'Video', LucideIcons.video),
      _i('mic', 'Mic', LucideIcons.mic),
      _i('headphones', 'Headphones', LucideIcons.headphones),
      _i('shopping_cart', 'Cart', LucideIcons.shopping_cart),
      _i('credit_card', 'Card', LucideIcons.credit_card, const ['payment']),
      _i('package', 'Package', LucideIcons.package, const ['box']),
      _i('truck', 'Truck', LucideIcons.truck, const ['delivery']),
      _i('hard_drive', 'Hard Drive', LucideIcons.hard_drive, const ['disk']),
      _i('network', 'Network', LucideIcons.network),
      _i('cpu', 'CPU', LucideIcons.cpu, const ['processor']),
      _i('monitor', 'Monitor', LucideIcons.monitor, const ['display']),
      _i('briefcase', 'Briefcase', LucideIcons.briefcase, const ['work']),
      _i('layers', 'Layers', LucideIcons.layers),
      _i('layout_dashboard', 'Dashboard', LucideIcons.layout_dashboard),
      _i('terminal', 'Terminal', LucideIcons.terminal, const ['console']),
      _i('git_branch', 'Git Branch', LucideIcons.git_branch, const ['git']),
      _i('git_merge', 'Git Merge', LucideIcons.git_merge),
      _i('bot', 'Bot', LucideIcons.bot, const ['robot', 'ai']),
      _i('sparkles', 'Sparkles', LucideIcons.sparkles, const ['ai', 'magic']),
      _i('brain', 'Brain', LucideIcons.brain, const ['ai']),
      _i('workflow', 'Workflow', LucideIcons.workflow),
      _i('blocks', 'Blocks', LucideIcons.blocks, const ['modules']),
      _i('puzzle', 'Puzzle', LucideIcons.puzzle, const ['plugin']),
      _i('webhook', 'Webhook', LucideIcons.webhook),
      _i('table', 'Table', LucideIcons.table, const ['grid']),
      _i('list_tree', 'Tree', LucideIcons.list_tree, const ['hierarchy']),
      _i('fingerprint', 'Fingerprint', LucideIcons.fingerprint_pattern),
      _i('eye', 'Eye', LucideIcons.eye, const ['visibility']),
      _i('heart', 'Heart', LucideIcons.heart),
      _i('star', 'Star', LucideIcons.star),
      _i('flag', 'Flag', LucideIcons.flag),
      _i('bookmark', 'Bookmark', LucideIcons.bookmark),
      _i('pencil', 'Edit', LucideIcons.pencil, const ['edit']),
      _i('trash', 'Trash', LucideIcons.trash, const ['delete']),
      _i('plus', 'Plus', LucideIcons.plus, const ['add']),
      _i('minus', 'Minus', LucideIcons.minus),
      _i('bell', 'Bell', LucideIcons.bell, const ['notification']),
      _i('lightbulb', 'Idea', LucideIcons.lightbulb, const ['idea']),
      _i('flask_conical', 'Lab', LucideIcons.flask_conical, const ['science']),
      _i('graduation_cap', 'School', LucideIcons.graduation_cap,
          const ['education']),
      _i('plane', 'Plane', LucideIcons.plane, const ['flight']),
      _i('car', 'Car', LucideIcons.car),
      _i('train_front', 'Train', LucideIcons.train_front),
      _i('ship', 'Ship', LucideIcons.ship),
      _i('leaf', 'Leaf', LucideIcons.leaf, const ['green']),
      _i('droplets', 'Water', LucideIcons.droplets),
      _i('sun', 'Sun', LucideIcons.sun),
      _i('moon', 'Moon', LucideIcons.moon),
      _i('server_cog', 'Server Cog', LucideIcons.server_cog, const ['server']),
      _i('database_zap', 'Database Zap', LucideIcons.database_zap, const ['db']),
      _i('cloud_off', 'Cloud Off', LucideIcons.cloud_off),
      _i('cloud_upload', 'Cloud Upload', LucideIcons.cloud_upload, const ['upload']),
      _i('cloud_download', 'Cloud Download', LucideIcons.cloud_download, const ['download']),
      _i('folder_git_2', 'Git Folder', LucideIcons.folder_git_2, const ['git']),
      _i('git_pull_request', 'Pull Request', LucideIcons.git_pull_request, const ['git', 'pr']),
      _i('git_commit_horizontal', 'Commit', LucideIcons.git_commit_horizontal, const ['git']),
      _i('git_fork', 'Fork', LucideIcons.git_fork, const ['git']),
      _i('kanban', 'Kanban', LucideIcons.kanban, const ['board']),
      _i('clipboard_list', 'Clipboard List', LucideIcons.clipboard_list, const ['tasks']),
      _i('clipboard_check', 'Clipboard Check', LucideIcons.clipboard_check, const ['done']),
      _i('file_code', 'Code File', LucideIcons.file_code, const ['code']),
      _i('book_open', 'Book', LucideIcons.book_open, const ['read']),
      _i('newspaper', 'News', LucideIcons.newspaper, const ['article']),
      _i('megaphone', 'Megaphone', LucideIcons.megaphone, const ['announce']),
      _i('radio', 'Radio', LucideIcons.radio),
      _i('satellite', 'Satellite', LucideIcons.satellite),
      _i('antenna', 'Antenna', LucideIcons.antenna, const ['signal']),
      _i('cable', 'Cable', LucideIcons.cable, const ['wire']),
      _i('plug', 'Plug', LucideIcons.plug, const ['power']),
      _i('unplug', 'Unplug', LucideIcons.unplug),
      _i('power', 'Power', LucideIcons.power),
      _i('battery_full', 'Battery Full', LucideIcons.battery_full),
      _i('battery_low', 'Battery Low', LucideIcons.battery_low),
      _i('thermometer', 'Thermometer', LucideIcons.thermometer, const ['temp']),
      _i('droplet', 'Droplet', LucideIcons.droplet, const ['water']),
      _i('flame', 'Flame', LucideIcons.flame, const ['fire']),
      _i('cloud_sun', 'Partly Cloudy', LucideIcons.cloud_sun, const ['weather']),
      _i('cloud_rain', 'Rain', LucideIcons.cloud_rain, const ['weather']),
      _i('snowflake', 'Snowflake', LucideIcons.snowflake, const ['cold']),
      _i('umbrella', 'Umbrella', LucideIcons.umbrella),
      _i('tent', 'Tent', LucideIcons.tent, const ['camp']),
      _i('mountain', 'Mountain', LucideIcons.mountain),
      _i('trees', 'Trees', LucideIcons.trees, const ['forest']),
      _i('flower_2', 'Flower', LucideIcons.flower_2),
      _i('paw_print', 'Paw', LucideIcons.paw_print, const ['pet']),
      _i('fish', 'Fish', LucideIcons.fish),
      _i('bird', 'Bird', LucideIcons.bird),
      _i('cat', 'Cat', LucideIcons.cat, const ['pet']),
      _i('dog', 'Dog', LucideIcons.dog, const ['pet']),
      _i('coffee', 'Coffee', LucideIcons.coffee),
      _i('utensils', 'Utensils', LucideIcons.utensils, const ['food']),
      _i('wine', 'Wine', LucideIcons.wine),
      _i('beer', 'Beer', LucideIcons.beer),
      _i('cake', 'Cake', LucideIcons.cake),
      _i('gift', 'Gift', LucideIcons.gift),
      _i('party_popper', 'Party', LucideIcons.party_popper, const ['celebrate']),
      _i('trophy', 'Trophy', LucideIcons.trophy, const ['award']),
      _i('medal', 'Medal', LucideIcons.medal),
      _i('award', 'Award', LucideIcons.award),
      _i('target', 'Target', LucideIcons.target, const ['goal']),
      _i('crosshair', 'Crosshair', LucideIcons.crosshair),
      _i('compass', 'Compass', LucideIcons.compass),
      _i('navigation', 'Navigation', LucideIcons.navigation),
      _i('milestone', 'Milestone', LucideIcons.milestone),
      _i('route', 'Route', LucideIcons.route, const ['path']),
      _i('signpost', 'Signpost', LucideIcons.signpost),
      _i('bus', 'Bus', LucideIcons.bus),
      _i('bike', 'Bike', LucideIcons.bike),
      _i('ambulance', 'Ambulance', LucideIcons.ambulance, const ['emergency']),
      _i('siren', 'Siren', LucideIcons.siren, const ['alert']),
      _i('hospital', 'Hospital', LucideIcons.hospital, const ['medical']),
      _i('pill', 'Pill', LucideIcons.pill, const ['medicine']),
      _i('stethoscope', 'Stethoscope', LucideIcons.stethoscope, const ['medical']),
      _i('syringe', 'Syringe', LucideIcons.syringe, const ['medical']),
      _i('heart_pulse', 'Heart Pulse', LucideIcons.heart_pulse, const ['health']),
      _i('activity', 'Activity', LucideIcons.activity, const ['pulse']),
      _i('dumbbell', 'Dumbbell', LucideIcons.dumbbell, const ['fitness']),
      _i('footprints', 'Footprints', LucideIcons.footprints),
      _i('accessibility', 'Accessibility', LucideIcons.accessibility, const ['a11y']),
      _i('baby', 'Baby', LucideIcons.baby),
      _i('smile', 'Smile', LucideIcons.smile),
      _i('frown', 'Frown', LucideIcons.frown),
      _i('meh', 'Meh', LucideIcons.meh),
      _i('thumbs_up', 'Thumbs Up', LucideIcons.thumbs_up, const ['like']),
      _i('thumbs_down', 'Thumbs Down', LucideIcons.thumbs_down),
      _i('hand', 'Hand', LucideIcons.hand),
      _i('handshake', 'Handshake', LucideIcons.handshake, const ['deal']),
      _i('user_plus', 'Add User', LucideIcons.user_plus, const ['invite']),
      _i('user_minus', 'Remove User', LucideIcons.user_minus),
      _i('user_check', 'User Check', LucideIcons.user_check),
      _i('user_x', 'User Remove', LucideIcons.user_x),
      _i('users_round', 'Team', LucideIcons.users_round, const ['group']),
      _i('contact', 'Contact', LucideIcons.contact),
      _i('id_card', 'ID Card', LucideIcons.id_card, const ['badge']),
      _i('qr_code', 'QR Code', LucideIcons.qr_code, const ['qr']),
      _i('barcode', 'Barcode', LucideIcons.barcode),
      _i('scan', 'Scan', LucideIcons.scan),
      _i('scan_line', 'Scan Line', LucideIcons.scan_line),
      _i('copy', 'Copy', LucideIcons.copy),
      _i('clipboard', 'Clipboard', LucideIcons.clipboard),
      _i('scissors', 'Scissors', LucideIcons.scissors, const ['cut']),
      _i('paperclip', 'Paperclip', LucideIcons.paperclip, const ['attach']),
      _i('pin', 'Pin', LucideIcons.pin),
      _i('map_pinned', 'Pinned', LucideIcons.map_pinned, const ['location']),
      _i('hotel', 'Hotel', LucideIcons.hotel),
      _i('church', 'Church', LucideIcons.church),
      _i('landmark', 'Landmark', LucideIcons.landmark),
      _i('castle', 'Castle', LucideIcons.castle),
      _i('university', 'University', LucideIcons.university, const ['school']),
      _i('library', 'Library', LucideIcons.library),
      _i('ticket', 'Ticket', LucideIcons.ticket),
      _i('clapperboard', 'Clapperboard', LucideIcons.clapperboard, const ['movie']),
      _i('film', 'Film', LucideIcons.film, const ['movie']),
      _i('tv', 'TV', LucideIcons.tv),
      _i('podcast', 'Podcast', LucideIcons.podcast),
      _i('music', 'Music', LucideIcons.music),
      _i('disc_3', 'Disc', LucideIcons.disc_3, const ['cd']),
      _i('volume_2', 'Volume', LucideIcons.volume_2, const ['sound']),
      _i('volume_x', 'Mute', LucideIcons.volume_x),
      _i('play', 'Play', LucideIcons.play),
      _i('pause', 'Pause', LucideIcons.pause),
      _i('skip_forward', 'Skip Forward', LucideIcons.skip_forward),
      _i('skip_back', 'Skip Back', LucideIcons.skip_back),
      _i('repeat', 'Repeat', LucideIcons.repeat),
      _i('shuffle', 'Shuffle', LucideIcons.shuffle),
      _i('cast', 'Cast', LucideIcons.cast),
      _i('airplay', 'AirPlay', LucideIcons.airplay),
      _i('monitor_play', 'Monitor Play', LucideIcons.monitor_play),
      _i('projector', 'Projector', LucideIcons.projector),
      _i('presentation', 'Presentation', LucideIcons.presentation),
      _i('pen_tool', 'Pen Tool', LucideIcons.pen_tool, const ['design']),
      _i('brush', 'Brush', LucideIcons.brush),
      _i('palette', 'Palette', LucideIcons.palette, const ['color']),
      _i('paintbrush', 'Paintbrush', LucideIcons.paintbrush),
      _i('eraser', 'Eraser', LucideIcons.eraser),
      _i('ruler', 'Ruler', LucideIcons.ruler),
      _i('triangle', 'Triangle', LucideIcons.triangle),
      _i('circle', 'Circle', LucideIcons.circle),
      _i('square', 'Square', LucideIcons.square),
      _i('hexagon', 'Hexagon', LucideIcons.hexagon),
      _i('octagon', 'Octagon', LucideIcons.octagon),
      _i('diamond', 'Diamond', LucideIcons.diamond),
      _i('shapes', 'Shapes', LucideIcons.shapes),
      _i('move', 'Move', LucideIcons.move),
      _i('maximize_2', 'Maximize', LucideIcons.maximize_2),
      _i('minimize_2', 'Minimize', LucideIcons.minimize_2),
      _i('expand', 'Expand', LucideIcons.expand),
      _i('shrink', 'Shrink', LucideIcons.shrink),
      _i('zoom_in', 'Zoom In', LucideIcons.zoom_in),
      _i('zoom_out', 'Zoom Out', LucideIcons.zoom_out),
      _i('focus', 'Focus', LucideIcons.focus),
      _i('aperture', 'Aperture', LucideIcons.aperture),
      _i('contrast', 'Contrast', LucideIcons.contrast),
      _i('toggle_left', 'Toggle Off', LucideIcons.toggle_left),
      _i('toggle_right', 'Toggle On', LucideIcons.toggle_right),
      _i('rotate_cw', 'Rotate CW', LucideIcons.rotate_cw),
      _i('rotate_ccw', 'Rotate CCW', LucideIcons.rotate_ccw),
      _i('redo_2', 'Redo', LucideIcons.redo_2),
      _i('undo_2', 'Undo', LucideIcons.undo_2),
      _i('history', 'History', LucideIcons.history),
      _i('timer', 'Timer', LucideIcons.timer),
      _i('hourglass', 'Hourglass', LucideIcons.hourglass),
      _i('alarm_clock', 'Alarm', LucideIcons.alarm_clock),
      _i('watch', 'Watch', LucideIcons.watch),
      _i('calendar_days', 'Calendar Days', LucideIcons.calendar_days),
      _i('calendar_check', 'Calendar Check', LucideIcons.calendar_check),
      _i('calendar_plus', 'Calendar Plus', LucideIcons.calendar_plus),
      _i('calendar_x', 'Calendar X', LucideIcons.calendar_x),
      _i('send', 'Send', LucideIcons.send),
      _i('reply', 'Reply', LucideIcons.reply),
      _i('forward', 'Forward', LucideIcons.forward),
      _i('share_2', 'Share', LucideIcons.share_2),
      _i('external_link', 'External Link', LucideIcons.external_link),
      _i('log_in', 'Log In', LucideIcons.log_in),
      _i('log_out', 'Log Out', LucideIcons.log_out),
      _i('door_open', 'Door Open', LucideIcons.door_open),
      _i('key_round', 'Key Round', LucideIcons.key_round),
      _i('shield_alert', 'Shield Alert', LucideIcons.shield_alert, const ['security']),
      _i('shield_off', 'Shield Off', LucideIcons.shield_off),
      _i('shield_plus', 'Shield Plus', LucideIcons.shield_plus),
      _i('lock_keyhole', 'Lock Keyhole', LucideIcons.lock_keyhole),
      _i('scan_face', 'Face Scan', LucideIcons.scan_face, const ['biometric']),
      _i('at_sign', 'At', LucideIcons.at_sign, const ['email']),
      _i('hash', 'Hash', LucideIcons.hash),
      _i('percent', 'Percent', LucideIcons.percent),
      _i('infinity', 'Infinity', LucideIcons.infinity),
      _i('equal', 'Equal', LucideIcons.equal),
      _i('info', 'Info', LucideIcons.info),
      _i('ban', 'Ban', LucideIcons.ban, const ['block']),
      _i('construction', 'Construction', LucideIcons.construction),
      _i('hammer', 'Hammer', LucideIcons.hammer, const ['build']),
      _i('wrench', 'Wrench', LucideIcons.wrench, const ['tool']),
      _i('cog', 'Cog', LucideIcons.cog, const ['settings']),
      _i('list', 'List', LucideIcons.list),
      _i('list_ordered', 'Ordered List', LucideIcons.list_ordered),
      _i('list_checks', 'Checklist', LucideIcons.list_checks),
      _i('square_check', 'Checked', LucideIcons.square_check),
      _i('square_pen', 'Edit Square', LucideIcons.square_pen),
      _i('type', 'Type', LucideIcons.type, const ['text']),
      _i('heading', 'Heading', LucideIcons.heading),
      _i('quote', 'Quote', LucideIcons.quote),
      _i('bold', 'Bold', LucideIcons.bold),
      _i('italic', 'Italic', LucideIcons.italic),
      _i('underline', 'Underline', LucideIcons.underline),
      _i('languages', 'Languages', LucideIcons.languages, const ['translate']),
      _i('earth', 'Earth', LucideIcons.earth, const ['world']),
      _i('waypoints', 'Waypoints', LucideIcons.waypoints),
      _i('anchor', 'Anchor', LucideIcons.anchor),
      _i('sailboat', 'Sailboat', LucideIcons.sailboat),
      _i('plane_takeoff', 'Takeoff', LucideIcons.plane_takeoff),
      _i('plane_landing', 'Landing', LucideIcons.plane_landing),
      _i('wallet', 'Wallet', LucideIcons.wallet, const ['money']),
      _i('banknote', 'Banknote', LucideIcons.banknote, const ['money']),
      _i('coins', 'Coins', LucideIcons.coins, const ['money']),
      _i('circle_dollar_sign', 'Dollar', LucideIcons.circle_dollar_sign, const ['money']),
      _i('receipt', 'Receipt', LucideIcons.receipt),
      _i('shopping_bag', 'Shopping Bag', LucideIcons.shopping_bag),
      _i('shopping_basket', 'Basket', LucideIcons.shopping_basket),
      _i('tags', 'Tags', LucideIcons.tags),
      _i('heart_handshake', 'Charity', LucideIcons.heart_handshake),
      _i('wand_sparkles', 'Magic', LucideIcons.wand_sparkles, const ['ai']),
      _i('bot_message_square', 'Chat Bot', LucideIcons.bot_message_square, const ['ai']),
      _i('message_circle', 'Message Circle', LucideIcons.message_circle, const ['chat']),
      _i('phone_call', 'Phone Call', LucideIcons.phone_call),
      _i('phone_incoming', 'Incoming Call', LucideIcons.phone_incoming),
      _i('phone_outgoing', 'Outgoing Call', LucideIcons.phone_outgoing),
      _i('mail_open', 'Mail Open', LucideIcons.mail_open),
      _i('archive', 'Archive', LucideIcons.archive),
      _i('trash_2', 'Trash Alt', LucideIcons.trash_2, const ['delete']),
      _i('recycle', 'Recycle', LucideIcons.recycle),
      _i('package_open', 'Open Package', LucideIcons.package_open),
      _i('package_check', 'Package Check', LucideIcons.package_check),
      _i('boxes', 'Boxes', LucideIcons.boxes),
      _i('warehouse', 'Warehouse', LucideIcons.warehouse),
      _i('forklift', 'Forklift', LucideIcons.forklift),
      _i('car_front', 'Car Front', LucideIcons.car_front),
      _i('bus_front', 'Bus Front', LucideIcons.bus_front),
      _i('tram_front', 'Tram', LucideIcons.tram_front),
      _i('orbit', 'Orbit', LucideIcons.orbit, const ['space']),
      _i('atom', 'Atom', LucideIcons.atom, const ['science']),
      _i('microscope', 'Microscope', LucideIcons.microscope, const ['science']),
      _i('test_tube', 'Test Tube', LucideIcons.test_tube, const ['lab']),
      _i('dna', 'DNA', LucideIcons.dna, const ['bio']),
      _i('sprout', 'Sprout', LucideIcons.sprout, const ['plant']),
      _i('tree_deciduous', 'Tree', LucideIcons.tree_deciduous),
      _i('tree_pine', 'Pine', LucideIcons.tree_pine),
      _i('wheat', 'Wheat', LucideIcons.wheat),
      _i('apple', 'Apple', LucideIcons.apple, const ['fruit']),
      _i('banana', 'Banana', LucideIcons.banana),
      _i('cherry', 'Cherry', LucideIcons.cherry),
      _i('grape', 'Grape', LucideIcons.grape),
      _i('carrot', 'Carrot', LucideIcons.carrot),
      _i('salad', 'Salad', LucideIcons.salad),
      _i('soup', 'Soup', LucideIcons.soup),
      _i('sandwich', 'Sandwich', LucideIcons.sandwich),
      _i('cookie', 'Cookie', LucideIcons.cookie),
      _i('candy', 'Candy', LucideIcons.candy),
      _i('chef_hat', 'Chef', LucideIcons.chef_hat, const ['cook']),
      _i('cooking_pot', 'Cooking Pot', LucideIcons.cooking_pot),
      _i('refrigerator', 'Fridge', LucideIcons.refrigerator),
      _i('bath', 'Bath', LucideIcons.bath),
      _i('sofa', 'Sofa', LucideIcons.sofa),
      _i('bed', 'Bed', LucideIcons.bed),
      _i('lamp', 'Lamp', LucideIcons.lamp),
      _i('armchair', 'Armchair', LucideIcons.armchair),

    ],
  ),
  ThirdPartyIconProvider(
    id: 'phosphor',
    name: 'Phosphor',
    license: 'MIT',
    icons: <ThirdPartyIcon>[
      _i('user', 'User', PhosphorIconsRegular.user, const ['person']),
      _i('users', 'Users', PhosphorIconsRegular.users, const ['group']),
      _i('identification_badge', 'Badge',
          PhosphorIconsRegular.identificationBadge),
      _i('hard_drives', 'Server', PhosphorIconsRegular.hardDrives,
          const ['server', 'host']),
      _i('database', 'Database', PhosphorIconsRegular.database, const ['db']),
      _i('cloud', 'Cloud', PhosphorIconsRegular.cloud),
      _i('cloud_check', 'Cloud Check', PhosphorIconsRegular.cloudCheck),
      _i('laptop', 'Laptop', PhosphorIconsRegular.laptop, const ['computer']),
      _i('phone', 'Phone', PhosphorIconsRegular.deviceMobile, const ['mobile']),
      _i('tablet', 'Tablet', PhosphorIconsRegular.deviceTablet),
      _i('globe', 'Globe', PhosphorIconsRegular.globe, const ['world']),
      _i('file', 'File', PhosphorIconsRegular.file),
      _i('file_text', 'Document', PhosphorIconsRegular.fileText, const ['doc']),
      _i('folder', 'Folder', PhosphorIconsRegular.folder),
      _i('folder_open', 'Folder Open', PhosphorIconsRegular.folderOpen),
      _i('mail', 'Mail', PhosphorIconsRegular.envelopeSimple, const ['email']),
      _i('tray', 'Inbox', PhosphorIconsRegular.tray),
      _i('building', 'Building', PhosphorIconsRegular.buildings,
          const ['office']),
      _i('factory', 'Factory', PhosphorIconsRegular.factory),
      _i('storefront', 'Store', PhosphorIconsRegular.storefront),
      _i('calendar', 'Calendar', PhosphorIconsRegular.calendarBlank),
      _i('clock', 'Clock', PhosphorIconsRegular.clock),
      _i('printer', 'Printer', PhosphorIconsRegular.printer),
      _i('lock', 'Lock', PhosphorIconsRegular.lock, const ['security']),
      _i('lock_open', 'Unlock', PhosphorIconsRegular.lockOpen),
      _i('warning', 'Warning', PhosphorIconsRegular.warning, const ['alert']),
      _i('check', 'Check', PhosphorIconsRegular.checkCircle, const ['ok']),
      _i('x_circle', 'Cancel', PhosphorIconsRegular.xCircle),
      _i('settings', 'Settings', PhosphorIconsRegular.gear, const ['gear']),
      _i('sliders', 'Sliders', PhosphorIconsRegular.sliders),
      _i('chart', 'Chart', PhosphorIconsRegular.chartBar, const ['analytics']),
      _i('chart_pie', 'Pie Chart', PhosphorIconsRegular.chartPie),
      _i('chart_line', 'Line Chart', PhosphorIconsRegular.chartLine),
      _i('camera', 'Camera', PhosphorIconsRegular.camera),
      _i('wifi', 'Wi‑Fi', PhosphorIconsRegular.wifiHigh, const ['network']),
      _i('bluetooth', 'Bluetooth', PhosphorIconsRegular.bluetooth),
      _i('broadcast', 'Broadcast', PhosphorIconsRegular.broadcast),
      _i('shield', 'Shield', PhosphorIconsRegular.shield, const ['security']),
      _i('shield_check', 'Shield Check', PhosphorIconsRegular.shieldCheck),
      _i('house', 'Home', PhosphorIconsRegular.house),
      _i('link', 'Link', PhosphorIconsRegular.link, const ['url']),
      _i('search', 'Search', PhosphorIconsRegular.magnifyingGlass),
      _i('download', 'Download', PhosphorIconsRegular.downloadSimple),
      _i('upload', 'Upload', PhosphorIconsRegular.uploadSimple),
      _i('arrows_clockwise', 'Sync', PhosphorIconsRegular.arrowsClockwise),
      _i('code', 'Code', PhosphorIconsRegular.code),
      _i('bug', 'Bug', PhosphorIconsRegular.bug),
      _i('rocket', 'Rocket', PhosphorIconsRegular.rocket, const ['launch']),
      _i('lightning', 'Bolt', PhosphorIconsRegular.lightning, const ['zap']),
      _i('battery_charging', 'Battery',
          PhosphorIconsRegular.batteryChargingVertical),
      _i('key', 'Key', PhosphorIconsRegular.key),
      _i('map_trifold', 'Map', PhosphorIconsRegular.mapTrifold),
      _i('map_pin', 'Map Pin', PhosphorIconsRegular.mapPin, const ['location']),
      _i('chat', 'Chat', PhosphorIconsRegular.chatCircle, const ['message']),
      _i('chats', 'Chats', PhosphorIconsRegular.chatsCircle),
      _i('image', 'Image', PhosphorIconsRegular.image),
      _i('video', 'Video', PhosphorIconsRegular.videoCamera),
      _i('microphone', 'Mic', PhosphorIconsRegular.microphone),
      _i('headphones', 'Headphones', PhosphorIconsRegular.headphones),
      _i('shopping_cart', 'Cart', PhosphorIconsRegular.shoppingCart),
      _i('credit_card', 'Card', PhosphorIconsRegular.creditCard),
      _i('package', 'Package', PhosphorIconsRegular.package),
      _i('truck', 'Truck', PhosphorIconsRegular.truck),
      _i('hard_drive', 'Hard Drive', PhosphorIconsRegular.hardDrive),
      _i('desktop', 'Desktop', PhosphorIconsRegular.desktopTower,
          const ['computer', 'pc']),
      _i('cpu', 'CPU', PhosphorIconsRegular.cpu),
      _i('monitor', 'Monitor', PhosphorIconsRegular.monitor),
      _i('briefcase', 'Briefcase', PhosphorIconsRegular.briefcase),
      _i('stack', 'Layers', PhosphorIconsRegular.stack),
      _i('squares_four', 'Dashboard', PhosphorIconsRegular.squaresFour),
      _i('terminal', 'Terminal', PhosphorIconsRegular.terminalWindow),
      _i('git_branch', 'Git Branch', PhosphorIconsRegular.gitBranch),
      _i('git_merge', 'Git Merge', PhosphorIconsRegular.gitMerge),
      _i('robot', 'Bot', PhosphorIconsRegular.robot, const ['ai']),
      _i('sparkle', 'Sparkles', PhosphorIconsRegular.sparkle, const ['ai']),
      _i('brain', 'Brain', PhosphorIconsRegular.brain, const ['ai']),
      _i('flow_arrow', 'Workflow', PhosphorIconsRegular.flowArrow),
      _i('puzzle', 'Puzzle', PhosphorIconsRegular.puzzlePiece),
      _i('plugs', 'Plugs', PhosphorIconsRegular.plugsConnected,
          const ['api', 'integration']),
      _i('table', 'Table', PhosphorIconsRegular.table),
      _i('tree_structure', 'Tree', PhosphorIconsRegular.treeStructure),
      _i('fingerprint', 'Fingerprint', PhosphorIconsRegular.fingerprint),
      _i('eye', 'Eye', PhosphorIconsRegular.eye),
      _i('info', 'Info', PhosphorIconsRegular.info),
      _i('question', 'Help', PhosphorIconsRegular.question, const ['help']),
      _i('heart', 'Heart', PhosphorIconsRegular.heart),
      _i('star', 'Star', PhosphorIconsRegular.star),
      _i('flag', 'Flag', PhosphorIconsRegular.flag),
      _i('bookmark', 'Bookmark', PhosphorIconsRegular.bookmarkSimple),
      _i('pencil', 'Edit', PhosphorIconsRegular.pencilSimple, const ['edit']),
      _i('trash', 'Trash', PhosphorIconsRegular.trash, const ['delete']),
      _i('plus', 'Plus', PhosphorIconsRegular.plus, const ['add']),
      _i('minus', 'Minus', PhosphorIconsRegular.minus),
      _i('bell', 'Bell', PhosphorIconsRegular.bell, const ['notification']),
      _i('lightbulb', 'Idea', PhosphorIconsRegular.lightbulb),
      _i('flask', 'Lab', PhosphorIconsRegular.flask),
      _i('graduation_cap', 'School', PhosphorIconsRegular.graduationCap),
      _i('airplane', 'Plane', PhosphorIconsRegular.airplane),
      _i('car', 'Car', PhosphorIconsRegular.car),
      _i('train', 'Train', PhosphorIconsRegular.train),
      _i('boat', 'Ship', PhosphorIconsRegular.boat),
      _i('leaf', 'Leaf', PhosphorIconsRegular.leaf),
      _i('drop', 'Water', PhosphorIconsRegular.drop),
      _i('sun', 'Sun', PhosphorIconsRegular.sun),
      _i('moon', 'Moon', PhosphorIconsRegular.moon),
      _i('tag', 'Tag', PhosphorIconsRegular.tag),
      _i('music', 'Music', PhosphorIconsRegular.musicNote),
      _i('users_three', 'Users Three', PhosphorIconsRegular.usersThree, const ['team']),
      _i('user_circle', 'User Circle', PhosphorIconsRegular.userCircle),
      _i('user_plus', 'Add User', PhosphorIconsRegular.userPlus, const ['invite']),
      _i('user_minus', 'Remove User', PhosphorIconsRegular.userMinus),
      _i('user_check', 'User Check', PhosphorIconsRegular.userCheck),
      _i('identification_card', 'ID Card', PhosphorIconsRegular.identificationCard, const ['badge']),
      _i('cloud_arrow_up', 'Cloud Upload', PhosphorIconsRegular.cloudArrowUp, const ['upload']),
      _i('cloud_arrow_down', 'Cloud Download', PhosphorIconsRegular.cloudArrowDown, const ['download']),
      _i('cloud_slash', 'Cloud Off', PhosphorIconsRegular.cloudSlash),
      _i('cloud_fog', 'Cloud Fog', PhosphorIconsRegular.cloudFog),
      _i('folder_simple', 'Folder Simple', PhosphorIconsRegular.folderSimple),
      _i('folder_plus', 'Folder Plus', PhosphorIconsRegular.folderPlus),
      _i('file_code', 'Code File', PhosphorIconsRegular.fileCode, const ['code']),
      _i('file_csv', 'CSV', PhosphorIconsRegular.fileCsv),
      _i('file_pdf', 'PDF', PhosphorIconsRegular.filePdf),
      _i('files', 'Files', PhosphorIconsRegular.files),
      _i('clipboard_text', 'Clipboard', PhosphorIconsRegular.clipboardText),
      _i('clipboard_check', 'Clipboard Check', PhosphorIconsRegular.checkSquare),
      _i('note', 'Note', PhosphorIconsRegular.note),
      _i('notebook', 'Notebook', PhosphorIconsRegular.notebook),
      _i('book_open', 'Book', PhosphorIconsRegular.bookOpen),
      _i('newspaper', 'Newspaper', PhosphorIconsRegular.newspaper),
      _i('megaphone', 'Megaphone', PhosphorIconsRegular.megaphone),
      _i('radio', 'Radio', PhosphorIconsRegular.radio),
      _i('wifi_slash', 'Wi‑Fi Off', PhosphorIconsRegular.wifiSlash),
      _i('cell_tower', 'Cell Tower', PhosphorIconsRegular.cellSignalFull),
      _i('plug', 'Plug', PhosphorIconsRegular.plug),
      _i('plug_charging', 'Charging', PhosphorIconsRegular.plugCharging),
      _i('power', 'Power', PhosphorIconsRegular.power),
      _i('battery_full', 'Battery Full', PhosphorIconsRegular.batteryFull),
      _i('battery_empty', 'Battery Empty', PhosphorIconsRegular.batteryEmpty),
      _i('thermometer', 'Thermometer', PhosphorIconsRegular.thermometer),
      _i('fire', 'Fire', PhosphorIconsRegular.fire),
      _i('snowflake', 'Snowflake', PhosphorIconsRegular.snowflake),
      _i('umbrella', 'Umbrella', PhosphorIconsRegular.umbrella),
      _i('mountains', 'Mountains', PhosphorIconsRegular.mountains),
      _i('tree', 'Tree', PhosphorIconsRegular.tree),
      _i('flower', 'Flower', PhosphorIconsRegular.flower),
      _i('paw_print', 'Paw', PhosphorIconsRegular.pawPrint),
      _i('fish', 'Fish', PhosphorIconsRegular.fish),
      _i('bird', 'Bird', PhosphorIconsRegular.bird),
      _i('cat', 'Cat', PhosphorIconsRegular.cat),
      _i('dog', 'Dog', PhosphorIconsRegular.dog),
      _i('coffee', 'Coffee', PhosphorIconsRegular.coffee),
      _i('fork_knife', 'Utensils', PhosphorIconsRegular.forkKnife, const ['food']),
      _i('wine', 'Wine', PhosphorIconsRegular.wine),
      _i('beer_bottle', 'Beer', PhosphorIconsRegular.beerBottle),
      _i('cake', 'Cake', PhosphorIconsRegular.cake),
      _i('gift', 'Gift', PhosphorIconsRegular.gift),
      _i('confetti', 'Party', PhosphorIconsRegular.confetti),
      _i('trophy', 'Trophy', PhosphorIconsRegular.trophy),
      _i('medal', 'Medal', PhosphorIconsRegular.medal),
      _i('target', 'Target', PhosphorIconsRegular.target),
      _i('crosshair', 'Crosshair', PhosphorIconsRegular.crosshair),
      _i('compass', 'Compass', PhosphorIconsRegular.compass),
      _i('navigation_arrow', 'Navigation', PhosphorIconsRegular.navigationArrow),
      _i('path', 'Route', PhosphorIconsRegular.path),
      _i('signpost', 'Signpost', PhosphorIconsRegular.signpost),
      _i('bus', 'Bus', PhosphorIconsRegular.bus),
      _i('bicycle', 'Bike', PhosphorIconsRegular.bicycle),
      _i('ambulance', 'Ambulance', PhosphorIconsRegular.ambulance),
      _i('siren', 'Siren', PhosphorIconsRegular.siren),
      _i('first_aid', 'First Aid', PhosphorIconsRegular.firstAid, const ['medical']),
      _i('pill', 'Pill', PhosphorIconsRegular.pill),
      _i('heartbeat', 'Heartbeat', PhosphorIconsRegular.heartbeat, const ['health']),
      _i('activity', 'Activity', PhosphorIconsRegular.pulse),
      _i('barbell', 'Dumbbell', PhosphorIconsRegular.barbell, const ['fitness']),
      _i('person_simple_walk', 'Walk', PhosphorIconsRegular.personSimpleWalk),
      _i('wheelchair', 'Accessibility', PhosphorIconsRegular.wheelchair, const ['a11y']),
      _i('baby', 'Baby', PhosphorIconsRegular.baby),
      _i('smiley', 'Smile', PhosphorIconsRegular.smiley),
      _i('smiley_meh', 'Meh', PhosphorIconsRegular.smileyMeh),
      _i('smiley_sad', 'Frown', PhosphorIconsRegular.smileySad),
      _i('thumbs_up', 'Thumbs Up', PhosphorIconsRegular.thumbsUp),
      _i('thumbs_down', 'Thumbs Down', PhosphorIconsRegular.thumbsDown),
      _i('hand_waving', 'Hand', PhosphorIconsRegular.handWaving),
      _i('handshake', 'Handshake', PhosphorIconsRegular.handshake),
      _i('qr_code', 'QR Code', PhosphorIconsRegular.qrCode),
      _i('barcode', 'Barcode', PhosphorIconsRegular.barcode),
      _i('scan', 'Scan', PhosphorIconsRegular.scan),
      _i('copy', 'Copy', PhosphorIconsRegular.copy),
      _i('scissors', 'Scissors', PhosphorIconsRegular.scissors),
      _i('paperclip', 'Paperclip', PhosphorIconsRegular.paperclip),
      _i('push_pin', 'Pin', PhosphorIconsRegular.pushPin),
      _i('map_pin_line', 'Map Pin Line', PhosphorIconsRegular.mapPinLine),
      _i('buildings', 'Buildings', PhosphorIconsRegular.buildings),
      _i('house_line', 'House', PhosphorIconsRegular.houseLine),
      _i('hospital', 'Hospital', PhosphorIconsRegular.hospital),
      _i('church', 'Church', PhosphorIconsRegular.church),
      _i('castle_turret', 'Castle', PhosphorIconsRegular.castleTurret),
      _i('ticket', 'Ticket', PhosphorIconsRegular.ticket),
      _i('film_strip', 'Film', PhosphorIconsRegular.filmStrip),
      _i('television', 'TV', PhosphorIconsRegular.television),
      _i('music_notes', 'Music Notes', PhosphorIconsRegular.musicNotes),
      _i('speaker_high', 'Speaker', PhosphorIconsRegular.speakerHigh),
      _i('speaker_slash', 'Mute', PhosphorIconsRegular.speakerSlash),
      _i('play', 'Play', PhosphorIconsRegular.play),
      _i('pause', 'Pause', PhosphorIconsRegular.pause),
      _i('skip_forward', 'Skip Forward', PhosphorIconsRegular.skipForward),
      _i('skip_back', 'Skip Back', PhosphorIconsRegular.skipBack),
      _i('repeat', 'Repeat', PhosphorIconsRegular.repeat),
      _i('shuffle', 'Shuffle', PhosphorIconsRegular.shuffle),
      _i('cast_airplay', 'AirPlay', PhosphorIconsRegular.airplay),
      _i('projector_screen', 'Projector', PhosphorIconsRegular.projectorScreen),
      _i('presentation', 'Presentation', PhosphorIconsRegular.presentation),
      _i('pen_nib', 'Pen', PhosphorIconsRegular.penNib),
      _i('paint_brush', 'Brush', PhosphorIconsRegular.paintBrush),
      _i('palette', 'Palette', PhosphorIconsRegular.palette),
      _i('eraser', 'Eraser', PhosphorIconsRegular.eraser),
      _i('ruler', 'Ruler', PhosphorIconsRegular.ruler),
      _i('triangle', 'Triangle', PhosphorIconsRegular.triangle),
      _i('circle', 'Circle', PhosphorIconsRegular.circle),
      _i('square', 'Square', PhosphorIconsRegular.square),
      _i('hexagon', 'Hexagon', PhosphorIconsRegular.hexagon),
      _i('diamond', 'Diamond', PhosphorIconsRegular.diamond),
      _i('shapes', 'Shapes', PhosphorIconsRegular.shapes),
      _i('arrows_out', 'Expand', PhosphorIconsRegular.arrowsOut),
      _i('arrows_in', 'Shrink', PhosphorIconsRegular.arrowsIn),
      _i('magnifying_glass_plus', 'Zoom In', PhosphorIconsRegular.magnifyingGlassPlus),
      _i('magnifying_glass_minus', 'Zoom Out', PhosphorIconsRegular.magnifyingGlassMinus),
      _i('aperture', 'Aperture', PhosphorIconsRegular.aperture),
      _i('contrast', 'Contrast', PhosphorIconsRegular.circleHalf),
      _i('toggle_left', 'Toggle Off', PhosphorIconsRegular.toggleLeft),
      _i('toggle_right', 'Toggle On', PhosphorIconsRegular.toggleRight),
      _i('arrow_clockwise', 'Rotate CW', PhosphorIconsRegular.arrowClockwise),
      _i('arrow_counter_clockwise', 'Rotate CCW', PhosphorIconsRegular.arrowCounterClockwise),
      _i('arrow_u_up_left', 'Undo', PhosphorIconsRegular.arrowUUpLeft),
      _i('arrow_u_up_right', 'Redo', PhosphorIconsRegular.arrowUUpRight),
      _i('clock_countdown', 'Timer', PhosphorIconsRegular.clockCountdown),
      _i('hourglass', 'Hourglass', PhosphorIconsRegular.hourglass),
      _i('alarm', 'Alarm', PhosphorIconsRegular.alarm),
      _i('watch', 'Watch', PhosphorIconsRegular.watch),
      _i('calendar_check', 'Calendar Check', PhosphorIconsRegular.calendarCheck),
      _i('calendar_plus', 'Calendar Plus', PhosphorIconsRegular.calendarPlus),
      _i('calendar_x', 'Calendar X', PhosphorIconsRegular.calendarX),
      _i('paper_plane_tilt', 'Send', PhosphorIconsRegular.paperPlaneTilt),
      _i('arrow_bend_up_left', 'Reply', PhosphorIconsRegular.arrowBendUpLeft),
      _i('share_network', 'Share', PhosphorIconsRegular.shareNetwork),
      _i('arrow_square_out', 'External', PhosphorIconsRegular.arrowSquareOut),
      _i('sign_in', 'Log In', PhosphorIconsRegular.signIn),
      _i('sign_out', 'Log Out', PhosphorIconsRegular.signOut),
      _i('door_open', 'Door Open', PhosphorIconsRegular.doorOpen),
      _i('shield_warning', 'Shield Alert', PhosphorIconsRegular.shieldWarning),
      _i('shield_slash', 'Shield Off', PhosphorIconsRegular.shieldSlash),
      _i('shield_plus', 'Shield Plus', PhosphorIconsRegular.shieldPlus),
      _i('lock_key', 'Lock Key', PhosphorIconsRegular.lockKey),
      _i('scan_smiley', 'Face Scan', PhosphorIconsRegular.scanSmiley),
      _i('at', 'At', PhosphorIconsRegular.at),
      _i('hash', 'Hash', PhosphorIconsRegular.hash),
      _i('percent', 'Percent', PhosphorIconsRegular.percent),
      _i('infinity', 'Infinity', PhosphorIconsRegular.infinity),
      _i('equals', 'Equal', PhosphorIconsRegular.equals),
      _i('prohibit', 'Ban', PhosphorIconsRegular.prohibit),
      _i('hammer', 'Hammer', PhosphorIconsRegular.hammer),
      _i('wrench', 'Wrench', PhosphorIconsRegular.wrench),
      _i('list', 'List', PhosphorIconsRegular.list),
      _i('list_numbers', 'Ordered List', PhosphorIconsRegular.listNumbers),
      _i('list_checks', 'Checklist', PhosphorIconsRegular.listChecks),
      _i('text_t', 'Type', PhosphorIconsRegular.textT),
      _i('text_h', 'Heading', PhosphorIconsRegular.textH),
      _i('quotes', 'Quote', PhosphorIconsRegular.quotes),
      _i('text_b', 'Bold', PhosphorIconsRegular.textB),
      _i('text_italic', 'Italic', PhosphorIconsRegular.textItalic),
      _i('translate', 'Languages', PhosphorIconsRegular.translate),
      _i('globe_hemisphere_west', 'Earth', PhosphorIconsRegular.globeHemisphereWest),
      _i('anchor', 'Anchor', PhosphorIconsRegular.anchor),
      _i('sailboat', 'Sailboat', PhosphorIconsRegular.sailboat),
      _i('airplane_takeoff', 'Takeoff', PhosphorIconsRegular.airplaneTakeoff),
      _i('airplane_landing', 'Landing', PhosphorIconsRegular.airplaneLanding),
      _i('wallet', 'Wallet', PhosphorIconsRegular.wallet),
      _i('money', 'Money', PhosphorIconsRegular.money),
      _i('coins', 'Coins', PhosphorIconsRegular.coins),
      _i('currency_dollar', 'Dollar', PhosphorIconsRegular.currencyDollar),
      _i('receipt', 'Receipt', PhosphorIconsRegular.receipt),
      _i('shopping_bag', 'Shopping Bag', PhosphorIconsRegular.shoppingBag),
      _i('basket', 'Basket', PhosphorIconsRegular.basket),
      _i('hand_heart', 'Charity', PhosphorIconsRegular.handHeart),
      _i('magic_wand', 'Magic', PhosphorIconsRegular.magicWand, const ['ai']),
      _i('chat_teardrop', 'Message', PhosphorIconsRegular.chatTeardrop),
      _i('phone_call', 'Phone Call', PhosphorIconsRegular.phoneCall),
      _i('phone_incoming', 'Incoming', PhosphorIconsRegular.phoneIncoming),
      _i('phone_outgoing', 'Outgoing', PhosphorIconsRegular.phoneOutgoing),
      _i('envelope_open', 'Mail Open', PhosphorIconsRegular.envelopeOpen),
      _i('archive', 'Archive', PhosphorIconsRegular.archive),
      _i('trash_simple', 'Trash Alt', PhosphorIconsRegular.trashSimple),
      _i('recycle', 'Recycle', PhosphorIconsRegular.recycle),
      _i('shipping_container', 'Container', PhosphorIconsRegular.shippingContainer),
      _i('warehouse', 'Warehouse', PhosphorIconsRegular.warehouse),
      _i('taxi', 'Taxi', PhosphorIconsRegular.taxi),
      _i('train_regional', 'Train Regional', PhosphorIconsRegular.trainRegional),
      _i('atom', 'Atom', PhosphorIconsRegular.atom),
      _i('microscope', 'Microscope', PhosphorIconsRegular.microscope),
      _i('test_tube', 'Test Tube', PhosphorIconsRegular.testTube),
      _i('dna', 'DNA', PhosphorIconsRegular.dna),
      _i('plant', 'Plant', PhosphorIconsRegular.plant),
      _i('tree_evergreen', 'Pine', PhosphorIconsRegular.treeEvergreen),
      _i('orange', 'Orange', PhosphorIconsRegular.orange),
      _i('carrot', 'Carrot', PhosphorIconsRegular.carrot),
      _i('cookie', 'Cookie', PhosphorIconsRegular.cookie),
      _i('cooking_pot', 'Cooking Pot', PhosphorIconsRegular.cookingPot),
      _i('bathtub', 'Bath', PhosphorIconsRegular.bathtub),
      _i('couch', 'Sofa', PhosphorIconsRegular.couch),
      _i('bed', 'Bed', PhosphorIconsRegular.bed),
      _i('lamp', 'Lamp', PhosphorIconsRegular.lamp),
      _i('armchair', 'Armchair', PhosphorIconsRegular.armchair),
      _i('git_pull_request', 'Pull Request', PhosphorIconsRegular.gitPullRequest, const ['git']),
      _i('git_commit', 'Commit', PhosphorIconsRegular.gitCommit, const ['git']),
      _i('git_diff', 'Diff', PhosphorIconsRegular.gitDiff, const ['git']),
      _i('kanban', 'Kanban', PhosphorIconsRegular.kanban),
      _i('flowchart', 'Flowchart', PhosphorIconsRegular.flowArrow),

    ],
  ),
  ThirdPartyIconProvider(
    id: 'cupertino',
    name: 'Cupertino',
    license: 'MIT (Flutter)',
    icons: <ThirdPartyIcon>[
      _i('person', 'Person', CupertinoIcons.person, const ['user']),
      _i('person_2', 'People', CupertinoIcons.person_2, const ['group']),
      _i('cloud', 'Cloud', CupertinoIcons.cloud),
      _i('device_laptop', 'Laptop', CupertinoIcons.device_laptop,
          const ['computer']),
      _i('device_phone', 'Phone', CupertinoIcons.device_phone_portrait,
          const ['mobile']),
      _i('desktopcomputer', 'Desktop', CupertinoIcons.desktopcomputer),
      _i('globe', 'Globe', CupertinoIcons.globe, const ['world']),
      _i('doc', 'Document', CupertinoIcons.doc, const ['file']),
      _i('folder', 'Folder', CupertinoIcons.folder),
      _i('mail', 'Mail', CupertinoIcons.mail, const ['email']),
      _i('building', 'Building', CupertinoIcons.building_2_fill,
          const ['office']),
      _i('calendar', 'Calendar', CupertinoIcons.calendar),
      _i('clock', 'Clock', CupertinoIcons.clock),
      _i('alarm', 'Alarm', CupertinoIcons.alarm),
      _i('printer', 'Printer', CupertinoIcons.printer),
      _i('lock', 'Lock', CupertinoIcons.lock, const ['security']),
      _i('warning', 'Warning', CupertinoIcons.exclamationmark_triangle,
          const ['alert']),
      _i('check', 'Check', CupertinoIcons.checkmark_circle, const ['ok']),
      _i('settings', 'Settings', CupertinoIcons.gear, const ['gear']),
      _i('chart', 'Chart', CupertinoIcons.chart_bar, const ['analytics']),
      _i('camera', 'Camera', CupertinoIcons.camera),
      _i('wifi', 'Wi‑Fi', CupertinoIcons.wifi, const ['network']),
      _i('bluetooth', 'Bluetooth', CupertinoIcons.bluetooth),
      _i('antenna', 'Antenna', CupertinoIcons.antenna_radiowaves_left_right,
          const ['signal']),
      _i('shield', 'Shield', CupertinoIcons.shield, const ['security']),
      _i('house', 'Home', CupertinoIcons.house),
      _i('link', 'Link', CupertinoIcons.link, const ['url']),
      _i('search', 'Search', CupertinoIcons.search),
      _i('download', 'Download', CupertinoIcons.cloud_download),
      _i('upload', 'Upload', CupertinoIcons.cloud_upload),
      _i('bolt', 'Bolt', CupertinoIcons.bolt, const ['zap', 'power']),
      _i('battery', 'Battery', CupertinoIcons.battery_100),
      _i('rocket', 'Rocket', CupertinoIcons.rocket_fill, const ['launch']),
      _i('map', 'Map', CupertinoIcons.map),
      _i('location', 'Location', CupertinoIcons.location, const ['pin']),
      _i('chat', 'Chat', CupertinoIcons.chat_bubble, const ['message']),
      _i('photo', 'Photo', CupertinoIcons.photo, const ['image']),
      _i('video', 'Video', CupertinoIcons.videocam),
      _i('headphones', 'Headphones', CupertinoIcons.headphones),
      _i('cart', 'Cart', CupertinoIcons.cart, const ['shop']),
      _i('creditcard', 'Card', CupertinoIcons.creditcard, const ['payment']),
      _i('gift', 'Gift', CupertinoIcons.gift),
      _i('flag', 'Flag', CupertinoIcons.flag),
      _i('bell', 'Bell', CupertinoIcons.bell, const ['notification']),
      _i('heart', 'Heart', CupertinoIcons.heart),
      _i('star', 'Star', CupertinoIcons.star),
      _i('tag', 'Tag', CupertinoIcons.tag),
      _i('bookmark', 'Bookmark', CupertinoIcons.bookmark),
      _i('trash', 'Trash', CupertinoIcons.trash, const ['delete']),
      _i('plus', 'Plus', CupertinoIcons.plus_circle, const ['add']),
      _i('minus', 'Minus', CupertinoIcons.minus_circle),
      _i('person_add', 'Add Person', CupertinoIcons.person_add, const ['invite']),
      _i('person_badge_plus', 'Person Badge', CupertinoIcons.person_badge_plus),
      _i('person_crop_circle', 'User Circle', CupertinoIcons.person_crop_circle),
      _i('cloud_fill', 'Cloud Fill', CupertinoIcons.cloud_fill),
      _i('folder_open', 'Folder Open', CupertinoIcons.folder_open),
      _i('doc_text', 'Doc Text', CupertinoIcons.doc_text),
      _i('doc_on_doc', 'Copy', CupertinoIcons.doc_on_doc),
      _i('tray_full', 'Inbox Full', CupertinoIcons.tray_full),
      _i('square_list', 'List', CupertinoIcons.square_list),
      _i('news', 'News', CupertinoIcons.news),
      _i('speaker_2', 'Speaker', CupertinoIcons.speaker_2),
      _i('speaker_slash', 'Mute', CupertinoIcons.speaker_slash),
      _i('play', 'Play', CupertinoIcons.play_arrow),
      _i('pause', 'Pause', CupertinoIcons.pause),
      _i('forward_end', 'Skip Next', CupertinoIcons.forward_end),
      _i('backward_end', 'Skip Prev', CupertinoIcons.backward_end),
      _i('arrow_2_circlepath', 'Sync', CupertinoIcons.arrow_2_circlepath),
      _i('arrow_up_doc', 'Upload Doc', CupertinoIcons.arrow_up_doc),
      _i('arrow_down_doc', 'Download Doc', CupertinoIcons.arrow_down_doc),
      _i('paperplane', 'Send', CupertinoIcons.paperplane),
      _i('reply', 'Reply', CupertinoIcons.reply),
      _i('share', 'Share', CupertinoIcons.share),
      _i('scissors', 'Scissors', CupertinoIcons.scissors),
      _i('paperclip', 'Paperclip', CupertinoIcons.paperclip),
      _i('pin', 'Pin', CupertinoIcons.pin),
      _i('placemark', 'Placemark', CupertinoIcons.placemark),
      _i('compass', 'Compass', CupertinoIcons.compass),
      _i('tram_fill', 'Tram', CupertinoIcons.tram_fill),
      _i('car', 'Car', CupertinoIcons.car),
      _i('bus', 'Bus', CupertinoIcons.bus),
      _i('bicycle', 'Bike', CupertinoIcons.car_detailed, const ['bike']),
      _i('airplane', 'Plane', CupertinoIcons.airplane),
      _i('bandage', 'Bandage', CupertinoIcons.bandage, const ['medical']),
      _i('heart_fill', 'Heart Fill', CupertinoIcons.heart_fill),
      _i('hand_raised', 'Hand', CupertinoIcons.hand_raised),
      _i('hand_thumbsup', 'Thumbs Up', CupertinoIcons.hand_thumbsup),
      _i('hand_thumbsdown', 'Thumbs Down', CupertinoIcons.hand_thumbsdown),
      _i('qrcode', 'QR Code', CupertinoIcons.qrcode),
      _i('barcode', 'Barcode', CupertinoIcons.barcode),
      _i('paintbrush', 'Brush', CupertinoIcons.paintbrush),
      _i('color_filter', 'Palette', CupertinoIcons.color_filter),
      _i('crop', 'Crop', CupertinoIcons.crop),
      _i('perspective', 'Perspective', CupertinoIcons.perspective),
      _i('zoom_in', 'Zoom In', CupertinoIcons.zoom_in),
      _i('zoom_out', 'Zoom Out', CupertinoIcons.zoom_out),
      _i('arrow_clockwise', 'Rotate CW', CupertinoIcons.arrow_clockwise),
      _i('arrow_counterclockwise', 'Rotate CCW', CupertinoIcons.arrow_counterclockwise),
      _i('timer', 'Timer', CupertinoIcons.timer),
      _i('hourglass', 'Hourglass', CupertinoIcons.hourglass),
      _i('lock_shield', 'Shield Lock', CupertinoIcons.lock_shield, const ['security']),
      _i('eye', 'Eye', CupertinoIcons.eye),
      _i('eye_slash', 'Hide', CupertinoIcons.eye_slash),
      _i('info', 'Info', CupertinoIcons.info),
      _i('question', 'Help', CupertinoIcons.question, const ['help']),
      _i('xmark_circle', 'Cancel', CupertinoIcons.xmark_circle),
      _i('minus_slash_plus', 'Plus Minus', CupertinoIcons.minus_slash_plus),
      _i('number', 'Hash', CupertinoIcons.number),
      _i('at', 'At', CupertinoIcons.at),
      _i('money_dollar', 'Dollar', CupertinoIcons.money_dollar),
      _i('bag', 'Bag', CupertinoIcons.bag),
      _i('archivebox', 'Archive', CupertinoIcons.archivebox),
      _i('square_arrow_up', 'Export', CupertinoIcons.square_arrow_up),
      _i('square_arrow_down', 'Import', CupertinoIcons.square_arrow_down),
      _i('macwindow', 'Window', CupertinoIcons.macwindow),
      _i('layers', 'Layers', CupertinoIcons.layers),
      _i('square_grid_2x2', 'Grid', CupertinoIcons.square_grid_2x2),
      _i('list_bullet', 'Bullets', CupertinoIcons.list_bullet),
      _i('list_number', 'Numbers', CupertinoIcons.list_number),
      _i('textformat', 'Text', CupertinoIcons.textformat),
      _i('bold', 'Bold', CupertinoIcons.bold),
      _i('italic', 'Italic', CupertinoIcons.italic),
      _i('underline', 'Underline', CupertinoIcons.underline),
      _i('text_quote', 'Quote', CupertinoIcons.text_quote),
      _i('moon_stars', 'Night', CupertinoIcons.moon_stars),
      _i('sun_max', 'Sun', CupertinoIcons.sun_max),
      _i('cloud_sun', 'Partly Cloudy', CupertinoIcons.cloud_sun),
      _i('cloud_rain', 'Rain', CupertinoIcons.cloud_rain),
      _i('cloud_snow', 'Snow', CupertinoIcons.cloud_snow),
      _i('flame', 'Flame', CupertinoIcons.flame),
      _i('drop', 'Drop', CupertinoIcons.drop),
      _i('leaf_arrow_circlepath', 'Eco', CupertinoIcons.leaf_arrow_circlepath),
      _i('hammer', 'Hammer', CupertinoIcons.hammer),
      _i('wrench', 'Wrench', CupertinoIcons.wrench),
      _i('lightbulb', 'Idea', CupertinoIcons.lightbulb),
      _i('gamecontroller', 'Game', CupertinoIcons.gamecontroller),
      _i('sportscourt', 'Sports', CupertinoIcons.sportscourt),
      _i('ticket', 'Ticket', CupertinoIcons.ticket),
      _i('tv', 'TV', CupertinoIcons.tv),
      _i('music_note', 'Music', CupertinoIcons.music_note),
      _i('mic', 'Mic', CupertinoIcons.mic),
      _i('videocam_circle', 'Video Circle', CupertinoIcons.videocam_circle),
      _i('camera_rotate', 'Flip Camera', CupertinoIcons.camera_rotate),
      _i('photo_on_rectangle', 'Photos', CupertinoIcons.photo_on_rectangle),

    ],
  ),
];

/// Flat lookup map: `providerId/iconId` → entry.
final Map<String, ThirdPartyIcon> kThirdPartyIconByKey = <String, ThirdPartyIcon>{
  for (final p in kThirdPartyIconProviders)
    for (final icon in p.icons) '${p.id}/${icon.id}': icon,
};

/// Lookup provider by [id], or null.
ThirdPartyIconProvider? findThirdPartyIconProvider(String id) {
  for (final p in kThirdPartyIconProviders) {
    if (p.id == id) return p;
  }
  return null;
}

/// Lookup icon by provider + id, or null.
ThirdPartyIcon? findThirdPartyIcon(String providerId, String iconId) =>
    kThirdPartyIconByKey['$providerId/$iconId'];

/// Provider id for a catalog [icon] instance, or null if not from the catalog.
String? findProviderIdForIcon(ThirdPartyIcon icon) {
  for (final p in kThirdPartyIconProviders) {
    if (p.icons.contains(icon)) return p.id;
  }
  return null;
}

/// True if [icon] matches a lowercase [query] (name, id, or keywords).
bool thirdPartyIconMatches(ThirdPartyIcon icon, String query) {
  if (query.isEmpty) return true;
  if (icon.name.toLowerCase().contains(query)) return true;
  if (icon.id.toLowerCase().contains(query)) return true;
  for (final k in icon.keywords) {
    if (k.contains(query)) return true;
  }
  return false;
}

/// Paint [icon] to a transparent PNG suitable for embedding in the document.
Future<Uint8List> rasterizeThirdPartyIcon(
  IconData icon, {
  int size = kThirdPartyIconRasterPx,
  Color color = kThirdPartyIconDefaultColor,
}) async {
  final recorder = ui.PictureRecorder();
  final canvas = Canvas(recorder);
  final fontSize = size * 0.72;
  final tp = TextPainter(
    text: TextSpan(
      text: String.fromCharCode(icon.codePoint),
      style: TextStyle(
        fontSize: fontSize,
        fontFamily: icon.fontFamily,
        package: icon.fontPackage,
        color: color,
      ),
    ),
    textDirection: TextDirection.ltr,
  )..layout();
  final dx = (size - tp.width) / 2;
  final dy = (size - tp.height) / 2;
  tp.paint(canvas, Offset(dx, dy));
  final picture = recorder.endRecording();
  final image = await picture.toImage(size, size);
  final bytes = await image.toByteData(format: ui.ImageByteFormat.png);
  image.dispose();
  picture.dispose();
  if (bytes == null) return Uint8List(0);
  return bytes.buffer.asUint8List();
}

// ---------------------------------------------------------------------------
// Persistence / rebuild helpers (Charts-style userCells)
// ---------------------------------------------------------------------------

/// Metadata keys written onto icon picture shapes.
abstract final class IconOps {
  IconOps._();

  static const String userIcon = 'visioeditor.Icon';
  static const String userProvider = 'visioeditor.IconProvider';
  static const String userId = 'visioeditor.IconId';
  static const String userColor = 'visioeditor.IconColor';

  static const int defaultColorArgb = 0xFF243040;

  static bool isIcon(VsdxShape s) {
    for (final c in s.userCells) {
      if (c.name == userIcon && (c.value == '1' || c.value == 'true')) {
        return true;
      }
    }
    return false;
  }

  static String? providerId(VsdxShape s) {
    for (final c in s.userCells) {
      if (c.name == userProvider) return c.value;
    }
    return null;
  }

  static String? iconId(VsdxShape s) {
    for (final c in s.userCells) {
      if (c.name == userId) return c.value;
    }
    return null;
  }

  static int colorArgb(VsdxShape s) {
    for (final c in s.userCells) {
      if (c.name == userColor) {
        final raw = (c.value ?? '').trim();
        var hex = raw.startsWith('#') ? raw.substring(1) : raw;
        if (hex.length == 6) hex = 'FF$hex';
        final v = int.tryParse(hex, radix: 16);
        if (v != null) return v;
      }
    }
    return defaultColorArgb;
  }

  static String formatColor(int argb) =>
      '#${argb.toRadixString(16).padLeft(8, '0').substring(2).toUpperCase()}';

  static List<VsdxUserCell> meta({
    required String providerId,
    required String iconId,
    required int colorArgb,
  }) =>
      <VsdxUserCell>[
        const VsdxUserCell(name: userIcon, value: '1'),
        VsdxUserCell(name: userProvider, value: providerId),
        VsdxUserCell(name: userId, value: iconId),
        VsdxUserCell(name: userColor, value: formatColor(colorArgb)),
      ];

  static ThirdPartyIcon? resolve(VsdxShape s) {
    final p = providerId(s);
    final id = iconId(s);
    if (p == null || id == null) return null;
    return findThirdPartyIcon(p, id);
  }
}
